### PR TITLE
Deduplicating Vectors for Space Optimization

### LINKED ISSUE #2795: [RFC] Deduplicating Vectors from Flat Index Storage to Optimize Space
# Deduplicating Flat Vectors

## **1. Abstract**

This document presents two solutions for deduplicating full-precision vectors in a FAISS index within OpenSearch. Currently, flat vectors are stored in both `.vec` and `.faiss` files, resulting in redundant data and increased resource usage.
With this optimization, the index size was reduced from 45 GB to 16 GB for FP16, from 59 GB to 32 GB for FP32 (FYI, Lucene has 30GB), 64% improvement. This deduplication also led to a 22% reduction in indexing throttle time (from 350 min to 272 min) and a 66% drop in total merge byte size (from 79.61 GB to 27.02 GB). Additionally, merge throttling time decreased by 66%, going from 33 min to 11 min. Memory efficiency also improved significantly, with JVM (off-heap) buffer memory dropping from 59.95 GB to 32.43 GB, 45% reduction.

The document starts with the problem statement, outlines benchmarking results, and provides a focused comparison of the two solutions, highlighting their implementation details, advantages, and trade-offs.

## **2. Scope**

The proposed solutions apply specifically to **FAISS HNSW indexing** and are **not applicable to IVF**.
This optimization targets cases where vectors are of type FP32, FP16, Byte and Pure Binary(case where user ingest already quantized bytes). 

## **3. Background**

OpenSearch’s k-NN plugin uses **FAISS with HNSW** for ANN(Approximate Nearest Neighbor Search) search. The figure below shows how vectors are currently indexed and stored in the system.

### **3.1. How We Are Storing Vectors**

When users send documents to OpenSearch, they are first temporarily buffered (Lucene’s [DocumentsWriterPerThread](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java)) then flushed into storage via [IndexOutput](https://lucene.apache.org/core/10_0_0/core/org/apache/lucene/store/IndexOutput.html).
For each document, the [NativeEngines990KnnVectorsWriter::addField](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L76) method is called for every vector-type field, and these fields are added to the buffer ([Lucene99FlatVectorsWriter::addValue](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99FlatVectorsWriter.java#L455)). Once flushing is triggered,
[NativeEngines990KnnVectorsWriter::flush()](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L93) method iterates all buffered vectors and begins writing data to disk.

During flushing:

* An [NativeIndexWriter](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java) requests a vector writer to handle vector storage.
* Based on the engine configuration (Native or Lucene), `[PerFieldKNNVectorFormat](https://github.com/opensearch-project/k-NN/blob/ee3f2625efea27d410219b939f4ff66ed5b9ce98/src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java#L156)` returns the appropriate writer.
* This writer writes vector data into a **new segment** on storage, creating two files:
    * `.vec` — stores flat vectors
    * `.faiss` — stores the HNSW graph and also vectors (if quantization is not used, flat vectors will have full precision vectors to be stored again, causing **duplication between `.vec`**)

This describes how vectors are stored during the **flush** process, one segment at a time.

### **3.2 How We Are Doing Exact Search**

For exact search, the current implementation retrieves relevant vectors based on the search query and then performs comparisons using a distance function (e.g., L2 or cosine) to compute similarity scores.
For the details, refer to [here](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/ExactSearcher.java#L65).

### **3.3 How We Are Doing Merge**

During merging, OpenSearch combines multiple segments, each of which typically contains its own `.vec` and `.faiss` files.
By default, both flat vectors and HNSW graphs are written during indexing and merge. However, this behavior can be controlled using the setting: [index.knn.advanced.approximate_threshold](https://docs.opensearch.org/docs/latest/vector-search/performance-tuning-indexing/)

* If this is set to `-1`, **.faiss file creation is skipped during indexing**, and only the `.vec` file is written with flat vectors.
* During merge, vectors are read from the `.vec` file only.
* It's important to change this setting to `0` **before triggering a force merge**. Otherwise, users would need to **reindex** their data.

In the `[mergeOneField()](https://github.com/opensearch-project/k-NN/blob/b62528c05630d42f26984e16ed53d16d420754e7/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L136)` method:

* Vectors from all source segments are read and written into a new merged segment:
    * A new `.vec` file with flat vectors.
    * A new `.faiss` file with vectors and the HNSW graph (if not skipped by the setting).

**Both flush and merge store the same flat vectors twice(FP32, Byte and Pure Binary Cases),** once in `.vec`, and again in `.faiss`, leading to significant **storage duplication**. Eliminating this redundancy is the main motivation for the optimization discussed in this document.
* * *

## **4. Problem Statement**

For FP32, Byte, and Pure Binary cases, maintaining **two copies of the same vectors** in both `.vec` and `.faiss` files is redundant. Both approximate and exact search operations can run on a **single set of vectors**, making it possible to eliminate this duplication safely. 
For FP16, the `.vec` file stores full-precision vectors, while the `.faiss` file stores a scalar-quantized FP16 representation.

### **Key issues in the current flow:**

1. **Redundant Storage**
     Flat vectors are stored in both `.vec` and `.faiss` files, effectively doubling storage for each segment.
2. **Increased Merge Overhead**
     During segment merges, duplicated vectors are read and re-written, leading to unnecessary compute and I/O costs.
    1. By removing redundancy, the system writes fewer bytes to disk and reads less data during segment consolidation. This not only reduces the overall I/O load but also makes merge operations significantly faster and more efficient.
    2. This optimization significantly reduces I/O amplification caused by default merge policy [TieredMergePolicy](https://lucene.apache.org/core/10_0_0/core/org/apache/lucene/index/TieredMergePolicy.html) — since vectors are no longer stored twice, the total I/O volume during merges drops considerably. In practice, this has shown over **66% reduction in total merge bytes**, leading to **more than 50% decrease in I/O cost**, faster merges, and improved system throughput.
3. **Higher Operational Cost**
     Larger index sizes increase disk and memory usage, resulting in higher infrastructure costs for OpenSearch users. 
4. **Reduced MMap Overhead:** 

When vector files are memory-mapped, the operating system loads them into memory using the mmap mechanism.
(Note that we are using [MMapDirectory](https://lucene.apache.org/core/10_0_0/core/org/apache/lucene/store/MMapDirectory.html) by default)
 Large or redundant files increase pressure on the **kernel’s virtual memory system**, leading to higher **page cache usage** and potential eviction of other useful data.
By eliminating duplicate vector data, this optimization **reduces the size of memory-mapped files**, lowering:

    1. Kernel memory pressure
    2. Page faults
    3. And overall resident memory usage

# 5. Performance Results

To validate the effectiveness of the vector deduplication optimization, we measured its impact under two conditions: **pure indexing workload** and a **stress scenario involving indexing + search under constrained memory**.

## 5.2. Pure Indexing Performance (Indexing Only, No Search)

Under a standard indexing workload, we observed substantial improvements across key metrics after applying the optimization:

* **Merge I/O Reduction
    **The `merges.total_size_in_bytes` decreased from **79.61 GB** to **27.02 GB**, a **66% reduction**, highlighting that duplicate vectors were eliminated from merge operations.
* **Merge Throttling Time**
     The `merges.total_throttled_time_in_millis` also saw a **66% reduction**, dropping from **1,990,087 ms** to **669,256 ms**, showing merge phases completed more efficiently.
* **JVM Direct Memory Pressure**
     Off-heap memory usage under `jvm.buffer_pools` reduced from **59.95 GB** to **32.43 GB**, reflecting a **45% improvement** in memory footprint due to smaller segment sizes.
* **Indexing Throttling Time**
     The `indexing.throttle_time_in_millis` dropped by **22%**, decreasing from **21,046,833 ms** in the baseline to **16,321,000 ms**, indicating lower back pressure during document ingestion.

#### Indexing & Merging Breakdown

* **Flush Phase**
     While flush operations benefit from smaller vector data, the improvement is moderate — around **22%** less throttling time, suggesting having `.vec` included in flush is less sensitive to vector duplication.
* **Merge Phase**
     This is where the optimization shows the greatest value:
    * Merge duration improved by **18.14%**, from **381.22 minutes** down to **312.05 minutes**.
    * Merge throttling saw a dramatic **73% reduction**, from **8.72 minutes** to **2.33 minutes**.

**Additional Benefit:** 
**Faster Remote Recovery, Replication:**  Because the segment size is nearly halved, remote recovery or replication operations are expected to complete roughly twice as fast.

## 5.3. Indexing + Search Under Memory Pressure

To test the robustness and efficiency of the deduplication optimization under stress, we simulated an environment where indexing and search operations run concurrently in a memory-constrained setting. The benchmark was run with a query-per-second (QPS) of 1, ensuring that all segments remain loaded during indexing. This setup is designed to evaluate the system’s behavior and limits from a memory pressure perspective.
The results indicate that the optimization significantly improves system stability, reduces memory overhead, and enables more efficient handling of concurrent indexing and search workloads.

**Key Observations:**

* **High CPU I/O Wait in Baseline**
    * The baseline setup exhibited significantly higher **CPU I/O wait time**, indicating the system was frequently stalled waiting on disk I/O. This behavior was mitigated in the optimized approach, reflecting reduced disk operations due to smaller segment files and the removal of duplicated vector writes.
    * 
* **Search Latency**
    * Search latency under concurrent indexing showed 20–30% improvement with the optimized approach. Reduced memory and disk pressure contributed to faster access to vector data during query execution. At extreme memory pressure, the performance gap widens up to 300%
    * 
* Page Faults
    * A sharp drop in page faults was observed: 
        * **Baseline**: 14.33 million
        * **Optimized**: 3.13 million
    * A **78.15% reduction**, highlighting better memory locality and fewer interruptions due to paging.
* #Segments and Merge Behavior
    * Due to smaller segment sizes in the optimized approach, the system can **merge more segments together** during force merges. This leads to Fewer total segments.
    * This aligns well with **Lucene’s Tiered merge policy**, which operates on a fixed I/O budget and merges similar-sized segments into intermediate layers before combining them further
        * Ref - https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/TieredMergePolicy.java#L30-L68
    * 
* System Stability During Merge
    * In the baseline case, the server **crashed during segment merging**, primarily due to large segment sizes and memory exhaustion. Since we are constantly sending query, this keeps all segments alive in memory.
         In contrast, with the optimized solution, **merges completed without failure**, due to smaller segments that required less memory and I/O.
         This demonstrates that the optimization **increased operational limits**, allowing the system to handle larger workloads more reliably.
    * 

A benchmarking table below provides a comparison between the current (base) implementation and the optimized version.

**Base Code Results V/S Optimized Approach Results**

|	|Base Code	|Optimized Approach	|Improvement	|
|---	|---	|---	|---	|
|Disk Usage (GB)	|45GB	|16GB	|~64%↓	|
|disk_used_percent	|42.7333	|22.40333	|~48%↓	|
|diskio_writes	|50,164	|42,598.66667	|~15%↓	|
|diskio_write_bytes	|3.07G	|1.82G	|~40%↓	|
|diskio_reads	|167,339.66667	|61,301	|~63%↓	|
|diskio_read_bytes	|7.54G	|6.99G	|~7%↓	|
|	|	|	|	|
|Ingestion Throughput (docd/sec)	|	|	|	|
|Min Throughput	|1045.04333	|917.57667	|~12%↓	|
|Mean Throughput	|1967.04333	|1707.79667	|~13%↓	|
|Median Throughput	|1620.61	|1226.59	|~24%↓	|
|Max Throughput	|9657.77	|9588.83667	|~0.7%↓	|
|	|	|	|	|
|Ingestion Latency	|	|	|	|
|50th percentile latency	|118.95343	|122.34855	|~0.2%↑	|
|90th percentile latency	|213.79453	|192.81594	|~0.9↓	|
|99th percentile latency	|426.58207	|364.79083	|~14%↓	|
|99.9th percentile latency	|222769.59853	|330550.76061	|~48%↑	|
|99.99th percentile latency	|1016394.44591	|817674.40804	|~19%↓	|
|100th percentile latency	|2241311.66279	|1302300.90822	|~41%↓	|
|	|	|	|	|
|	|	|	|	|
|Mean recall@k	|0.95	|0.95	|	|
|Mean recall@1	|0.97667	|0.97667	|	|

* * *

# **6. Solution Proposed**

## 6.1. How we are loading vectors in recommended approach?

For vector loading we are making use of Lucene’s FlatVectorReader which in turn uses IndexInput. 
For reference: **[Loading logic](https://quip-amazon.com/6L0dAH0CasTc/POC-Deduplicating-Flat-Vectors#temp:C:YQQdca394027b474d17ae1ac9529)**

## 6.2. Ongoing SIMD Project — Manasvi

**What is SIMD?**
**SIMD (Single Instruction, Multiple Data)** is a type of parallel computing architecture where a single CPU instruction is applied to multiple data elements simultaneously. It leverages **wide vector registers** (128-bit, 256-bit, or 512-bit) to process multiple values in one operation.

**How We Use SIMD in Our Project?**
In our project, we work with vectors data that we want to store in half-precision (FP16) format to save memory and I/O bandwidth. 
To optimize this process, we use SIMD instructions to accelerate the conversion:

* **x86 (Intel AVX-512)**: We use `_mm512_cvtph_ps` to convert 16 FP16 values to FP32 in a single instruction. 
    * [Code ref. X86](https://quip-amazon.com/6L0dAH0CasTc/POC-Deduplicating-Flat-Vectors#temp:C:YQQd945cdefaa0a4777aa15d83d9)
* **ARM (NEON with FP16 support)**: We use `vcvt_f32_f16` to perform 4-wide FP16 to FP32 conversion on Graviton-based EC2 instances. 
    * [Code ref. ARM](https://quip-amazon.com/6L0dAH0CasTc/POC-Deduplicating-Flat-Vectors#temp:C:YQQd6e62e24142f49a9ac4ee573e)

This allows us to process entire vectors in chunks rather than converting each float individually in a loop.

**How we embed this SIMD logic in deduplicating vectors project?**
To support FP16, we plan to store FP16 vectors in the `.vec` file, this is made possible by using the second part of **Manasvi’s** project. In her implementation, she is developing a custom reader/writer that can write FP32 vectors to the `.vec` file as FP16 byte representations and read FP16 bytes from the `.vec` file while converting them back to FP32.
By reusing her project’s custom reader/writer and conversion logic, our project can seamlessly handle FP16 storage and retrieval without implementing separate conversion logic, ensuring reducing overhead.
[Lucene99FlatVectorsReader](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99FlatVectorsReader.java)
[Lucene99FlatVectorsWriter](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99FlatVectorsWriter.java)

## **6.3. Solutions Overview**

We propose two solutions.

#### **[Recommended] Approach 1: Remove Flat Vectors from the `.faiss` File and Save FP16 in `.vec` file**

In this approach, we eliminate the flat vector section from the `.faiss` file and continue storing all flat vectors, including FP16 in the `.vec` file. At index load time, vectors are retrieved from the `.vec` file into the JVM heap and subsequently passed to native C++ memory. To support storing FP16 vectors in the `.vec` file, we are going to use Manasvi’s implementation, which introduces a new datatype for FP16 vectors. This will make `.vec` file the single source of flat vector data. This solution reduces the storage significantly(~64 %) and the reduced size of `.faiss` file will also help in simplifying the GPU pipeline.
Experimental benchmarking demonstrates **major storage savings**:

1. Base implementation: ~45 GB.
2. Optimized approach: ~16 GB. This shows we can **approximately reduce disk usage by 64%**, which in turn improves **cost efficiency** and **disk I/O performance.**

#### **[Alternative] Approach 2: Remove Flat** **Vectors** **from the `.vec` File**

In this approach, we stop writing flat vectors to the `.vec` file during both flush and merge phases. Instead, vector data is stored and retrieved **exclusively from the `.faiss` file**. (Assuming the  `index.knn.advanced.approximate_threshold` setting is not set to `-1`. More details on this setting and its impact are discussed in the section — [Note: If the user sets index.knn.advanced.approximate_threshold = -1, .faiss file construction is explicitly skipped. In such cases, the system must…](https://quip-amazon.com/6L0dAH0CasTc#temp:C:YQQ74a836c773344483ae47670eb))
This eliminates dependency on `.vec`, reduces index size, and simplifies the indexing flow by using **just one file** (`.faiss` file), to store all vector information.

## **6.4. Conversion Overhead Status for FP16 With SIMD**

Regardless of the approach, FP16 introduces conversion cost, but with SIMD, the impact is negligible.

### Faiss C++

|	|Recommended Approach With SIMD	|Alternative Approach With SIMD	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in ANN search	|No Issue	|No Issue	|
|Conversion overhead (FP16 → FP32) in merge	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Conversion overhead in exact search	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

### LuceneOnFaiss

|	|Recommended Approach With SIMD	|Alternative Approach With SIMD	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in search	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Conversion overhead (FP16 → FP32) in merge	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Conversion overhead in exact search	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

## **6.5. Conversion Overhead Status for FP16 Without SIMD**

Regardless of which approach we take, FP16 introduces conversion cost, but with SIMD, the impact is negligible.
We have to use Float.float16ToFloat in Java 
And saying that due to the conversion cost, we will likely see 2-3x slower performance in derived source + exact search.
[JAVA Code for conversion:](https://quip-amazon.com/6L0dAH0CasTc#temp:C:YQQ7cad450b2b3b4572836542119)

### Faiss C++

|	|Recommended Approach	|Alternative Approach	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in ANN search	|No Issue	|No Issue	|
|Conversion overhead (FP16 → FP32) in merge	|There would be conversion cost	|There would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|There would be conversion cost	|There would be conversion cost	|
|Conversion overhead in exact search	|There would be conversion cost	|There would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

### LuceneOnFaiss

|	|Recommended Approach	|Alternative Approach	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in search	|There would be conversion cost	|There would be conversion cost	|
|Conversion overhead (FP16 → FP32) in merge	|There would be conversion cost	|There would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|There would be conversion cost	|There would be conversion cost	|
|Conversion overhead in exact search	|There would be conversion cost	|There would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

### **6.6.1. Implementation Methodology**

This approach removes flat vectors from the `.faiss` file and relies entirely on the .`vec` file for vector storage. Below is a detailed breakdown of how this works during flush, merge, and search.

**For conversion overhead: We are going to use SIMD optimization(FP16 to FP32).**

* We are already making use of SIMD on FAISS side of the code. 
    * [ScalerQuantizer.cpp](https://github.com/facebookresearch/faiss/blob/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64/faiss/impl/ScalarQuantizer.cpp)

#### **6.6.1.1. `flush()` Logic – Skip Flat Vector Section in `.faiss` File**

In this approach, the flush flow largely mirrors the default indexing behavior, with one key difference:

* Flat vectors are still written to the **`.vec` file** as usual.
* When the `.faiss` index is created, the C++ layer **skips writing the flat vector section**.

```
void write_index(const Index* idx, IOWriter* f, int io_flags) {
    if (...) {
        
    } else if (const IndexFlat* idxf = dynamic_cast<const IndexFlat*>(idx)) {
        uint32_t h =
                fourcc(idxf->metric_type == METRIC_INNER_PRODUCT ? "IxFI"
                               : idxf->metric_type == METRIC_L2  ? "IxF2"
                                                                 : "IxFl");
        WRITE1(h);
        write_index_header(idx, f);
        
        commenting this line will stop writing flat vectors to .faiss file
        // WRITEXBVECTOR(idxf->codes);
    } else if (...) {
       ...
    }
    ...
    ...
 }
```

 [index_write.cpp](https://github.com/facebookresearch/faiss/blob/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64/faiss/impl/index_write.cpp#L403)

* The logic is modified to exclude the flat vector data while writing the index in `.faiss` file.
* **This creates a segment having both `.faiss` and `.vec` files**, but avoids duplication of vector storage between the two.

As a result:

* The `.faiss` file contains the **HNSW graph** and the associated **ID mapping** (linking internal FAISS vector IDs to Lucene doc IDs).
* The `.vec` file contains full-precision flat vectors and, with the new implementation, can also store FP16 vectors.
* This creates a segment with both `.faiss` and `.vec` files, but avoids duplication of vector storage between the two files.

#### **6.6.1.2. Loading logic – Read from `.vec` File in Faiss C++**

In the loading path (e.g. search, warm up), we implement support to construct the FAISS index by reading vectors from `.vec` via the Java-side `VectorReader(new implementation)`.
Vectors are read from the `IndexInput` on the Java side, then passed into C++ off-heap memory through JNI for FAISS to build the index. This enables FAISS to construct HNSW graphs even though the `.faiss` file initially did not contain vector data.

Key Changes: To read flat vectors directly from IndexInput, we modified the FAISS-native I/O pipeline to bridge Java and C++. 

C++ Side:

* **We have `[FaissOpenSearchIOReader](https://github.com/opensearch-project/k-NN/blob/ee3f2625efea27d410219b939f4ff66ed5b9ce98/jni/include/faiss_stream_support.h#L34)`**, which **inherits from `[faiss::IOReader](https://github.com/facebookresearch/faiss/blob/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64/faiss/impl/io.h#L27)`**.
* We **introduced a new virtual method `copy()` in the base `IOReader` interface**, allowing custom vector loading behavior.
* `FaissOpenSearchIOReader` **overrides `copy()`**, and inside this method:
    * JNI is used to **call Java's `VectorReader.next()`** method.
    * One vector is fetched from the Java side per call and passed to FAISS in-memory for index construction.

#### **Java Side:**

* A new class **`VectorReader`** wraps `FloatVectorValues` for a Lucene segment.
* Inside `VectorReader`, we expose a **`next()` method**, which:
    * Calls `iterator.nextDoc()` to advance to the next document and get its **doc ID**.
    * Uses that doc ID to fetch the vector via `floatVectorValues.vectorValue(docId)`.
    * Returns the resulting `float[]` vector.

####  Flow:

* Instead of reading flat vectors from `.faiss`, FAISS internally requests vectors via the `IOReader::copy()` method.
* This calls into the Java `VectorReader.next()` and pulls data from the `.vec` file.

[index_read.cpp](https://github.com/facebookresearch/faiss/blob/dd0d40b57e617ac4b3e165c5e6739d19cca55eff/faiss/impl/index_read.cpp#L684)

Java Code Snippet:

```
public class VectorReader {
    private final FloatVectorValues floatVectorValues;
    private final DocIndexIterator iterator;

    public VectorReader(FloatVectorValues floatVectorValues) {
        ...
        ...
    }
    
`    // This will allow the copy method in the C++ side to read vectors`
    public float[] next() throws IOException {
        int docId = iterator.nextDoc();
        if (docId != DocIndexIterator.NO_MORE_DOCS) {
            return floatVectorValues.vectorValue(docId);
        } else {
            return null;
        }
    }
}
```

C++ Code Snippet:

```
class FaissOpenSearchIOReader final : public faiss::IOReader {
public:
    explicit FaissOpenSearchIOReader(NativeEngineIndexInputMediator* _mediator)
        ... // constructor things
    }

    // We overrides the copy() method of io.h and used it to get vectors from Java side VectorReader.
    bool copy(void* dest, int expectedByteSize) final{
        JNIEnv* env = cachedEnv;

        // Get float[] from JVM
        jfloatArray vector = (jfloatArray) env->CallObjectMethod(vectorReaderGlobalRef, nextMid);

        if (env->ExceptionCheck() || vector == nullptr) {
            return false;
        }

        // Prepare copy
        jsize length = env->GetArrayLength(vector);
        jfloat* elems = env->GetFloatArrayElements(vector, nullptr);

        JNIReleaseElements release_elems([=]() {
            env->ReleaseFloatArrayElements(vector, elems, JNI_ABORT);
        });

        int vectorByteSize = sizeof(float) * length;
        if (vectorByteSize != expectedByteSize) {
            return false;
        }

        // Copy Java float[] to C++ float[]
        std::memcpy(dest, elems, vectorByteSize);

        return true;
    }

};
```

#### **6.6.1.3. Exact Search** 

Exact search continues to follow the **default flow**. Codec layer will load flat vectors from the appropriate source and these vectors are then passed to the exact search component.

#### **6.6.1.5. Backward Compatibility**

There are no backward compatibility issues with this solution. It remains fully backward compatible, as it only modifies the way flat vectors are written during flush and merge operations. The `.vec` file continues to store all flat vectors, and now also includes FP16 vectors.
To support FP16 storage and retrieval, a custom reader and writer will be implemented. These components will handle all necessary conversions and ensure seamless integration without affecting existing functionality.

#### **Pros**

1. ****GPU Indexing Pipeline Optimization:****
     Removing flat vectors from the `.faiss` file results in a much smaller index file, which can:
    1. Speed up downloads in GPU-accelerated pipelines.
    2. Reduce network transfer time and storage costs, especially in distributed deployments.
    3. Additionally, with the proposed approach, the merge phase can be skipped entirely.
2. There is no need to create a bi-directional mapping table (Lucene’s Doc ID to Internal vector ID) as it’s already present in `.vec` file.
3. We reduce storage by 66% using FP16, and also get similar performance to FP32 when SIMD is used.

#### Cons:

1. Since we plan to use SIMD to mitigate the conversion overhead, users can benefit from reduced latency. However, older versions of CPU may not support SIMD, so users will need to migrate to a new instance having a modern chip to take advantage of this optimization.
    1. Without SIMD, latency increases by up to 3x
2. Since we now store FP16 in the `.vec` file, users might see a drop in recall when reindexing to a schema that expects FP32. However, this is a rare and edge case scenario.

### **6.7.1. Implementation Methodology**

This solution removes the dependency on `.vec` files by ensuring that flat vectors are written and read only through the `.faiss` index. This requires changes across three core components:

#### **6.7.1.1. `flush()` Logic – Remove `.vec` File Writing**

In the `flush()` method of `NativeEngines990KnnVectorsWriter`, the logic responsible for writing flat vectors to the `.vec` file is removed. Instead, only the `.faiss` index is built and flushed to disk.

* During flush, a new segment is created, but only the FAISS index is written.
* The `.vec` file is still created structurally, because the codec expects a `.vec` file to exist for compatibility and versioning purposes. However the `.vec` file remains nearly empty —
    **Before optimization**: ~28.8 GB per segment
    **After optimization**: ~630 B per segment (header only, no vector payload)

**Note:** If the user sets `index.knn.advanced.approximate_threshold = -1`, `.faiss` file construction is explicitly skipped. In such cases, the system must **spill flat vectors to the `.vec` file**, as no `.faiss` file is created.

```
public void flush(int maxDoc, finsl Sorter.DocMap sortMap){
    // We can comment this out, so that we don't store vectors in .vec file
    // flatVectorsWriter.flush(maxDoc, sortMap);
    for (final NativeEngineFieldVectorsWriter<?> field : fields) {
        final FieldInfo fieldInfo = field.getFieldInfo();
        final VectorDataType vectorDataType = extractVectorDataType(fieldInfo);
        int totalLiveDocs = field.getVectors().size();
        if (totalLiveDocs == 0) {
            ...
    ...
}
```

#### **6.7.1.2. `mergeOneField()` Logic – Read from `.faiss` File Only**

During segment merging:

* When HNSW graph construction is enabled, flat vectors are not read from `.vec` files.
    * Instead, an iterator extracts vectors directly from the `.faiss` file of each input segment.
* When graph construction is skipped (i.e., `index.knn.advanced.approximate_threshold = -1`), vectors are read from `.vec` files, since `.faiss` is not written.
* From an implementation perspective, we first attempt to get the `Iterator<float[]>` from the `.faiss` file. If this fails (e.g., due to the absence of `.faiss`), we gracefully fall back to loading vectors from the `.vec` file instead.

This change ensures that:

* In the default case only `.faiss` files are read and written during the merge.
* Duplicate storage of flat vectors is avoided.
* The merged segment ends up with:
    * A `.faiss` file containing both the HNSW graph and vectors.
    * A `.vec` file that is created structurally but has **no flat vector section**.

**Note:** When the user disables graph creation (`approximate_threshold = -1`), flat vectors are written to the `.vec` file, and `.faiss` file is skipped entirely.

```
public void mergeOneField(final FieldInfo fieldInfo, final MergeState mergeState) throws IOException {
    // This will ensure that we are not merging the Flat Vectors int .vec file.
    // flatVectorsWriter.mergeOneField(fieldInfo, mergeState);
           
       final VectorDataType vectorDataType = extractVectorDataType(fieldInfo);
       final Supplier<KNNVectorValues<?>> knnVectorValuesSupplier = getKNNVectorValuesSupplierForMerge(
       vectorDataType,
       fieldInfo,
       mergeState
       );
       int totalLiveDocs = getLiveDocs(knnVectorValuesSupplier.get());
       if (totalLiveDocs == 0) {
           log.debug("[Merge] No live docs for field {}", fieldInfo.getName());
           return;
       }
       ...
       ...
       ...
        
  }
```

#### **6.7.1.3. Exact Search – Use `.faiss` for Flat Vectors**

There are **no changes required** in the exact searcher. The codec layer is responsible for loading flat vectors from the appropriate source. These vectors are then passed to the exact search component transparently.

#### **6.7.1.4. Sparse Case Handling**

In sparse scenarios, **not every Lucene document contains a vector**. FAISS, in this case, stores vectors **only for documents that have them**. As a result, the internal FAISS vector IDs do not directly align with Lucene doc IDs.
To support exact search in such cases, a **reverse mapping** is required—from Lucene doc ID to FAISS vector ID.
Example:

* If only Lucene doc IDs 0 and 4 have vectors, FAISS will assign them vector IDs 0 and 1.
* A mapping must be maintained:

{
0 : 0,  → Mapping Lucene Id 0 to its internal vector id 0
4 : 1  → Mapping Lucene Id 4 to its internal vector id 1
}
This mapping is used during exact search to retrieve the correct FAISS vector for a given Lucene doc ID.
This mapping is constructed at index loading time and introduces minimal overhead. For example, for 10 million vectors, it adds only a few seconds. Internally, we use `MonotonicIntegerSequenceEncoder` to store this mapping efficiently.

#### **Pros:**

1. **No Changes to File Format or Codec Layer**
     The underlying Lucene codec and file format structure remains **untouched**, which means:
    1. Lucene codec structure remains unchanged.
    2. No impact on serialization or storage formats.

#### Cons:

1. A bi-directional mapping between Lucene Doc ID and the internal vector ID needs to be established.
    1. This table construction will be happening during loading time, so this will likely impact loading time.
2. **Limited GPU Index Optimization Flexibility:** This approach may limit scenarios where smaller `.faiss` files are preferred for GPU offloading and caching strategies.
    1. But it can also be solved with the below mentioned solution:
        1. [HNSW Cagra Graph and Flat Vectors Merging With O(1) Memory](https://quip-amazon.com/0ZYKAh4DQgKf)

### 6.7.3. Backward Compatibility

This solution is fully backward compatible and can be released as a **minor version update**. It only changes how flat vectors are written during flush and merge, without altering the final index structure. The output remains a standard **FAISS index** stored in the `.faiss` file, fully compatible with the k-NN plugin. While the `.vec` file is no longer populated with vectors, it is still created by the Lucene codec, ensuring compatibility with existing components. No changes are required in serialization, loading, or query paths.

* * *

# Appendix 1. SIMD FP16 to FP32 Conversion

**Code to implement SIMD in X86 machine:**

```
#include <immintrin.h>
#include <iostream>
#include <iomanip>
#include <cstdint>


float original_fp32_vector[768] = {float vector values......};

int main() {
    constexpr int DIM = 768;
    alignas(64) float fp32_input[DIM];
    alignas(64) uint16_t fp16_buffer[DIM];
    alignas(64) float fp32_output[DIM];

    // Copy from your original vector
    for (int i = 0; i < DIM; ++i) {
        fp32_input[i] = original_fp32_vector[i];
    }

    // FP32 → FP16
    for (int i = 0; i < DIM; i += 16) {
        __m512 fp32_vals = _mm512_load_ps(&fp32_input[i]);
        __m256i fp16_vals = _mm512_cvtps_ph(fp32_vals, _MM_FROUND_TO_NEAREST_INT | _MM_FROUND_NO_EXC);
        _mm256_store_si256((__m256i*)&fp16_buffer[i], fp16_vals);
    }

    // FP16 → FP32
    for (int i = 0; i < DIM; i += 16) {
        __m256i fp16_vals = _mm256_load_si256((__m256i*)&fp16_buffer[i]);
        __m512 fp32_vals = _mm512_cvtph_ps(fp16_vals);
        _mm512_store_ps(&fp32_output[i], fp32_vals);
    }

    std::cout << std::endl;

    return 0;
}
```

**Code to implement SIMD in ARM machine:**

```
#include <arm_neon.h>
#include <iostream>
#include <iomanip>
#include <cstdint>

constexpr int DIM = 768;
alignas(16) float original_fp32_vector[DIM] = {float vector values......};

int main() {
    alignas(16) float32_t fp32_input[DIM];
    alignas(16) float16_t fp16_buffer[DIM]; 
    alignas(16) float32_t fp32_output[DIM];

    for (int i = 0; i < DIM; i++) {
        fp32_input[i] = original_fp32_vector[i];
    }

    // FP32 → FP16 conversion using NEON
    for (int i = 0; i < DIM; i += 8) {
        float32x4_t low = vld1q_f32(&fp32_input[i]);
        float32x4_t high = vld1q_f32(&fp32_input[i + 4]);
        float16x4_t low16 = vcvt_f16_f32(low);
        float16x4_t high16 = vcvt_f16_f32(high);
        vst1_f16(&fp16_buffer[i], low16);
        vst1_f16(&fp16_buffer[i + 4], high16);
    }

    // FP16 → FP32 conversion using NEON
    for (int i = 0; i < DIM; i += 8) {
        float16x4_t low16 = vld1_f16(&fp16_buffer[i]);
        float16x4_t high16 = vld1_f16(&fp16_buffer[i + 4]);
        float32x4_t low32 = vcvt_f32_f16(low16);
        float32x4_t high32 = vcvt_f32_f16(high16);
        vst1q_f32(&fp32_output[i], low32);
        vst1q_f32(&fp32_output[i + 4], high32);
    }

    std::cout << std::endl;
    return 0;
}
```

**JAVA Code for conversion:** 
**File name Float.java**

```
//
// From JDK
//
public static float float16ToFloat(short floatBinary16) {
        /*
         * The binary16 format has 1 sign bit, 5 exponent bits, and 10
         * significand bits. The exponent bias is 15.
         */
        int bin16arg = (int)floatBinary16;
        int bin16SignBit     = 0x8000 & bin16arg;
        int bin16ExpBits     = 0x7c00 & bin16arg;
        int bin16SignifBits  = 0x03FF & bin16arg;

        // Shift left difference in the number of significand bits in
        // the float and binary16 formats
        final int SIGNIF_SHIFT = (FloatConsts.SIGNIFICAND_WIDTH - 11);

        float sign = (bin16SignBit != 0) ? -1.0f : 1.0f;

        // Extract binary16 exponent, remove its bias, add in the bias
        // of a float exponent and shift to correct bit location
        // (significand width includes the implicit bit so shift one
        // less).
        int bin16Exp = (bin16ExpBits >> 10) - 15;
        if (bin16Exp == -15) {
            // For subnormal binary16 values and 0, the numerical
            // value is 2^24 * the significand as an integer (no
            // implicit bit).
            return sign * (0x1p-24f * bin16SignifBits);
        } else if (bin16Exp == 16) {
            return (bin16SignifBits == 0) ?
                sign * Float.POSITIVE_INFINITY :
                Float.intBitsToFloat((bin16SignBit << 16) |
                                     0x7f80_0000 |
                                     // Preserve NaN signif bits
                                     ( bin16SignifBits << SIGNIF_SHIFT ));
        }

        assert -15 < bin16Exp  && bin16Exp < 16;

        int floatExpBits = (bin16Exp + FloatConsts.EXP_BIAS)
            << (FloatConsts.SIGNIFICAND_WIDTH - 1);

        // Compute and combine result sign, exponent, and significand bits.
        return Float.intBitsToFloat((bin16SignBit << 16) |
                                    floatExpBits |
                                    (bin16SignifBits << SIGNIF_SHIFT));
    }
```

### LINKED ISSUE #2823: [FEATURE] Dedup Vectors to Optimize Space
# Deduplicating Flat Vectors

## **1. Abstract**

This document presents two solutions for deduplicating full-precision vectors in a FAISS index within OpenSearch. Currently, flat vectors are stored in both `.vec` and `.faiss` files, resulting in redundant data and increased resource usage.
With this optimization, the index size was reduced from 45 GB to 16 GB for FP16, from 59 GB to 32 GB for FP32 (FYI, Lucene has 30GB), 64% improvement. This deduplication also led to a 22% reduction in indexing throttle time (from 350 min to 272 min) and a 66% drop in total merge byte size (from 79.61 GB to 27.02 GB). Additionally, merge throttling time decreased by 66%, going from 33 min to 11 min. Memory efficiency also improved significantly, with JVM (off-heap) buffer memory dropping from 59.95 GB to 32.43 GB, 45% reduction.

The document starts with the problem statement, outlines benchmarking results, and provides a focused comparison of the two solutions, highlighting their implementation details, advantages, and trade-offs.

## **2. Scope**

The proposed solutions apply specifically to **FAISS HNSW indexing** and are **not applicable to IVF**.
This optimization targets cases where vectors are of type FP32, FP16, Byte and Pure Binary(case where user ingest already quantized bytes). 

## **3. Background**

OpenSearch’s k-NN plugin uses **FAISS with HNSW** for ANN(Approximate Nearest Neighbor Search) search. The figure below shows how vectors are currently indexed and stored in the system.

### **3.1. How We Are Storing Vectors**

When users send documents to OpenSearch, they are first temporarily buffered (Lucene’s [DocumentsWriterPerThread](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java)) then flushed into storage via [IndexOutput](https://lucene.apache.org/core/10_0_0/core/org/apache/lucene/store/IndexOutput.html).
For each document, the [NativeEngines990KnnVectorsWriter::addField](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L76) method is called for every vector-type field, and these fields are added to the buffer ([Lucene99FlatVectorsWriter::addValue](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99FlatVectorsWriter.java#L455)). Once flushing is triggered,
[NativeEngines990KnnVectorsWriter::flush()](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L93) method iterates all buffered vectors and begins writing data to disk.

During flushing:

* An [NativeIndexWriter](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/nativeindex/NativeIndexWriter.java) requests a vector writer to handle vector storage.
* Based on the engine configuration (Native or Lucene), `[PerFieldKNNVectorFormat](https://github.com/opensearch-project/k-NN/blob/ee3f2625efea27d410219b939f4ff66ed5b9ce98/src/main/java/org/opensearch/knn/index/codec/BasePerFieldKnnVectorsFormat.java#L156)` returns the appropriate writer.
* This writer writes vector data into a **new segment** on storage, creating two files:
    * `.vec` — stores flat vectors
    * `.faiss` — stores the HNSW graph and also vectors (if quantization is not used, flat vectors will have full precision vectors to be stored again, causing **duplication between `.vec`**)

This describes how vectors are stored during the **flush** process, one segment at a time.

### **3.2 How We Are Doing Exact Search**

For exact search, the current implementation retrieves relevant vectors based on the search query and then performs comparisons using a distance function (e.g., L2 or cosine) to compute similarity scores.
For the details, refer to [here](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/ExactSearcher.java#L65).

### **3.3 How We Are Doing Merge**

During merging, OpenSearch combines multiple segments, each of which typically contains its own `.vec` and `.faiss` files.
By default, both flat vectors and HNSW graphs are written during indexing and merge. However, this behavior can be controlled using the setting: [index.knn.advanced.approximate_threshold](https://docs.opensearch.org/docs/latest/vector-search/performance-tuning-indexing/)

* If this is set to `-1`, **.faiss file creation is skipped during indexing**, and only the `.vec` file is written with flat vectors.
* During merge, vectors are read from the `.vec` file only.
* It's important to change this setting to `0` **before triggering a force merge**. Otherwise, users would need to **reindex** their data.

In the `[mergeOneField()](https://github.com/opensearch-project/k-NN/blob/b62528c05630d42f26984e16ed53d16d420754e7/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L136)` method:

* Vectors from all source segments are read and written into a new merged segment:
    * A new `.vec` file with flat vectors.
    * A new `.faiss` file with vectors and the HNSW graph (if not skipped by the setting).

**Both flush and merge store the same flat vectors twice(FP32, Byte and Pure Binary Cases),** once in `.vec`, and again in `.faiss`, leading to significant **storage duplication**. Eliminating this redundancy is the main motivation for the optimization discussed in this document.
* * *

## **4. Problem Statement**

For FP32, Byte, and Pure Binary cases, maintaining **two copies of the same vectors** in both `.vec` and `.faiss` files is redundant. Both approximate and exact search operations can run on a **single set of vectors**, making it possible to eliminate this duplication safely. 
For FP16, the `.vec` file stores full-precision vectors, while the `.faiss` file stores a scalar-quantized FP16 representation.

### **Key issues in the current flow:**

1. **Redundant Storage**
     Flat vectors are stored in both `.vec` and `.faiss` files, effectively doubling storage for each segment.
2. **Increased Merge Overhead**
     During segment merges, duplicated vectors are read and re-written, leading to unnecessary compute and I/O costs.
    1. By removing redundancy, the system writes fewer bytes to disk and reads less data during segment consolidation. This not only reduces the overall I/O load but also makes merge operations significantly faster and more efficient.
    2. This optimization significantly reduces I/O amplification caused by default merge policy [TieredMergePolicy](https://lucene.apache.org/core/10_0_0/core/org/apache/lucene/index/TieredMergePolicy.html) — since vectors are no longer stored twice, the total I/O volume during merges drops considerably. In practice, this has shown over **66% reduction in total merge bytes**, leading to **more than 50% decrease in I/O cost**, faster merges, and improved system throughput.
3. **Higher Operational Cost**
     Larger index sizes increase disk and memory usage, resulting in higher infrastructure costs for OpenSearch users. 
4. **Reduced MMap Overhead:** 

When vector files are memory-mapped, the operating system loads them into memory using the mmap mechanism.
(Note that we are using [MMapDirectory](https://lucene.apache.org/core/10_0_0/core/org/apache/lucene/store/MMapDirectory.html) by default)
 Large or redundant files increase pressure on the **kernel’s virtual memory system**, leading to higher **page cache usage** and potential eviction of other useful data.
By eliminating duplicate vector data, this optimization **reduces the size of memory-mapped files**, lowering:

    1. Kernel memory pressure
    2. Page faults
    3. And overall resident memory usage

# 5. Performance Results

To validate the effectiveness of the vector deduplication optimization, we measured its impact under two conditions: **pure indexing workload** and a **stress scenario involving indexing + search under constrained memory**.

## 5.2. Pure Indexing Performance (Indexing Only, No Search)

Under a standard indexing workload, we observed substantial improvements across key metrics after applying the optimization:

* **Merge I/O Reduction
    **The `merges.total_size_in_bytes` decreased from **79.61 GB** to **27.02 GB**, a **66% reduction**, highlighting that duplicate vectors were eliminated from merge operations.
* **Merge Throttling Time**
     The `merges.total_throttled_time_in_millis` also saw a **66% reduction**, dropping from **1,990,087 ms** to **669,256 ms**, showing merge phases completed more efficiently.
* **JVM Direct Memory Pressure**
     Off-heap memory usage under `jvm.buffer_pools` reduced from **59.95 GB** to **32.43 GB**, reflecting a **45% improvement** in memory footprint due to smaller segment sizes.
* **Indexing Throttling Time**
     The `indexing.throttle_time_in_millis` dropped by **22%**, decreasing from **21,046,833 ms** in the baseline to **16,321,000 ms**, indicating lower back pressure during document ingestion.

#### Indexing & Merging Breakdown

* **Flush Phase**
     While flush operations benefit from smaller vector data, the improvement is moderate — around **22%** less throttling time, suggesting having `.vec` included in flush is less sensitive to vector duplication.
* **Merge Phase**
     This is where the optimization shows the greatest value:
    * Merge duration improved by **18.14%**, from **381.22 minutes** down to **312.05 minutes**.
    * Merge throttling saw a dramatic **73% reduction**, from **8.72 minutes** to **2.33 minutes**.

**Additional Benefit:** 
**Faster Remote Recovery, Replication:**  Because the segment size is nearly halved, remote recovery or replication operations are expected to complete roughly twice as fast.

## 5.3. Indexing + Search Under Memory Pressure

To test the robustness and efficiency of the deduplication optimization under stress, we simulated an environment where indexing and search operations run concurrently in a memory-constrained setting. The benchmark was run with a query-per-second (QPS) of 1, ensuring that all segments remain loaded during indexing. This setup is designed to evaluate the system’s behavior and limits from a memory pressure perspective.
The results indicate that the optimization significantly improves system stability, reduces memory overhead, and enables more efficient handling of concurrent indexing and search workloads.

**Key Observations:**

* **High CPU I/O Wait in Baseline**
    * The baseline setup exhibited significantly higher **CPU I/O wait time**, indicating the system was frequently stalled waiting on disk I/O. This behavior was mitigated in the optimized approach, reflecting reduced disk operations due to smaller segment files and the removal of duplicated vector writes.
    * 
* **Search Latency**
    * Search latency under concurrent indexing showed 20–30% improvement with the optimized approach. Reduced memory and disk pressure contributed to faster access to vector data during query execution. At extreme memory pressure, the performance gap widens up to 300%
    * 
* Page Faults
    * A sharp drop in page faults was observed: 
        * **Baseline**: 14.33 million
        * **Optimized**: 3.13 million
    * A **78.15% reduction**, highlighting better memory locality and fewer interruptions due to paging.
* #Segments and Merge Behavior
    * Due to smaller segment sizes in the optimized approach, the system can **merge more segments together** during force merges. This leads to Fewer total segments.
    * This aligns well with **Lucene’s Tiered merge policy**, which operates on a fixed I/O budget and merges similar-sized segments into intermediate layers before combining them further
        * Ref - https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/TieredMergePolicy.java#L30-L68
    * 
* System Stability During Merge
    * In the baseline case, the server **crashed during segment merging**, primarily due to large segment sizes and memory exhaustion. Since we are constantly sending query, this keeps all segments alive in memory.
         In contrast, with the optimized solution, **merges completed without failure**, due to smaller segments that required less memory and I/O.
         This demonstrates that the optimization **increased operational limits**, allowing the system to handle larger workloads more reliably.
    * 

A benchmarking table below provides a comparison between the current (base) implementation and the optimized version.

**Base Code Results V/S Optimized Approach Results**

|	|Base Code	|Optimized Approach	|Improvement	|
|---	|---	|---	|---	|
|Disk Usage (GB)	|45GB	|16GB	|~64%↓	|
|disk_used_percent	|42.7333	|22.40333	|~48%↓	|
|diskio_writes	|50,164	|42,598.66667	|~15%↓	|
|diskio_write_bytes	|3.07G	|1.82G	|~40%↓	|
|diskio_reads	|167,339.66667	|61,301	|~63%↓	|
|diskio_read_bytes	|7.54G	|6.99G	|~7%↓	|
|	|	|	|	|
|Ingestion Throughput (docd/sec)	|	|	|	|
|Min Throughput	|1045.04333	|917.57667	|~12%↓	|
|Mean Throughput	|1967.04333	|1707.79667	|~13%↓	|
|Median Throughput	|1620.61	|1226.59	|~24%↓	|
|Max Throughput	|9657.77	|9588.83667	|~0.7%↓	|
|	|	|	|	|
|Ingestion Latency	|	|	|	|
|50th percentile latency	|118.95343	|122.34855	|~0.2%↑	|
|90th percentile latency	|213.79453	|192.81594	|~0.9↓	|
|99th percentile latency	|426.58207	|364.79083	|~14%↓	|
|99.9th percentile latency	|222769.59853	|330550.76061	|~48%↑	|
|99.99th percentile latency	|1016394.44591	|817674.40804	|~19%↓	|
|100th percentile latency	|2241311.66279	|1302300.90822	|~41%↓	|
|	|	|	|	|
|	|	|	|	|
|Mean recall@k	|0.95	|0.95	|	|
|Mean recall@1	|0.97667	|0.97667	|	|

* * *

# **6. Solution Proposed**

## 6.1. How we are loading vectors in recommended approach?

For vector loading we are making use of Lucene’s FlatVectorReader which in turn uses IndexInput. 
For reference: **[Loading logic](https://quip-amazon.com/6L0dAH0CasTc/POC-Deduplicating-Flat-Vectors#temp:C:YQQdca394027b474d17ae1ac9529)**

## 6.2. Ongoing SIMD Project — Manasvi

**What is SIMD?**
**SIMD (Single Instruction, Multiple Data)** is a type of parallel computing architecture where a single CPU instruction is applied to multiple data elements simultaneously. It leverages **wide vector registers** (128-bit, 256-bit, or 512-bit) to process multiple values in one operation.

**How We Use SIMD in Our Project?**
In our project, we work with vectors data that we want to store in half-precision (FP16) format to save memory and I/O bandwidth. 
To optimize this process, we use SIMD instructions to accelerate the conversion:

* **x86 (Intel AVX-512)**: We use `_mm512_cvtph_ps` to convert 16 FP16 values to FP32 in a single instruction. 
    * [Code ref. X86](https://quip-amazon.com/6L0dAH0CasTc/POC-Deduplicating-Flat-Vectors#temp:C:YQQd945cdefaa0a4777aa15d83d9)
* **ARM (NEON with FP16 support)**: We use `vcvt_f32_f16` to perform 4-wide FP16 to FP32 conversion on Graviton-based EC2 instances. 
    * [Code ref. ARM](https://quip-amazon.com/6L0dAH0CasTc/POC-Deduplicating-Flat-Vectors#temp:C:YQQd6e62e24142f49a9ac4ee573e)

This allows us to process entire vectors in chunks rather than converting each float individually in a loop.

**How we embed this SIMD logic in deduplicating vectors project?**
To support FP16, we plan to store FP16 vectors in the `.vec` file, this is made possible by using the second part of **Manasvi’s** project. In her implementation, she is developing a custom reader/writer that can write FP32 vectors to the `.vec` file as FP16 byte representations and read FP16 bytes from the `.vec` file while converting them back to FP32.
By reusing her project’s custom reader/writer and conversion logic, our project can seamlessly handle FP16 storage and retrieval without implementing separate conversion logic, ensuring reducing overhead.
[Lucene99FlatVectorsReader](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99FlatVectorsReader.java)
[Lucene99FlatVectorsWriter](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/codecs/lucene99/Lucene99FlatVectorsWriter.java)

## **6.3. Solutions Overview**

We propose two solutions.

#### **[Recommended] Approach 1: Remove Flat Vectors from the `.faiss` File and Save FP16 in `.vec` file**

In this approach, we eliminate the flat vector section from the `.faiss` file and continue storing all flat vectors, including FP16 in the `.vec` file. At index load time, vectors are retrieved from the `.vec` file into the JVM heap and subsequently passed to native C++ memory. To support storing FP16 vectors in the `.vec` file, we are going to use Manasvi’s implementation, which introduces a new datatype for FP16 vectors. This will make `.vec` file the single source of flat vector data. This solution reduces the storage significantly(~64 %) and the reduced size of `.faiss` file will also help in simplifying the GPU pipeline.
Experimental benchmarking demonstrates **major storage savings**:

1. Base implementation: ~45 GB.
2. Optimized approach: ~16 GB. This shows we can **approximately reduce disk usage by 64%**, which in turn improves **cost efficiency** and **disk I/O performance.**

#### **[Alternative] Approach 2: Remove Flat** **Vectors** **from the `.vec` File**

In this approach, we stop writing flat vectors to the `.vec` file during both flush and merge phases. Instead, vector data is stored and retrieved **exclusively from the `.faiss` file**. (Assuming the  `index.knn.advanced.approximate_threshold` setting is not set to `-1`. More details on this setting and its impact are discussed in the section — [Note: If the user sets index.knn.advanced.approximate_threshold = -1, .faiss file construction is explicitly skipped. In such cases, the system must…](https://quip-amazon.com/6L0dAH0CasTc#temp:C:YQQ74a836c773344483ae47670eb))
This eliminates dependency on `.vec`, reduces index size, and simplifies the indexing flow by using **just one file** (`.faiss` file), to store all vector information.

## **6.4. Conversion Overhead Status for FP16 With SIMD**

Regardless of the approach, FP16 introduces conversion cost, but with SIMD, the impact is negligible.

### Faiss C++

|	|Recommended Approach With SIMD	|Alternative Approach With SIMD	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in ANN search	|No Issue	|No Issue	|
|Conversion overhead (FP16 → FP32) in merge	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Conversion overhead in exact search	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

### LuceneOnFaiss

|	|Recommended Approach With SIMD	|Alternative Approach With SIMD	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in search	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Conversion overhead (FP16 → FP32) in merge	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Conversion overhead in exact search	|No latency lost with SIMD, but there would be conversion cost	|No latency lost with SIMD, but there would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

## **6.5. Conversion Overhead Status for FP16 Without SIMD**

Regardless of which approach we take, FP16 introduces conversion cost, but with SIMD, the impact is negligible.
We have to use Float.float16ToFloat in Java 
And saying that due to the conversion cost, we will likely see 2-3x slower performance in derived source + exact search.
[JAVA Code for conversion:](https://quip-amazon.com/6L0dAH0CasTc#temp:C:YQQ7cad450b2b3b4572836542119)

### Faiss C++

|	|Recommended Approach	|Alternative Approach	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in ANN search	|No Issue	|No Issue	|
|Conversion overhead (FP16 → FP32) in merge	|There would be conversion cost	|There would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|There would be conversion cost	|There would be conversion cost	|
|Conversion overhead in exact search	|There would be conversion cost	|There would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

### LuceneOnFaiss

|	|Recommended Approach	|Alternative Approach	|
|---	|---	|---	|
|Conversion overhead (FP16 → FP32) in search	|There would be conversion cost	|There would be conversion cost	|
|Conversion overhead (FP16 → FP32) in merge	|There would be conversion cost	|There would be conversion cost	|
|Any additional overheads in flush	|No Issue	|No Issue	|
|Conversion overhead in derived source	|There would be conversion cost	|There would be conversion cost	|
|Conversion overhead in exact search	|There would be conversion cost	|There would be conversion cost	|
|Any overhead during loading index	|No Issue	|No Issue	|
|	|	|	|

### **6.6.1. Implementation Methodology**

This approach removes flat vectors from the `.faiss` file and relies entirely on the .`vec` file for vector storage. Below is a detailed breakdown of how this works during flush, merge, and search.

**For conversion overhead: We are going to use SIMD optimization(FP16 to FP32).**

* We are already making use of SIMD on FAISS side of the code. 
    * [ScalerQuantizer.cpp](https://github.com/facebookresearch/faiss/blob/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64/faiss/impl/ScalarQuantizer.cpp)

#### **6.6.1.1. `flush()` Logic – Skip Flat Vector Section in `.faiss` File**

In this approach, the flush flow largely mirrors the default indexing behavior, with one key difference:

* Flat vectors are still written to the **`.vec` file** as usual.
* When the `.faiss` index is created, the C++ layer **skips writing the flat vector section**.

```
void write_index(const Index* idx, IOWriter* f, int io_flags) {
    if (...) {
        
    } else if (const IndexFlat* idxf = dynamic_cast<const IndexFlat*>(idx)) {
        uint32_t h =
                fourcc(idxf->metric_type == METRIC_INNER_PRODUCT ? "IxFI"
                               : idxf->metric_type == METRIC_L2  ? "IxF2"
                                                                 : "IxFl");
        WRITE1(h);
        write_index_header(idx, f);
        
        commenting this line will stop writing flat vectors to .faiss file
        // WRITEXBVECTOR(idxf->codes);
    } else if (...) {
       ...
    }
    ...
    ...
 }
```

 [index_write.cpp](https://github.com/facebookresearch/faiss/blob/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64/faiss/impl/index_write.cpp#L403)

* The logic is modified to exclude the flat vector data while writing the index in `.faiss` file.
* **This creates a segment having both `.faiss` and `.vec` files**, but avoids duplication of vector storage between the two.

As a result:

* The `.faiss` file contains the **HNSW graph** and the associated **ID mapping** (linking internal FAISS vector IDs to Lucene doc IDs).
* The `.vec` file contains full-precision flat vectors and, with the new implementation, can also store FP16 vectors.
* This creates a segment with both `.faiss` and `.vec` files, but avoids duplication of vector storage between the two files.

#### **6.6.1.2. Loading logic – Read from `.vec` File in Faiss C++**

In the loading path (e.g. search, warm up), we implement support to construct the FAISS index by reading vectors from `.vec` via the Java-side `VectorReader(new implementation)`.
Vectors are read from the `IndexInput` on the Java side, then passed into C++ off-heap memory through JNI for FAISS to build the index. This enables FAISS to construct HNSW graphs even though the `.faiss` file initially did not contain vector data.

Key Changes: To read flat vectors directly from IndexInput, we modified the FAISS-native I/O pipeline to bridge Java and C++. 

C++ Side:

* **We have `[FaissOpenSearchIOReader](https://github.com/opensearch-project/k-NN/blob/ee3f2625efea27d410219b939f4ff66ed5b9ce98/jni/include/faiss_stream_support.h#L34)`**, which **inherits from `[faiss::IOReader](https://github.com/facebookresearch/faiss/blob/0cbc2a885cde923d80c4bf9c9d6f4d81665f3f64/faiss/impl/io.h#L27)`**.
* We **introduced a new virtual method `copy()` in the base `IOReader` interface**, allowing custom vector loading behavior.
* `FaissOpenSearchIOReader` **overrides `copy()`**, and inside this method:
    * JNI is used to **call Java's `VectorReader.next()`** method.
    * One vector is fetched from the Java side per call and passed to FAISS in-memory for index construction.

#### **Java Side:**

* A new class **`VectorReader`** wraps `FloatVectorValues` for a Lucene segment.
* Inside `VectorReader`, we expose a **`next()` method**, which:
    * Calls `iterator.nextDoc()` to advance to the next document and get its **doc ID**.
    * Uses that doc ID to fetch the vector via `floatVectorValues.vectorValue(docId)`.
    * Returns the resulting `float[]` vector.

####  Flow:

* Instead of reading flat vectors from `.faiss`, FAISS internally requests vectors via the `IOReader::copy()` method.
* This calls into the Java `VectorReader.next()` and pulls data from the `.vec` file.

[index_read.cpp](https://github.com/facebookresearch/faiss/blob/dd0d40b57e617ac4b3e165c5e6739d19cca55eff/faiss/impl/index_read.cpp#L684)

Java Code Snippet:

```
public class VectorReader {
    private final FloatVectorValues floatVectorValues;
    private final DocIndexIterator iterator;

    public VectorReader(FloatVectorValues floatVectorValues) {
        ...
        ...
    }
    
`    // This will allow the copy method in the C++ side to read vectors`
    public float[] next() throws IOException {
        int docId = iterator.nextDoc();
        if (docId != DocIndexIterator.NO_MORE_DOCS) {
            return floatVectorValues.vectorValue(docId);
        } else {
            return null;
        }
    }
}
```

C++ Code Snippet:

```
class FaissOpenSearchIOReader final : public faiss::IOReader {
public:
    explicit FaissOpenSearchIOReader(NativeEngineIndexInputMediator* _mediator)
        ... // constructor things
    }

    // We overrides the copy() method of io.h and used it to get vectors from Java side VectorReader.
    bool copy(void* dest, int expectedByteSize) final{
        JNIEnv* env = cachedEnv;

        // Get float[] from JVM
        jfloatArray vector = (jfloatArray) env->CallObjectMethod(vectorReaderGlobalRef, nextMid);

        if (env->ExceptionCheck() || vector == nullptr) {
            return false;
        }

        // Prepare copy
        jsize length = env->GetArrayLength(vector);
        jfloat* elems = env->GetFloatArrayElements(vector, nullptr);

        JNIReleaseElements release_elems([=]() {
            env->ReleaseFloatArrayElements(vector, elems, JNI_ABORT);
        });

        int vectorByteSize = sizeof(float) * length;
        if (vectorByteSize != expectedByteSize) {
            return false;
        }

        // Copy Java float[] to C++ float[]
        std::memcpy(dest, elems, vectorByteSize);

        return true;
    }

};
```

#### **6.6.1.3. Exact Search** 

Exact search continues to follow the **default flow**. Codec layer will load flat vectors from the appropriate source and these vectors are then passed to the exact search component.

#### **6.6.1.5. Backward Compatibility**

There are no backward compatibility issues with this solution. It remains fully backward compatible, as it only modifies the way flat vectors are written during flush and merge operations. The `.vec` file continues to store all flat vectors, and now also includes FP16 vectors.
To support FP16 storage and retrieval, a custom reader and writer will be implemented. These components will handle all necessary conversions and ensure seamless integration without affecting existing functionality.

#### **Pros**

1. ****GPU Indexing Pipeline Optimization:****
     Removing flat vectors from the `.faiss` file results in a much smaller index file, which can:
    1. Speed up downloads in GPU-accelerated pipelines.
    2. Reduce network transfer time and storage costs, especially in distributed deployments.
    3. Additionally, with the proposed approach, the merge phase can be skipped entirely.
2. There is no need to create a bi-directional mapping table (Lucene’s Doc ID to Internal vector ID) as it’s already present in `.vec` file.
3. We reduce storage by 66% using FP16, and also get similar performance to FP32 when SIMD is used.

#### Cons:

1. Since we plan to use SIMD to mitigate the conversion overhead, users can benefit from reduced latency. However, older versions of CPU may not support SIMD, so users will need to migrate to a new instance having a modern chip to take advantage of this optimization.
    1. Without SIMD, latency increases by up to 3x
2. Since we now store FP16 in the `.vec` file, users might see a drop in recall when reindexing to a schema that expects FP32. However, this is a rare and edge case scenario.

### **6.7.1. Implementation Methodology**

This solution removes the dependency on `.vec` files by ensuring that flat vectors are written and read only through the `.faiss` index. This requires changes across three core components:

#### **6.7.1.1. `flush()` Logic – Remove `.vec` File Writing**

In the `flush()` method of `NativeEngines990KnnVectorsWriter`, the logic responsible for writing flat vectors to the `.vec` file is removed. Instead, only the `.faiss` index is built and flushed to disk.

* During flush, a new segment is created, but only the FAISS index is written.
* The `.vec` file is still created structurally, because the codec expects a `.vec` file to exist for compatibility and versioning purposes. However the `.vec` file remains nearly empty —
    **Before optimization**: ~28.8 GB per segment
    **After optimization**: ~630 B per segment (header only, no vector payload)

**Note:** If the user sets `index.knn.advanced.approximate_threshold = -1`, `.faiss` file construction is explicitly skipped. In such cases, the system must **spill flat vectors to the `.vec` file**, as no `.faiss` file is created.

```
public void flush(int maxDoc, finsl Sorter.DocMap sortMap){
    // We can comment this out, so that we don't store vectors in .vec file
    // flatVectorsWriter.flush(maxDoc, sortMap);
    for (final NativeEngineFieldVectorsWriter<?> field : fields) {
        final FieldInfo fieldInfo = field.getFieldInfo();
        final VectorDataType vectorDataType = extractVectorDataType(fieldInfo);
        int totalLiveDocs = field.getVectors().size();
        if (totalLiveDocs == 0) {
            ...
    ...
}
```

#### **6.7.1.2. `mergeOneField()` Logic – Read from `.faiss` File Only**

During segment merging:

* When HNSW graph construction is enabled, flat vectors are not read from `.vec` files.
    * Instead, an iterator extracts vectors directly from the `.faiss` file of each input segment.
* When graph construction is skipped (i.e., `index.knn.advanced.approximate_threshold = -1`), vectors are read from `.vec` files, since `.faiss` is not written.
* From an implementation perspective, we first attempt to get the `Iterator<float[]>` from the `.faiss` file. If this fails (e.g., due to the absence of `.faiss`), we gracefully fall back to loading vectors from the `.vec` file instead.

This change ensures that:

* In the default case only `.faiss` files are read and written during the merge.
* Duplicate storage of flat vectors is avoided.
* The merged segment ends up with:
    * A `.faiss` file containing both the HNSW graph and vectors.
    * A `.vec` file that is created structurally but has **no flat vector section**.

**Note:** When the user disables graph creation (`approximate_threshold = -1`), flat vectors are written to the `.vec` file, and `.faiss` file is skipped entirely.

```
public void mergeOneField(final FieldInfo fieldInfo, final MergeState mergeState) throws IOException {
    // This will ensure that we are not merging the Flat Vectors int .vec file.
    // flatVectorsWriter.mergeOneField(fieldInfo, mergeState);
           
       final VectorDataType vectorDataType = extractVectorDataType(fieldInfo);
       final Supplier<KNNVectorValues<?>> knnVectorValuesSupplier = getKNNVectorValuesSupplierForMerge(
       vectorDataType,
       fieldInfo,
       mergeState
       );
       int totalLiveDocs = getLiveDocs(knnVectorValuesSupplier.get());
       if (totalLiveDocs == 0) {
           log.debug("[Merge] No live docs for field {}", fieldInfo.getName());
           return;
       }
       ...
       ...
       ...
        
  }
```

#### **6.7.1.3. Exact Search – Use `.faiss` for Flat Vectors**

There are **no changes required** in the exact searcher. The codec layer is responsible for loading flat vectors from the appropriate source. These vectors are then passed to the exact search component transparently.

#### **6.7.1.4. Sparse Case Handling**

In sparse scenarios, **not every Lucene document contains a vector**. FAISS, in this case, stores vectors **only for documents that have them**. As a result, the internal FAISS vector IDs do not directly align with Lucene doc IDs.
To support exact search in such cases, a **reverse mapping** is required—from Lucene doc ID to FAISS vector ID.
Example:

* If only Lucene doc IDs 0 and 4 have vectors, FAISS will assign them vector IDs 0 and 1.
* A mapping must be maintained:

{
0 : 0,  → Mapping Lucene Id 0 to its internal vector id 0
4 : 1  → Mapping Lucene Id 4 to its internal vector id 1
}
This mapping is used during exact search to retrieve the correct FAISS vector for a given Lucene doc ID.
This mapping is constructed at index loading time and introduces minimal overhead. For example, for 10 million vectors, it adds only a few seconds. Internally, we use `MonotonicIntegerSequenceEncoder` to store this mapping efficiently.

#### **Pros:**

1. **No Changes to File Format or Codec Layer**
     The underlying Lucene codec and file format structure remains **untouched**, which means:
    1. Lucene codec structure remains unchanged.
    2. No impact on serialization or storage formats.

#### Cons:

1. A bi-directional mapping between Lucene Doc ID and the internal vector ID needs to be established.
    1. This table construction will be happening during loading time, so this will likely impact loading time.
2. **Limited GPU Index Optimization Flexibility:** This approach may limit scenarios where smaller `.faiss` files are preferred for GPU offloading and caching strategies.
    1. But it can also be solved with the below mentioned solution:
        1. [HNSW Cagra Graph and Flat Vectors Merging With O(1) Memory](https://quip-amazon.com/0ZYKAh4DQgKf)

### 6.7.3. Backward Compatibility

This solution is fully backward compatible and can be released as a **minor version update**. It only changes how flat vectors are written during flush and merge, without altering the final index structure. The output remains a standard **FAISS index** stored in the `.faiss` file, fully compatible with the k-NN plugin. While the `.vec` file is no longer populated with vectors, it is still created by the Lucene codec, ensuring compatibility with existing components. No changes are required in serialization, loading, or query paths.

* * *

# Appendix 1. SIMD FP16 to FP32 Conversion

**Code to implement SIMD in X86 machine:**

```
#include <immintrin.h>
#include <iostream>
#include <iomanip>
#include <cstdint>


float original_fp32_vector[768] = {float vector values......};

int main() {
    constexpr int DIM = 768;
    alignas(64) float fp32_input[DIM];
    alignas(64) uint16_t fp16_buffer[DIM];
    alignas(64) float fp32_output[DIM];

    // Copy from your original vector
    for (int i = 0; i < DIM; ++i) {
        fp32_input[i] = original_fp32_vector[i];
    }

    // FP32 → FP16
    for (int i = 0; i < DIM; i += 16) {
        __m512 fp32_vals = _mm512_load_ps(&fp32_input[i]);
        __m256i fp16_vals = _mm512_cvtps_ph(fp32_vals, _MM_FROUND_TO_NEAREST_INT | _MM_FROUND_NO_EXC);
        _mm256_store_si256((__m256i*)&fp16_buffer[i], fp16_vals);
    }

    // FP16 → FP32
    for (int i = 0; i < DIM; i += 16) {
        __m256i fp16_vals = _mm256_load_si256((__m256i*)&fp16_buffer[i]);
        __m512 fp32_vals = _mm512_cvtph_ps(fp16_vals);
        _mm512_store_ps(&fp32_output[i], fp32_vals);
    }

    std::cout << std::endl;

    return 0;
}
```

**Code to implement SIMD in ARM machine:**

```
#include <arm_neon.h>
#include <iostream>
#include <iomanip>
#include <cstdint>

constexpr int DIM = 768;
alignas(16) float original_fp32_vector[DIM] = {float vector values......};

int main() {
    alignas(16) float32_t fp32_input[DIM];
    alignas(16) float16_t fp16_buffer[DIM]; 
    alignas(16) float32_t fp32_output[DIM];

    for (int i = 0; i < DIM; i++) {
        fp32_input[i] = original_fp32_vector[i];
    }

    // FP32 → FP16 conversion using NEON
    for (int i = 0; i < DIM; i += 8) {
        float32x4_t low = vld1q_f32(&fp32_input[i]);
        float32x4_t high = vld1q_f32(&fp32_input[i + 4]);
        float16x4_t low16 = vcvt_f16_f32(low);
        float16x4_t high16 = vcvt_f16_f32(high);
        vst1_f16(&fp16_buffer[i], low16);
        vst1_f16(&fp16_buffer[i + 4], high16);
    }

    // FP16 → FP32 conversion using NEON
    for (int i = 0; i < DIM; i += 8) {
        float16x4_t low16 = vld1_f16(&fp16_buffer[i]);
        float16x4_t high16 = vld1_f16(&fp16_buffer[i + 4]);
        float32x4_t low32 = vcvt_f32_f16(low16);
        float32x4_t high32 = vcvt_f32_f16(high16);
        vst1q_f32(&fp32_output[i], low32);
        vst1q_f32(&fp32_output[i + 4], high32);
    }

    std::cout << std::endl;
    return 0;
}
```

**JAVA Code for conversion:** 
**File name Float.java**

```
//
// From JDK
//
public static float float16ToFloat(short floatBinary16) {
        /*
         * The binary16 format has 1 sign bit, 5 exponent bits, and 10
         * significand bits. The exponent bias is 15.
         */
        int bin16arg = (int)floatBinary16;
        int bin16SignBit     = 0x8000 & bin16arg;
        int bin16ExpBits     = 0x7c00 & bin16arg;
        int bin16SignifBits  = 0x03FF & bin16arg;

        // Shift left difference in the number of significand bits in
        // the float and binary16 formats
        final int SIGNIF_SHIFT = (FloatConsts.SIGNIFICAND_WIDTH - 11);

        float sign = (bin16SignBit != 0) ? -1.0f : 1.0f;

        // Extract binary16 exponent, remove its bias, add in the bias
        // of a float exponent and shift to correct bit location
        // (significand width includes the implicit bit so shift one
        // less).
        int bin16Exp = (bin16ExpBits >> 10) - 15;
        if (bin16Exp == -15) {
            // For subnormal binary16 values and 0, the numerical
            // value is 2^24 * the significand as an integer (no
            // implicit bit).
            return sign * (0x1p-24f * bin16SignifBits);
        } else if (bin16Exp == 16) {
            return (bin16SignifBits == 0) ?
                sign * Float.POSITIVE_INFINITY :
                Float.intBitsToFloat((bin16SignBit << 16) |
                                     0x7f80_0000 |
                                     // Preserve NaN signif bits
                                     ( bin16SignifBits << SIGNIF_SHIFT ));
        }

        assert -15 < bin16Exp  && bin16Exp < 16;

        int floatExpBits = (bin16Exp + FloatConsts.EXP_BIAS)
            << (FloatConsts.SIGNIFICAND_WIDTH - 1);

        // Compute and combine result sign, exponent, and significand bits.
        return Float.intBitsToFloat((bin16SignBit << 16) |
                                    floatExpBits |
                                    (bin16SignifBits << SIGNIF_SHIFT));
    }
```

### PR DESCRIPTION
**Pull request by sobhu17**
### Description
This is the first PR which introduces Java-side support to expose FloatVectorValues via VectorReader, enabling FAISS to access flat vectors through JNI and also incliudes LuceneOnFaiss changes.
Currently we store vectors in two files (.vec and .faiss). The two vector sets stored in each file may differ where Faiss index file (.faiss) might contains quantized vectors for fast approximate search, while the Lucene .vec file  stores the full-precision vectors used during exact search.
For FP32, Byte, and Pure Binary cases, maintaining two copies of the same vectors in both .vec and .faiss files is redundant. Both approximate and exact search operations can run on a single set of vectors, making it possible to eliminate this duplication safely. 

In the next PRs I will-  
- add native integration to read float vectors from the JVM using the new VectorReader, removing the need to write flat vectors to .faiss.
- include bumping up FAISS version.

### Related Issues
Resolves #2823

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java [hunk 1]
```diff
@@ -192,6 +193,9 @@ protected NativeMemoryAllocation loadGraph(
         final String modelId,
         LeafReaderContext context
     ) throws ExecutionException, IOException {
+        KnnVectorValues knnVectorValues = (vectorDataType == VectorDataType.BYTE)
+            ? context.reader().getByteVectorValues(knnQuery.getField())
+            : context.reader().getFloatVectorValues(knnQuery.getField());
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java]: All the places where you are using Lucene KNNVectorValues please use our own vector values: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValues.java and this factory class to create the vector values: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/vectorvalues/KNNVectorValuesFactory.java

Not sure why we are using Lucene abstraction because we built our own abstraction for a reason to simplify the integration

File: src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+import lombok.Getter;
+import org.apache.lucene.codecs.hnsw.FlatVectorsReader;
+
+public class FlatVectorsReaderWithFieldName {
+
+    @Getter
+    private final FlatVectorsReader flatVectorsReader;
+    @Getter
+    private final String field;
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java:16]: Please provide explanation why we need this `field`?

File: src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java (hunk 1 above)
Comment (sobhu17) [reply src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java]: Got it,
 I will make this change.

Comment (sobhu17) [reply src/main/java/org/opensearch/knn/index/query/DefaultKNNWeight.java]: Hey @navneet1v, I added the KNNVectorValues implementation, Could you please take a look to the new changes?

File: src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java (hunk 2 above)
Comment (sobhu17) [reply src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java:16]: Hey @navneet1v, in order to get FloatVectorValues/ByteVectorValues from FlatVectorReader we need field name and we are using this field in FaissIndexFloatFlat.java and FaissIndexScalarQuantizedFlat.java. 
[src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexFloatFlat.java](https://github.com/opensearch-project/k-NN/pull/2835/files#diff-6a46047cd7f3b2fe4109cc32d00509c14e1dac0fcf7d149909bebe0bb49c5e8eR91-R94)

So, to make it easy to get everything at one place we are setting up these values in here:
[src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java](https://github.com/opensearch-project/k-NN/pull/2835/files#diff-e8c0b3983b0fd2edc56cabf9fbb439ea56eaa8917e7bff5713a30ee5e2a4e69cR366-R369)

File: src/main/java/org/opensearch/knn/index/KNNIndexShard.java [hunk 3]
```diff
@@ -9,12 +9,7 @@
 import lombok.AllArgsConstructor;
 import lombok.Getter;
 import lombok.extern.log4j.Log4j2;
-import org.apache.lucene.index.FieldInfo;
-import org.apache.lucene.index.LeafReader;
-import org.apache.lucene.index.LeafReaderContext;
-import org.apache.lucene.index.SegmentCommitInfo;
-import org.apache.lucene.index.SegmentInfo;
-import org.apache.lucene.index.SegmentReader;
+import org.apache.lucene.index.*;
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/KNNIndexShard.java]: avoid wildcard imports

File: src/main/java/org/opensearch/knn/index/store/VectorReader.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+package org.opensearch.knn.index.store;
+
+import org.opensearch.knn.index.vectorvalues.KNNByteVectorValues;
+import org.opensearch.knn.index.vectorvalues.KNNFloatVectorValues;
+import org.opensearch.knn.index.vectorvalues.KNNVectorValues;
+
+import java.io.IOException;
+
+public class VectorReader {
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/store/VectorReader.java:16]: Can we not use vector values directly for this one?

File: src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java [hunk 5]
```diff
@@ -49,20 +50,21 @@ public FaissIndex(final String indexType) {
...
+    protected abstract void doLoad(IndexInput input, FlatVectorsReaderWithFieldName flatVectorsReaderWithFieldName) throws IOException;
 
-    protected void readCommonHeader(IndexInput readStream) throws IOException {
+    protected boolean readCommonHeader(IndexInput readStream) throws IOException {
         dimension = readStream.readInt();
         totalNumberOfVectors = Math.toIntExact(readStream.readLong());
         // consume 2 dummy deprecated fields.
-        readStream.readLong();
+        final long dedupCheck = readStream.readLong();
+        final boolean dedupApplied = dedupCheck == 0xFFFFFFF;
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java]: move 0xFFFFFFF to static variable at top

Comment (sobhu17) [reply src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java]: Done

File: src/main/java/org/opensearch/knn/index/store/VectorReader.java (hunk 4 above)
Comment (sobhu17) [reply src/main/java/org/opensearch/knn/index/store/VectorReader.java:16]: We introduced this class to keep the deduplication logic isolated. It’s cleaner and more maintainable to have a dedicated class responsible for loading vectors into JNI, rather than accessing vector values directly.

**Comment by sobhu17** [comment]
> Can we add test coverage for this change?

Hey @jmazanec15, in this PR we are just defining all the classes that we need for C++ to load vectors during load time. The tests would be added as a part of second PR.

File: src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java [hunk 6]
```diff
@@ -362,8 +363,17 @@ private IOSupplier<VectorSearcher> getVectorSearcherSupplier(final FieldInfo fie
 
         // Start creating searcher
         final String fileName = KNNCodecUtil.getNativeEngineFileFromFieldInfo(fieldInfo, segmentReadState.segmentInfo);
+        FlatVectorsReaderWithFieldName flatVectorsReaderWithFieldName = new FlatVectorsReaderWithFieldName(
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsReader.java]: Let's put this under line 370. We don't need this if fileName is null.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java [hunk 7]
```diff
@@ -90,6 +90,7 @@ public NativeMemoryAllocation.IndexAllocation load(NativeMemoryEntryContext.Inde
                 throw new IllegalStateException("Index [" + indexEntryContext.getOpenSearchIndexName() + "] is not preloaded");
             }
             try (indexEntryContext) {
+                indexEntryContext.indexInputWithBuffer.setKnnVectorValues(indexEntryContext.getKnnVectorValues());
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java:93]: Is there a way to pass KnnVectorValues to IndexInputWithBuffer?
So that we can avoid setting it every time when it needed.

File: src/main/java/org/opensearch/knn/index/store/VectorReader.java [hunk 8]
```diff
@@ -0,0 +1,54 @@
...
+     *
+     * This method will be invoked by the native layer via JNI to sequentially
+     * retrieve vectors during index loading.
+     *
+     * @return The next available float vector, or null
+     * @throws IOException if there is an error accessing the vector
+     */
+    public float[] nextFloatVector() throws IOException {
+        int docId = knnVectorValues.nextDoc();
+        if (docId != -1 && knnVectorValues instanceof KNNFloatVectorValues) {
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/index/store/VectorReader.java]: Can you use `NO_MORE_DOCS` instead of -1?

File: src/main/java/org/opensearch/knn/index/store/VectorReader.java [hunk 9]
```diff
@@ -0,0 +1,54 @@
...
+     *
+     * This method will be invoked by the native layer via JNI to sequentially
+     * retrieve vectors during index loading.
+     *
+     * @return The next available byte vector, or null
+     * @throws IOException if there is an error accessing the vector
+     */
+    public byte[] nextByteVector() throws IOException {
+        int docId = knnVectorValues.nextDoc();
+        if (docId != -1 && knnVectorValues instanceof KNNByteVectorValues) {
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/index/store/VectorReader.java]: Can you use `NO_MORE_DOCS` instead of -1?

File: src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java [hunk 10]
```diff
@@ -33,6 +34,7 @@ public abstract class FaissIndex {
     protected int totalNumberOfVectors;
     // Space type used to index vectors in this index.
     protected SpaceType spaceType;
+    static long DEDUPE_VECTORS_OPT_DISABLED = 0xFFFFFFF;
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java]: We should assign a greater value than INT_MAX.
Since uint32_t is being used internally in Faiss, the one that we occupied can be used by Faiss in the future.
You can use Long.MAX_VALUE, which will set 1 as most significant bit in the expanded uint64_t.

File: src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java [hunk 11]
```diff
@@ -49,20 +51,21 @@ public FaissIndex(final String indexType) {
...
-        faissIndex.doLoad(input);
+        faissIndex.doLoad(input, flatVectorsReaderWithFieldName);
         return faissIndex;
     }
 
-    protected abstract void doLoad(IndexInput input) throws IOException;
+    protected abstract void doLoad(IndexInput input, FlatVectorsReaderWithFieldName flatVectorsReaderWithFieldName) throws IOException;
 
-    protected void readCommonHeader(IndexInput readStream) throws IOException {
+    protected boolean readCommonHeader(IndexInput readStream) throws IOException {
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java:70]: Please add a simple doc for this, especially regarding to the return type. and where puts DEDUPE_VECTORS_OPT_DISABLED.

File: src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java [hunk 12]
```diff
@@ -49,20 +51,21 @@ public FaissIndex(final String indexType) {
...
         dimension = readStream.readInt();
         totalNumberOfVectors = Math.toIntExact(readStream.readLong());
         // consume 2 dummy deprecated fields.
-        readStream.readLong();
+        final long dedupCheck = readStream.readLong();
+        final boolean dedupApplied = dedupCheck == DEDUPE_VECTORS_OPT_DISABLED;
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndex.java]: For scalability, could you use 

```
(dedupCheck & DEDUPE_VECTORS_OPT_DISABLED) != 0;
```

File: src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java [hunk 13]
```diff
@@ -93,7 +100,10 @@ public VectorEncoding getVectorEncoding() {
     }
 
     @Override
-    public FloatVectorValues getFloatValues(IndexInput indexInput) {
+    public FloatVectorValues getFloatValues(IndexInput indexInput) throws IOException {
+        if (flatVectors == null) {
```
Comment (0ctopus13prime) [inline src/main/java/org/opensearch/knn/memoryoptsearch/faiss/FaissIndexScalarQuantizedFlat.java:109]: NIT : Please add small comments on this.
Something like, dedup optimization was enabled, so it will read vectors from .vec.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java (hunk 7 above)
Comment (sobhu17) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryLoadStrategy.java:93]: I tried it but IndexInputWithBuffer follows one path via this NativeMemoryEntryContext and we are setting up the KNNVectorValues in this path only that is in KNNIndexShard.java and DefaultKNNWeight.java with the help of LeafReader.

File: src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java (hunk 2 above)
Comment (navneet1v) [reply src/main/java/org/opensearch/knn/memoryoptsearch/FlatVectorsReaderWithFieldName.java:16]: If that is the case then just change the `FlatVectorsReader` class why to create another class?
