### PR TITLE
Don't fall back to CPU on terminal exceptions

### LINKED ISSUE #2766: [BUG] Terminate Index build request if Failed to write index in segment
## Description
Currently, if a k-NN index graph build fails at segment level for GPU based index acceleration, we always fallback to to CPU. But there are some hard failures like IndexInput is closed or index is deleted. We fallback to CPU and then again hit same hard failure before failing the shard. 

Ideally in case of hard failures we should throw the exception out and shouldn't fall back to CPU.

BTW in the CPU flow, if we are not able to write the index in the segment we completely fail the shard. So it should be safe to do so.

The current behavior is just not optimal it doesn't impact consistency. It just waste the compute.

### PR DESCRIPTION
**Pull request by owenhalpert**
### Description
From the issue:

> Currently, if a k-NN index graph build fails at segment level for GPU based index acceleration, we always fallback to to CPU. But there are some hard failures like IndexInput is closed or index is deleted. We fallback to CPU and then again hit same hard failure before failing the shard. Ideally in case of hard failures we should throw the exception out and shouldn't fall back to CPU.

This PR introduces a new exception to signal to the remote build process that no fall back strategy should be invoked, instead the exception should be rethrown to the caller to terminate the build altogether.

### Related Issues
Resolves #2766 

### Check List
- [X] New functionality includes testing.
~- [] New functionality has been documented.~
~- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [X] Commits are signed per the DCO using `--signoff`.
~- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java [hunk 1]
```diff
@@ -72,7 +73,11 @@ private void writeFromStreamWithBuffer(InputStream inputStream, byte[] outputBuf
             assert bytesRead <= outputBuffer.length;
             // However many bytes we read, write it to the IndexOutput if != -1
             if (bytesRead != -1) {
-                indexOutput.writeBytes(outputBuffer, 0, bytesRead);
+                try {
+                    indexOutput.writeBytes(outputBuffer, 0, bytesRead);
+                } catch (IOException e) {
+                    throw new RemoteIndexBuildStrategy.TerminalIOException("Failed to write to indexOutput", e);
```
Comment (jed326) [inline src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java]: So `writeFromStreamWithBuffer` is actually used by both the native and remote index build strategies. I'm a little worried about catching and rethrowing like this in the native case, so I'm wondering if we should just split the native and remote use cases into 2 different methods?

Comment (owenhalpert) [reply src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java]: It looks like both paths do share the `writeBytes` method but this `writeFromStreamWithBuffer` method is only in the remote path. So, it should be fine to keep this here.

Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java]: So here we are catching IO exception and then wrapping with terminal exception,  why ? Why can't we we terminate the RemoteBuild in case of IO exception? Unless/ until we have way to differentiate between out of these IO Execptions , theses are my termianal states , Which I don't see here.

Comment (owenhalpert) [reply src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java]: There are many places in the code, throughout the entire remote build process, where an IOException can be thrown that is not a terminal failure. In these cases we need to fallback. Example:

https://github.com/opensearch-project/k-NN/blob/5aec8550f34bb55f57eec895fd10c0a1ddc43ae6/src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/DefaultVectorRepositoryAccessor.java#L230-L243

The `readFromRepository` method has potential IOExceptions being thrown on both of the last two lines:

```
InputStream graphStream = blobContainer.readBlob(fileName);
indexOutputWithBuffer.writeFromStreamWithBuffer(graphStream, INDEX_DOWNLOAD_BUFFER_SIZE);
```

We do not want to cancel the build if the S3 operation `readBlob` fails. We do want to cancel if the `writeFromStreamWithBuffer` fails on the write to indexOutput, because of the statement at the top of this PR.

**Comment by owenhalpert** [comment]
> @owenhalpert So we never gonna fall back to CPU ...because IndexInput will be closed on all the cases. Is my Understanding correct.

No, the index input will not be closed in every case. That would be considered a hard failure on the CPU build, so instead of trying the CPU build and failing again, we can save the compute by failing early in the GPU path for these specific terminal error scenarios like the index input being closed or the index deleted.

File: src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java (hunk 1 above)
Comment (Vikasht34) [reply src/main/java/org/opensearch/knn/index/store/IndexOutputWithBuffer.java]: Makes Sense !!

**Review by Vikasht34 — DISMISSED** [review]

File: src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java [hunk 2]
```diff
@@ -349,4 +357,15 @@ static RemoteBuildRequest buildRemoteBuildRequest(
             .indexParameters(indexInfo.getKnnEngine().createRemoteIndexingParameters(parameters))
             .build();
     }
+
+    /**
+     * Custom exception class to distinguish between terminal IOExceptions (in the case of writing to index output,
+     * for example) and non-terminal (e.g. reading from S3). See {@link DefaultVectorRepositoryAccessor#readFromRepository}.
+     * Useful for determining whether to fall back to CPU build or terminate build altogether.
+     */
+    public static class TerminalIOException extends IOException {
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java]: [Minor] we should move this to a separate file, inner classes are good if you keep the scope limited to just same file. but since this exception is being used at multiple places better to have a separate file for it

**Review by navneet1v — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]

File: src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java (hunk 2 above)
Comment (owenhalpert) [reply src/main/java/org/opensearch/knn/index/codec/nativeindex/remote/RemoteIndexBuildStrategy.java]: Thanks Navneet, I like that
