### PR TITLE
Throw errors on model deletion failures

### LINKED ISSUE #831: Failure to delete model when model is training should not return 200
Currently, when we try to delete a model while it is training, we block the request:
```
curl -X DELETE "localhost:9200/_plugins/_knn/models/my-model3?pretty"
{
  "model_id" : "my-model3",
  "result" : "failed",
  "error" : "Cannot delete model \"my-model3\". Model is still in training"
}
```
However, this request returns a 200 response code, even though it failed to delete the resource.

```
curl -I -X DELETE "localhost:9200/_plugins/_knn/models/my-model3"
HTTP/1.1 200 OK
```

I believe that this should throw a 409 conflict error code.

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Throws errors on model deletion. Previously we were indicating failure, but returning 200 response codes. This changes that to throw exceptions with the correct response code.

Deprecates constructor for [DeleteModelResponse](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/plugin/transport/DeleteModelResponse.java) that takes an error/result, as this result should only be returned on success.
 
### Issues Resolved
#831 
 
### Check List
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+import org.opensearch.rest.RestStatus;
+
+public class DeleteModelWhenInTrainStateException extends OpenSearchException {
+    public DeleteModelWhenInTrainStateException(String msg, Object... args) {
+        super(LoggerMessageFormat.format(msg, args));
+    }
+
+    @Override
+    public RestStatus status() {
+        return RestStatus.CONFLICT;
```
Comment (naveentatikonda) [inline src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java:19]: Can you pls tell why are we overriding it and what does CONFLICT do here ?

File: src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+package org.opensearch.knn.common.exception;
+
+import org.opensearch.OpenSearchException;
+import org.opensearch.common.logging.LoggerMessageFormat;
+import org.opensearch.rest.RestStatus;
+
+public class DeleteModelWhenInTrainStateException extends OpenSearchException {
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java:12]: add documentation on the public class.

File: src/main/java/org/opensearch/knn/indices/ModelDao.java [hunk 3]
```diff
@@ -462,9 +461,10 @@ public boolean isModelInGraveyard(String modelId) {
         public void delete(String modelId, ActionListener<DeleteModelResponse> listener) {
             // If the index is not created, there is no need to delete the model
             if (!isCreated()) {
-                logger.error("Cannot delete model \"" + modelId + "\". Model index " + MODEL_INDEX_NAME + "does not exist.");
-                String errorMessage = String.format("Cannot delete model \"%s\". Model index does not exist", modelId);
-                listener.onResponse(new DeleteModelResponse(modelId, FAILED, errorMessage));
+                String errorMessage = String.format("Cannot delete model [%s]. Model index [%s] does not exist", modelId, MODEL_INDEX_NAME);
+                Exception e = new ResourceNotFoundException(errorMessage);
+                logger.error(e);
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/indices/ModelDao.java:466]: This is really interesting use of exception. In general we log the exception trace so that we know from where exception came. but here this is not the case.

If we put a log.error message here will that not be sufficient?

File: src/main/java/org/opensearch/knn/indices/ModelDao.java [hunk 4]
```diff
@@ -489,8 +490,10 @@ public void delete(String modelId, ActionListener<DeleteModelResponse> listener)
             getModelStep.whenComplete(getModelResponse -> {
                 // If model is in Training state, fail delete model request
                 if (ModelState.TRAINING == getModelResponse.getModel().getModelMetadata().getState()) {
-                    String errorMessage = String.format("Cannot delete model \"%s\". Model is still in training", modelId);
-                    listener.onResponse(new DeleteModelResponse(modelId, FAILED, errorMessage));
+                    String errorMessage = String.format("Cannot delete model [%s]. Model is still in training", modelId);
+                    Exception e = new DeleteModelWhenInTrainStateException(errorMessage);
+                    logger.error(e);
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/indices/ModelDao.java:495]: same as above.

**Comment by naveentatikonda** [comment]
Do you also want to refactor the BWC tests for model Deletion?
https://github.com/opensearch-project/k-NN/blob/main/qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/ModelIT.java

File: src/main/java/org/opensearch/knn/indices/ModelDao.java (hunk 3 above)
Comment (martin-gaievski) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:466]: We also need exception instance to pass it to the listener.onFailure, I guess that's the main reason why we create it

File: src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java (hunk 1 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/common/exception/DeleteModelWhenInTrainStateException.java:19]: The issue is that the resource cannot be deleted because it is not in the proper state. This aligns with:
```
     * The request could not be completed due to a conflict with the current state of the resource. This code is
     * only allowed in situations where it is expected that the user might be able to resolve the conflict and
     * resubmit the request. The response body SHOULD include enough information for the user to recognize the
     * source of the conflict. Ideally, the response entity would include enough information for the user or user
     * agent to fix the problem; however, that might not be possible and is not required.
```
From https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/rest/RestStatus.java#L354-L366.

I can add a comment on it.

File: src/main/java/org/opensearch/knn/indices/ModelDao.java (hunk 3 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:466]: > In general we log the exception trace so that we know from where exception came. but here this is not the case.

Im not sure what you mean by this. I wanted to log the error here so that we can see the complete stack trace. We can also just log the errorMessage, but I felt adding additional information about the exception would be helpful.

File: src/main/java/org/opensearch/knn/indices/ModelDao.java (hunk 4 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:495]: Will track discussion above.

**Comment by jmazanec15** [comment]
@naveentatikonda yes, I missed that one. Will update.

File: src/main/java/org/opensearch/knn/indices/ModelDao.java (hunk 3 above)
Comment (navneet1v) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:466]: What information you are adding here? I see log can do the job.




> Im not sure what you mean by this.

What I mean was why not log the error message in when `listener.onFailure(e);` is executed, which is the line just below this code.

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java]: Got it, I updated.

**Comment by jmazanec15** [comment]
Failure on windows related to: https://github.com/opensearch-project/OpenSearch/pull/7080. 

Please review @naveentatikonda @martin-gaievski @navneet1v

**Review by naveentatikonda — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]
