### PR TITLE
Set NoMergePolicy for codec tests

### LINKED ISSUE #750: [AUTOCUT] OS Distribution Build Failed for k-NN-3.0.0
***Received Error***: **Error building k-NN, retry with: ./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component k-NN**.
                      The distribution build for k-NN has failed.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/7056/consoleFull

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Sets NoMerge as merge policy for codec tests. This allows us to reliably predict how many segments will be created.

This fixes flaky test case that caused 3.0 build to fail
 
### Issues Resolved
#750 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
What is the policy that is applied now, before this change?

File: src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java [hunk 1]
```diff
@@ -317,6 +320,7 @@ public void testKnnVectorIndex(
         IndexWriterConfig iwc = newIndexWriterConfig();
         iwc.setMergeScheduler(new SerialMergeScheduler());
         iwc.setCodec(codec);
+        iwc.setMergePolicy(NoMergePolicy.INSTANCE);
```
Comment (heemin32) [inline src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java:323]: Would be nice to have a comment explaining why we need this policy.
Shouldn't we modify the test itself so that it won't fail even without specifying this policy?

**Comment by jmazanec15** [comment]
@martin-gaievski TieredMergePolicy is used.

File: src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java (hunk 1 above)
Comment (heemin32) [reply src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java:323]: More specific test with less chance of missing fault is better. In that sense, using NoMergePolicy is better I guess.

Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/index/codec/KNNCodecTestCase.java]: Sounds good. I updated and added a comment.

**Review by martin-gaievski — APPROVED** [review]

**Review by heemin32 — APPROVED** [review]
