### PR TITLE
Fix quant bwc main

### LINKED ISSUE #2991: [BUG] Disk Based BWC Issues for 2.19 -> 3.3 upgrade
**What is the bug?**
An exception is thrown when loading segments from >2.17 in a 3.2+ cluster due to a missed backwards compatibility (BWC) check in the `NativeEngines990KnnVectorsWriter` class.

**How can one reproduce the bug?**

Create segments in OpenSearch 2.19 cluster. Kill the OpenSearch 2.19 cluster and bring up an OpenSearch 3.3 cluster. 

How to reproduce the issue:
1. start up a cluster on 3.3 and a data directory containing 2.19 segments:

```
./gradlew run --data-dir /Users/finnrobl/opensearch-219-segments/opensearch-data-219-clean
```
We can see segments are created in 2.19 (lucene version 9.12.3):
```
(base) finnrobl@80a997329e07 ~ % curl -X GET "localhost:9200/_cat/segments"
target_index 0 p 127.0.0.1 _0 0 14 0 8.4kb 0 true true 9.12.3 true
target_index 1 p 127.0.0.1 _0 0 11 0 7.8kb 0 true true 9.12.3 true
```

Add new docs to the same index:

```
curl --location 'http://localhost:9200/_bulk' \
--header 'Content-Type: application/json' \
--data '{ "index": { "_index": "target_index"} }
{ "location": [5, 4.4], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [5.2, 3], "parking" : "false", "rating" : 4 }
{ "index": { "_index": "target_index"} }
{ "location": [4, 3.4], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 4.6], "parking" : "false", "rating" : 6}
{ "index": { "_index": "target_index"} }
{ "location": [3.3, 4], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [6, 3.4], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 6], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [2.4, 4.2], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [1.4, 3.1], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [7.0, 9.3], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [3.0, 2.2], "parking" : "false", "rating" : 6 }
{ "index": { "_index": "target_index"} }
{ "location": [5.0, 1.1], "parking" : "true", "rating" : 3 }
{ "index": { "_index": "target_index"} }
{ "location": [5.2, 4.4], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [5.2, 3.5], "parking" : "false", "rating" : 4 }
{ "index": { "_index": "target_index"} }
{ "location": [4.9, 3.6], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 4.7], "parking" : "false", "rating" : 6}
{ "index": { "_index": "target_index"} }
{ "location": [3.3, 4.8], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [6.4, 3.9], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 6.7], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [2.4, 4.7], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [1.4, 3.8], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [7.0, 9.5], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [3.0, 2.3], "parking" : "false", "rating" : 6 }
{ "index": { "_index": "target_index"} }
{ "location": [5.0, 1.2], "parking" : "true", "rating" : 3 }
{ "index": { "_index": "target_index"} }
{ "location": [5.0, 1.1], "parking" : "true", "rating" : 3 }

'
> 
{"took":280,"errors":false,"items":[{"index":{"_index":"target_index","_id":"vPwlzJoB84sL8GWoZ_s4","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":11,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"vfwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":14,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"vvwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":12,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"v_wlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":15,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"wPwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":13,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"wfwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":16,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"wvwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":14,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"w_wlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":15,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"xPwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":16,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"xfwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":17,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"xvwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":17,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"x_wlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":18,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"yPwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":18,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"yfwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":19,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"yvwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":20,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"y_wlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":21,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"zPwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":22,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"zfwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":19,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"zvwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":23,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"z_wlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":20,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"0PwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":21,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"0fwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":22,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"0vwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":24,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"0_wlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":25,"_primary_term":2,"status":201}},{"index":{"_index":"target_index","_id":"1PwlzJoB84sL8GWoZ_s9","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":26,"_primary_term":2,"status":201}}]}
```

Flush to 10.3 segments:
```
(base) finnrobl@80a997329e07 ~ % curl -X POST --location 'localhost:9200/target_index/_flush'
{"_shards":{"total":2,"successful":2,"failed":0}}%
```
See the segments:
```
index        shard prirep ip        segment generation docs.count docs.deleted  size size.memory committed searchable version compound
target_index 0     p      127.0.0.1 _0               0         14            0 8.4kb           0 true      true       9.12.3  true
target_index 0     p      127.0.0.1 _1               1         13            0 8.3kb           0 true      false      10.3.1  true
target_index 1     p      127.0.0.1 _0               0         11            0 7.8kb           0 true      true       9.12.3  true
target_index 1     p      127.0.0.1 _1               1         12            0 8.1kb           0 true      false      10.3.1  true
```
Force merge to 1 segment per shard (should version upgrade to 10.3):
```
(base) finnrobl@80a997329e07 ~ % curl -X POST "localhost:9200/target_index/_forcemerge?max_num_segments=1"
{"_shards":{"total":2,"successful":1,"failed":1,"failures":[{"shard":0,"index":"target_index","status":"INTERNAL_SERVER_ERROR","reason":{"type":"illegal_state_exception","reason":"this writer hit an unrecoverable error; cannot complete forceMerge","caused_by":{"type":"illegal_argument_exception","reason":"Invalid csv for quantization config: \"type=binary,bits=1\""}}}]}}%
```

Here are the logs on the server:
```
[2025-11-28T11:59:38,598][INFO ][o.o.c.s.ClusterManagerService] [integTest-0] Tasks batched with key: org.opensearch.cluster.coordination.JoinHelper, count:3 and sample tasks: elected-as-cluster-manager ([1] nodes joined)[{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{hT89WpQ9RTmgvT5E8b4zWw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ} elect leader, _BECOME_CLUSTER_MANAGER_TASK_, _FINISH_ELECTION_], term: 2, version: 7, delta: cluster-manager node changed {previous [], current [{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{hT89WpQ9RTmgvT5E8b4zWw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ}]}
[2025-11-28T11:59:38,658][INFO ][o.o.c.s.ClusterApplierService] [integTest-0] cluster-manager node changed {previous [], current [{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{hT89WpQ9RTmgvT5E8b4zWw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ}]}, term: 2, version: 7, reason: Publication{term=2, version=7}
[2025-11-28T11:59:38,667][INFO ][o.o.d.PeerFinder         ] [integTest-0] setting findPeersInterval to [1s] as node commission status = [true] for local node [{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{hT89WpQ9RTmgvT5E8b4zWw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ}]
[2025-11-28T11:59:38,708][INFO ][o.o.g.GatewayService     ] [integTest-0] recovered [1] indices into cluster_state
[2025-11-28T11:59:38,848][INFO ][o.o.p.PluginsService     ] [integTest-0] PluginService:onIndexModule index:[target_index/ox3fWt69S-i8q40GTxP3Uw]
[2025-11-28T11:59:39,248][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[target_index][0]]]).
[2025-11-28T12:00:08,714][WARN ][o.o.c.InternalClusterInfoService] [integTest-0] No resource usage stats available for node: integTest-0
[2025-11-28T12:28:06,758][WARN ][o.o.i.e.Engine           ] [integTest-0] [target_index][0] failed engine [merge failed]
org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
        at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun(InternalEngine.java:2544) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:975) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
        at org.apache.lucene.index.IndexWriter.hasPendingMerges(IndexWriter.java:2448) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:2502) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:131) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
Caused by: java.lang.IllegalArgumentException: Invalid csv for quantization config: "type=binary,bits=1"
        at org.opensearch.knn.index.engine.qframe.QuantizationConfigParser.parseCurrentVersion(QuantizationConfigParser.java:84) ~[?:?]
        at org.opensearch.knn.index.engine.qframe.QuantizationConfigParser.fromCsv(QuantizationConfigParser.java:75) ~[?:?]
        at org.opensearch.knn.common.FieldInfoExtractor.extractQuantizationConfig(FieldInfoExtractor.java:85) ~[?:?]
        at org.opensearch.knn.index.quantizationservice.QuantizationService.getQuantizationParams(QuantizationService.java:122) ~[?:?]
        at org.opensearch.knn.index.codec.KNN990Codec.NativeEngines990KnnVectorsWriter.train(NativeEngines990KnnVectorsWriter.java:232) ~[?:?]
        at org.opensearch.knn.index.codec.KNN990Codec.NativeEngines990KnnVectorsWriter.mergeOneField(NativeEngines990KnnVectorsWriter.java:152) ~[?:?]
        at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.mergeOneField(PerFieldKnnVectorsFormat.java:126) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.codecs.KnnVectorsWriter.merge(KnnVectorsWriter.java:105) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.mergeVectorValues(SegmentMerger.java:271) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.mergeWithLogging(SegmentMerger.java:314) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:158) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5317) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4778) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6601) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:668) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:126) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
[2025-11-28T12:28:06,794][WARN ][o.o.i.c.IndicesClusterStateService] [integTest-0] [target_index][0] marking and sending shard failed due to [shard failure, reason [merge failed]]
org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
        at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun(InternalEngine.java:2544) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:975) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
        at org.apache.lucene.index.IndexWriter.hasPendingMerges(IndexWriter.java:2448) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:2502) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:131) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
Caused by: java.lang.IllegalArgumentException: Invalid csv for quantization config: "type=binary,bits=1"
        at org.opensearch.knn.index.engine.qframe.QuantizationConfigParser.parseCurrentVersion(QuantizationConfigParser.java:84) ~[?:?]
        at org.opensearch.knn.index.engine.qframe.QuantizationConfigParser.fromCsv(QuantizationConfigParser.java:75) ~[?:?]
        at org.opensearch.knn.common.FieldInfoExtractor.extractQuantizationConfig(FieldInfoExtractor.java:85) ~[?:?]
        at org.opensearch.knn.index.quantizationservice.QuantizationService.getQuantizationParams(QuantizationService.java:122) ~[?:?]
        at org.opensearch.knn.index.codec.KNN990Codec.NativeEngines990KnnVectorsWriter.train(NativeEngines990KnnVectorsWriter.java:232) ~[?:?]
        at org.opensearch.knn.index.codec.KNN990Codec.NativeEngines990KnnVectorsWriter.mergeOneField(NativeEngines990KnnVectorsWriter.java:152) ~[?:?]
        at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.mergeOneField(PerFieldKnnVectorsFormat.java:126) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.codecs.KnnVectorsWriter.merge(KnnVectorsWriter.java:105) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.mergeVectorValues(SegmentMerger.java:271) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.mergeWithLogging(SegmentMerger.java:314) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:158) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5317) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4778) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6601) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:668) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:126) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
[2025-11-28T12:28:06,807][WARN ][o.o.c.r.a.AllocationService] [integTest-0] failing shard [failed shard, shard [target_index][0], node[pw8C645xS7mDyuoYh3E_9g], [P], s[STARTED], a[id=IEkLEyDCRWOrXB-ZsxlhSw], message [shard failure, reason [merge failed]], failure [MergeException[java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge]; nested: IllegalStateException[this writer hit an unrecoverable error; cannot merge]; nested: IllegalArgumentException[Invalid csv for quantization config: "type=binary,bits=1"]; ], markAsStale [true]]
org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
        at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler$2.doRun(InternalEngine.java:2544) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:975) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
        at org.apache.lucene.index.IndexWriter.hasPendingMerges(IndexWriter.java:2448) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:2502) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:131) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
Caused by: java.lang.IllegalArgumentException: Invalid csv for quantization config: "type=binary,bits=1"
        at org.opensearch.knn.index.engine.qframe.QuantizationConfigParser.parseCurrentVersion(QuantizationConfigParser.java:84) ~[?:?]
        at org.opensearch.knn.index.engine.qframe.QuantizationConfigParser.fromCsv(QuantizationConfigParser.java:75) ~[?:?]
        at org.opensearch.knn.common.FieldInfoExtractor.extractQuantizationConfig(FieldInfoExtractor.java:85) ~[?:?]
        at org.opensearch.knn.index.quantizationservice.QuantizationService.getQuantizationParams(QuantizationService.java:122) ~[?:?]
        at org.opensearch.knn.index.codec.KNN990Codec.NativeEngines990KnnVectorsWriter.train(NativeEngines990KnnVectorsWriter.java:232) ~[?:?]
        at org.opensearch.knn.index.codec.KNN990Codec.NativeEngines990KnnVectorsWriter.mergeOneField(NativeEngines990KnnVectorsWriter.java:152) ~[?:?]
        at org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.mergeOneField(PerFieldKnnVectorsFormat.java:126) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.codecs.KnnVectorsWriter.merge(KnnVectorsWriter.java:105) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.mergeVectorValues(SegmentMerger.java:271) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.mergeWithLogging(SegmentMerger.java:314) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:158) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5317) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4778) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6601) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:668) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:126) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
[2025-11-28T12:28:06,818][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [GREEN] to [RED] (reason: [shards failed [[target_index][0]]]).
[2025-11-28T12:28:07,102][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[target_index][0]]]).
<============-> 94% EXECUTING [29m 40s]
```

**What is the expected behavior?**
Merges should succeed and all segments should be on latest lucene version. We are able to get successful merge by taking the following commit: https://github.com/opensearch-project/k-NN/pull/2986/files

We are working on reproducing the issue with a backwards compatibility `restart-upgrade` test here: https://github.com/opensearch-project/k-NN/pull/2987

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by finnroblin**
### Description
Fix a bug in backwards compatability checks when merging Lucene segments created with scalar quantization from pre-opensearch 3.2 to opensearch >3.2.

The root cause is a faulty bwc check in knn vectors writer. Lucene segments contain scalar quantization information in a FieldInfo object called `qframe_config`. These quantization settings are serialized and deserialized whenever segments are read and written. In OpenSearch 3.2 we added two new quantization features, asymmetric distance computation (ADC) and random rotation (RR) to boost search quality when using quantization. These additional two settings were also added to the `qframe_config`.

Therefore the `qframe_config` is length 2 in some old lucene segments and length 4 in segments created on or after version 3.2. To maintain backwards compatability we added a check using the in the QuantizationConfigParser that switches based on the lucene version to either read 4 values or 2 (check [here](https://github.com/opensearch-project/k-NN/blob/cb572c12bc9e6a62051ce2f5a042ca93652ffdb9/src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java#L74)). However the version passed into this method is incorrect in the case of merge: [here](https://github.com/opensearch-project/k-NN/blob/3.2/src/main/java/org/opensearch/knn/index/codec/KNN990Codec/NativeEngines990KnnVectorsWriter.java#L234) we use `segmentWriteState.segmentInfo.getVersion()` in the KnnVectorsWriter segment writer. This is in fact the version of the written segment (e.g. 10.3.1) and not that of the previous segments during merge. Due to Lucene's reader-writer separation there is no way we found to get the previous unmerged segment version. Please see the original issue for a full stacktrace and explanation of the bug. 

This change uses the length of the quantization config as the signal of which version the segment was created in. That is, if it is length 2, it infers that it is an old segment so random rotation and adc are disabled. If it is length 4 then it reads the adc and random rotation values from the segment quantization info.

This change includes a bwc test that fails without the fix through the same error path and passes for this fix. We can see the test failure against a clean 3.3 branch in this CI run: https://github.com/opensearch-project/k-NN/actions/runs/19841273178/job/56850083767?pr=2993#step:10:1847

The BWC check works like the following:

-     Create index on old cluster, flush lucene 9.11/9.12 segments (depending on which OS version >=2.17 < 3.2), merge to 1 segment per shard.
-    Bring up new index on >=3.2 version , write new segments, merge new segment with old segment.
 -   Assert that all the 9.11/9.12 segments are not searchable (i.e. merge succeeded).

The previous error we were seeing, as mentioned in the parent issue, is a merge exception like:

```
»  org.apache.lucene.index.MergePolicy$MergeException: java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
```

However, in a BWC test enviornment, the cluster quickly autorecovers so we cannot just take cluster health as a proxy for the merge error.

```
... (other parts of stack trace available in parent issue)
org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6601) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:668) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
        at org.opensearch.index.engine.OpenSearchConcurrentMergeScheduler.doMerge(OpenSearchConcurrentMergeScheduler.java:126) ~[opensearch-3.3.2-SNAPSHOT.jar:3.3.2-SNAPSHOT]
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:729) ~[lucene-core-10.3.1.jar:10.3.1 51190f35a16d2ce433139abfe0fd8365791b352a - 2025-10-02 09:50:16]
# shard fails
[2025-11-28T12:28:06,818][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [GREEN] to [RED] (reason: [shards failed [[target_index][0]]]).
# shard back to green in < 2 seconds!!
[2025-11-28T12:28:07,102][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[target_index][0]]]). 
```

What we can do is test that the old 9.11/9.12 segments are either deleted or not searchable. That check is what this test asserts.

```
(base) finnrobl@80a997329e07 ~ % curl -X POST "localhost:9200/target_index/_forcemerge?max_num_segments=1"
{"_shards":{"total":2,"successful":1,"failed":1,"failures":[{"shard":0,"index":"target_index","status":"INTERNAL_SERVER_ERROR","reason":{"type":"illegal_state_exception","reason":"this writer hit an unrecoverable error; cannot complete forceMerge","caused_by":{"type":"illegal_argument_exception","reason":"Invalid csv for quantization config: \"type=binary,bits=1\""}}}]}}%
(base) finnrobl@80a997329e07 ~ % curl -X GET "localhost:9200/_cat/segments?v"
index        shard prirep ip        segment generation docs.count docs.deleted   size size.memory committed searchable version compound
# old segment is still searchable since merge did not succeed!
target_index 0     p      127.0.0.1 _0               0         14            0  8.4kb           0 true      true       9.12.3  true
target_index 0     p      127.0.0.1 _1               1         13            0  8.3kb           0 true      true       10.3.1  true
target_index 1     p      127.0.0.1 _2               2         23            0 10.4kb           0 true      true       10.3.1  false
```

Additionally there are manual testing details attached at the bottom of this PR description.

### Related Issues
Resolves #2991

### Check List
- [X] New functionality includes testing.
- [ ] New functionality has been documented. (bugfix; not applicable).
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md). (bugfix; not applicable).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose). bugfix; not applicable).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

## Manual testing details

```
mkdir /Users/finnrobl/segments-for-gh-pr/
cp -r /Users/finnrobl/opensearch-data-219-with-segments/opensearch-data-219-clean /Users/finnrobl/segments-for-gh-pr/
```
```
./gradlew run --data-dir /Users/finnrobl/segments-for-gh-pr/opensearch-data-219-clean
```

```
(base) finnrobl@80a997329e07 ~ % curl -X GET "localhost:9200/_cat/segments?v"
index        shard prirep ip        segment generation docs.count docs.deleted  size size.memory committed searchable version compound
target_index 0     p      127.0.0.1 _0               0         14            0 8.4kb           0 true      true       9.12.3  true
target_index 1     p      127.0.0.1 _0               0         11            0 7.8kb           0 true      true       9.12.3  true
```

```
(base) finnrobl@80a997329e07 ~ % curl --location 'http://localhost:9200/_bulk' \
--header 'Content-Type: application/json' \
--data '{ "index": { "_index": "target_index"} }
{ "location": [5, 4.4], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [5.2, 3], "parking" : "false", "rating" : 4 }
{ "index": { "_index": "target_index"} }
{ "location": [4, 3.4], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 4.6], "parking" : "false", "rating" : 6}
{ "index": { "_index": "target_index"} }
{ "location": [3.3, 4], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [6, 3.4], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 6], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [2.4, 4.2], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [1.4, 3.1], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [7.0, 9.3], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [3.0, 2.2], "parking" : "false", "rating" : 6 }
{ "index": { "_index": "target_index"} }
{ "location": [5.0, 1.1], "parking" : "true", "rating" : 3 }
{ "index": { "_index": "target_index"} }
{ "location": [5.2, 4.4], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [5.2, 3.5], "parking" : "false", "rating" : 4 }
{ "index": { "_index": "target_index"} }
{ "location": [4.9, 3.6], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 4.7], "parking" : "false", "rating" : 6}
{ "index": { "_index": "target_index"} }
{ "location": [3.3, 4.8], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [6.4, 3.9], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [4.2, 6.7], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [2.4, 4.7], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [1.4, 3.8], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [7.0, 9.5], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [3.0, 2.3], "parking" : "false", "rating" : 6 }
{ "index": { "_index": "target_index"} }
{ "location": [5.0, 1.2], "parking" : "true", "rating" : 3 }
{ "index": { "_index": "target_index"} }
{ "location": [5.0, 1.1], "parking" : "true", "rating" : 3 }

'
{"took":73,"errors":false,"items":[{"index":{"_index":"target_index","_id":"SdMV4JoBzdyVQD23_1Jf","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":14,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"StMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":11,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"S9MV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":12,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"TNMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":15,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"TdMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":13,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"TtMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":16,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"T9MV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":17,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"UNMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":14,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"UdMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":18,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"UtMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":19,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"U9MV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":15,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"VNMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":20,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"VdMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":21,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"VtMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":22,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"V9MV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":23,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"WNMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":24,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"WdMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":16,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"WtMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":17,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"W9MV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":18,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"XNMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":25,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"XdMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":26,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"XtMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":19,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"X9MV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":20,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"YNMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":21,"_primary_term":3,"status":201}},{"index":{"_index":"target_index","_id":"YdMV4JoBzdyVQD23_1Jh","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":22,"_primary_term":3,"status":201}}]}%
```

```
(base) finnrobl@80a997329e07 ~ % curl -X GET "localhost:9200/_cat/segments?v"
index        shard prirep ip        segment generation docs.count docs.deleted  size size.memory committed searchable version compound
target_index 0     p      127.0.0.1 _0               0         14            0 8.4kb           0 true      true       9.12.3  true
target_index 0     p      127.0.0.1 _1               1         13            0 8.4kb           0 true      false      10.3.2  true
target_index 1     p      127.0.0.1 _0               0         11            0 7.8kb           0 true      true       9.12.3  true
target_index 1     p      127.0.0.1 _1               1         12            0 8.1kb           0 true      false      10.3.2  true
```

```
(base) finnrobl@80a997329e07 ~ % curl -X POST "localhost:9200/target_index/_forcemerge?max_num_segments=1"
{"_shards":{"total":2,"successful":2,"failed":0}}%
```

```
index        shard prirep ip        segment generation docs.count docs.deleted   size size.memory committed searchable version compound
target_index 0     p      127.0.0.1 _0               0         14            0  8.4kb           0 false     true       9.12.3  true
target_index 0     p      127.0.0.1 _2               2         27            0 11.1kb           0 true      false      10.3.2  false
target_index 1     p      127.0.0.1 _0               0         11            0  7.8kb           0 false     true       9.12.3  true
target_index 1     p      127.0.0.1 _2               2         23            0 10.4kb           0 true      false      10.3.2  false
```

```
(base) finnrobl@80a997329e07 ~ % curl -X POST "localhost:9200/target_index/_refresh"
{"_shards":{"total":2,"successful":2,"failed":0}}%
(base) finnrobl@80a997329e07 ~ % curl -X GET "localhost:9200/_cat/segments?v"
index        shard prirep ip        segment generation docs.count docs.deleted   size size.memory committed searchable version compound
target_index 0     p      127.0.0.1 _2               2         27            0 11.1kb           0 true      true       10.3.2  false
target_index 1     p      127.0.0.1 _2               2         23            0 10.4kb           0 true      true       10.3.2  false
```

No errors on cluster:
```
[2025-12-02T09:21:18,805][WARN ][o.o.g.DanglingIndicesState] [integTest-0] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
[2025-12-02T09:21:18,926][INFO ][o.o.n.Node               ] [integTest-0] initialized
[2025-12-02T09:21:18,926][INFO ][o.o.n.Node               ] [integTest-0] starting ...
[2025-12-02T09:21:19,022][INFO ][o.o.t.TransportService   ] [integTest-0] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2025-12-02T09:21:19,024][INFO ][o.o.t.TransportService   ] [integTest-0] Remote clusters initialized successfully.
[2025-12-02T09:21:19,215][INFO ][o.o.c.c.Coordinator      ] [integTest-0] cluster UUID [OSN8SoJHQdK7vlUN-66dWw]
[2025-12-02T09:21:19,220][WARN ][o.o.d.FileBasedSeedHostsProvider] [integTest-0] expected, but did not find, a dynamic hosts list at [/Users/finnrobl/Documents/k-nn-fresh-change/k-NN/build/testclusters/integTest-0/config/unicast_hosts.txt]
[2025-12-02T09:21:19,232][INFO ][o.o.h.AbstractHttpServerTransport] [integTest-0] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2025-12-02T09:21:19,235][INFO ][o.o.n.Node               ] [integTest-0] started
[2025-12-02T09:21:19,300][INFO ][o.o.c.s.ClusterManagerService] [integTest-0] Tasks batched with key: org.opensearch.cluster.coordination.JoinHelper, count:3 and sample tasks: elected-as-cluster-manager ([1] nodes joined)[{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{ff4s_ASQQCC18uriNyRfHw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ} elect leader, _BECOME_CLUSTER_MANAGER_TASK_, _FINISH_ELECTION_], term: 3, version: 12, delta: cluster-manager node changed {previous [], current [{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{ff4s_ASQQCC18uriNyRfHw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ}]}
[2025-12-02T09:21:19,354][INFO ][o.o.c.s.ClusterApplierService] [integTest-0] cluster-manager node changed {previous [], current [{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{ff4s_ASQQCC18uriNyRfHw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ}]}, term: 3, version: 12, reason: Publication{term=3, version=12}
[2025-12-02T09:21:19,361][INFO ][o.o.d.PeerFinder         ] [integTest-0] setting findPeersInterval to [1s] as node commission status = [true] for local node [{integTest-0}{pw8C645xS7mDyuoYh3E_9g}{ff4s_ASQQCC18uriNyRfHw}{127.0.0.1}{127.0.0.1:9300}{dimr}{testattr=test, shard_indexing_pressure_enabled=true, knn_cb_tier=integ}]
[2025-12-02T09:21:19,398][INFO ][o.o.g.GatewayService     ] [integTest-0] recovered [1] indices into cluster_state
[2025-12-02T09:21:19,497][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index target_index from [false] to [true]
[2025-12-02T09:21:19,497][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating maxThreadCount from [0] to [4] and maxMergeCount from [0] to [9] for index target_index.
[2025-12-02T09:21:19,497][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Initialized index target_index with maxMergeCount=9, maxThreadCount=4, autoThrottleEnabled=true
[2025-12-02T09:21:19,504][INFO ][o.o.p.PluginsService     ] [integTest-0] PluginService:onIndexModule index:[target_index/ox3fWt69S-i8q40GTxP3Uw]
[2025-12-02T09:21:19,545][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index target_index from [true] to [true]
[2025-12-02T09:21:19,890][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[target_index][0]]]).
[2025-12-02T09:21:49,380][WARN ][o.o.c.InternalClusterInfoService] [integTest-0] No resource usage stats available for node: integTest-0
<============-> 94% EXECUTING [4m 9s]
> :run
> IDLE
> IDLE
> IDLE
```

```
curl --location 'http://localhost:9200/_bulk' \
--header 'Content-Type: application/json' \
--data '{ "index": { "_index": "target_index"} }
{ "location": [15, 14.4], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [15.2, 13], "parking" : "false", "rating" : 4 }
{ "index": { "_index": "target_index"} }
{ "location": [14, 13.4], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [14.2, 14.6], "parking" : "false", "rating" : 6}
{ "index": { "_index": "target_index"} }
{ "location": [13.3, 14], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [16, 13.4], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [14.2, 16], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [12.4, 14.2], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [11.4, 13.1], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [17.0, 19.3], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [13.0, 12.2], "parking" : "false", "rating" : 6 }
{ "index": { "_index": "target_index"} }
{ "location": [15.0, 11.1], "parking" : "true", "rating" : 3 }
{ "index": { "_index": "target_index"} }
{ "location": [15.2, 14.4], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [15.2, 13.5], "parking" : "false", "rating" : 4 }
{ "index": { "_index": "target_index"} }
{ "location": [14.9, 13.6], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [14.2, 14.7], "parking" : "false", "rating" : 6}
{ "index": { "_index": "target_index"} }
{ "location": [13.3, 14.8], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [16.4, 13.9], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [14.2, 16.7], "parking" : "true", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [12.4, 14.7], "parking" : "true", "rating" : 8 }
{ "index": { "_index": "target_index"} }
{ "location": [11.4, 13.8], "parking" : "false", "rating" : 5 }
{ "index": { "_index": "target_index"} }
{ "location": [17.0, 19.5], "parking" : "true", "rating" : 9 }
{ "index": { "_index": "target_index"} }
{ "location": [13.0, 12.3], "parking" : "false", "rating" : 6 }
{ "index": { "_index": "target_index"} }
{ "location": [15.0, 11.2], "parking" : "true", "rating" : 3 }
{ "index": { "_index": "target_index"} }
{ "location": [15.0, 11.1], "parking" : "true", "rating" : 3 }

'
```

search works:
```
curl --location 'http://localhost:9200/target_index/_search' \
--header 'Content-Type: application/json' \
--data '{
  "query": {
    "bool": {
      "filter": {
        "term": {"parking": "true"}
      },
      "must": {
        "knn": {
          "location": {
            "vector": [15, 15],
            "k": 10
          }
        }
      }
    }
  }
}'

{"took":1139,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":15,"relation":"eq"},"max_score":548.5,"hits":[{"_index":"target_index","_id":"m9Mc4JoBzdyVQD234FKU","_score":548.5,"_source":{ "location": [17.0, 19.5], "parking" : "true", "rating" : 9 }},{"_index":"target_index","_id":"j9Mc4JoBzdyVQD234FKU","_score":545.5,"_source":{ "location": [17.0, 19.3], "parking" : "true", "rating" : 9 }},{"_index":"target_index","_id":"mNMc4JoBzdyVQD234FKU","_score":464.5,"_source":{ "location": [14.2, 16.7], "parking" : "true", "rating" : 5 }},{"_index":"target_index","_id":"l9Mc4JoBzdyVQD234FKU","_score":455.5,"_source":{ "location": [16.4, 13.9], "parking" : "true", "rating" : 9 }},{"_index":"target_index","_id":"jNMc4JoBzdyVQD234FKU","_score":454.0,"_source":{ "location": [14.2, 16], "parking" : "true", "rating" : 5 }},{"_index":"target_index","_id":"ktMc4JoBzdyVQD234FKU","_score":445.0,"_source":{ "location": [15.2, 14.4], "parking" : "true", "rating" : 5 }},{"_index":"target_index","_id":"i9Mc4JoBzdyVQD234FKU","_score":442.0,"_source":{ "location": [16, 13.4], "parking" : "true", "rating" : 9 }},{"_index":"target_index","_id":"htMc4JoBzdyVQD234FKU","_score":442.0,"_source":{ "location": [15, 14.4], "parking" : "true", "rating" : 5 }},{"_index":"target_index","_id":"lNMc4JoBzdyVQD234FKU","_score":428.5,"_source":{ "location": [14.9, 13.6], "parking" : "true", "rating" : 9 }},{"_index":"target_index","_id":"ltMc4JoBzdyVQD234FKU","_score":422.5,"_source":{ "location": [13.3, 14.8], "parking" : "true", "rating" : 8 }}]}}%
```

# create and validate an adc/random_rotation index

```
(base) finnrobl@80a997329e07 ~ % curl -XPUT "http://localhost:9200/vector-index" -H 'Content-Type: application/json' -d'
{
  "settings" : {
    "index": {
      "knn": true
    }
  },
  "mappings": {
    "properties": {
      "vector_field": {
        "type": "knn_vector",
        "dimension": 8,
        "method": {
            "name": "hnsw",
            "engine": "faiss",
            "space_type": "l2",
            "parameters": {
              "encoder": {
                "name": "binary",
                "parameters": {
                  "bits": 1,
                  "random_rotation": true,
                  "enable_adc": true
                }
              }
            }
        }
      }
    }
  }
}
'

(base) finnrobl@80a997329e07 ~ % curl --location 'http://localhost:9200/_bulk' \
--header 'Content-Type: application/json' \
--data '{ "index": { "_index": "vector-index"} }
{ "vector_field": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [1.0, 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [2.0, 3.1, 4.2, 5.3, 6.4, 7.5, 8.6, 9.7] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [0.8, 1.7, 2.6, 3.5, 4.4, 5.3, 6.2, 7.1] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [3.0, 4.9, 5.8, 6.7, 7.6, 8.5, 9.4, 10.3] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [0.3, 1.4, 2.5, 3.6, 4.7, 5.8, 6.9, 8.0] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8, 8.9] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [2.4, 3.5, 4.6, 5.7, 6.8, 7.9, 9.0, 10.1] }
{ "index": { "_index": "vector-index"} }
{ "vector_field": [0.7, 1.8, 2.9, 4.0, 5.1, 6.2, 7.3, 8.4] }
quote>
quote> '
{"took":16,"errors":false,"items":[{"index":{"_index":"vector-index","_id":"t9Mj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":3,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"uNMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":4,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"udMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":5,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"utMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":6,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"u9Mj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":7,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"vNMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":8,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"vdMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":9,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"vtMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":10,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"v9Mj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":11,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"wNMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":12,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"wdMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":13,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"wtMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":14,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"w9Mj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":15,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"xNMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":16,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"xdMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":17,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"xtMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":18,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"x9Mj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":19,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"yNMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":20,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"ydMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":21,"_primary_term":1,"status":201}},{"index":{"_index":"vector-index","_id":"ytMj4JoBzdyVQD23BlID","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":22,"_primary_term":1,"status":201}}]}%
(base) finnrobl@80a997329e07 ~ % curl --location 'http://localhost:9200/vector-index/_search' \
--header 'Content-Type: application/json' \
--data '{
  "query": {
    "knn": {
      "vector_field": {
        "vector": [1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.0, 8.0],
        "k": 10
      }
    }
  }
}'
{"took":646,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":10,"relation":"eq"},"max_score":0.006009654,"hits":[{"_index":"vector-index","_id":"wtMj4JoBzdyVQD23BlID","_score":0.006009654,"_source":{"vector_field":[1.0,2.1,3.2,4.3,5.4,6.5,7.6,8.7]}},{"_index":"vector-index","_id":"xdMj4JoBzdyVQD23BlID","_score":0.0060082744,"_source":{"vector_field":[1.9,2.8,3.7,4.6,5.5,6.4,7.3,8.2]}},{"_index":"vector-index","_id":"yNMj4JoBzdyVQD23BlID","_score":0.0060082744,"_source":{"vector_field":[1.2,2.3,3.4,4.5,5.6,6.7,7.8,8.9]}},{"_index":"vector-index","_id":"ytMj4JoBzdyVQD23BlID","_score":0.005858722,"_source":{"vector_field":[0.7,1.8,2.9,4.0,5.1,6.2,7.3,8.4]}},{"_index":"vector-index","_id":"wdMj4JoBzdyVQD23BlID","_score":0.005798676,"_source":{"vector_field":[0.5,1.5,2.5,3.5,4.5,5.5,6.5,7.5]}},{"_index":"vector-index","_id":"xNMj4JoBzdyVQD23BlID","_score":0.005798676,"_source":{"vector_field":[0.8,1.7,2.6,3.5,4.4,5.3,6.2,7.1]}},{"_index":"vector-index","_id":"x9Mj4JoBzdyVQD23BlID","_score":0.005798676,"_source":{"vector_field":[0.3,1.4,2.5,3.6,4.7,5.8,6.9,8.0]}},{"_index":"vector-index","_id":"w9Mj4JoBzdyVQD23BlID","_score":0.005386937,"_source":{"vector_field":[2.0,3.1,4.2,5.3,6.4,7.5,8.6,9.7]}},{"_index":"vector-index","_id":"ydMj4JoBzdyVQD23BlID","_score":0.005386937,"_source":{"vector_field":[2.4,3.5,4.6,5.7,6.8,7.9,9.0,10.1]}},{"_index":"vector-index","_id":"xtMj4JoBzdyVQD23BlID","_score":0.0052625095,"_source":{"vector_field":[3.0,4.9,5.8,6.7,7.6,8.5,9.4,10.3]}}]}}%
```

still no errors on doc:
```
[2025-12-02T09:21:19,398][INFO ][o.o.g.GatewayService     ] [integTest-0] recovered [1] indices into cluster_state
[2025-12-02T09:21:19,497][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index target_index from [false] to [true]
[2025-12-02T09:21:19,497][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating maxThreadCount from [0] to [4] and maxMergeCount from [0] to [9] for index target_index.
[2025-12-02T09:21:19,497][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Initialized index target_index with maxMergeCount=9, maxThreadCount=4, autoThrottleEnabled=true
[2025-12-02T09:21:19,504][INFO ][o.o.p.PluginsService     ] [integTest-0] PluginService:onIndexModule index:[target_index/ox3fWt69S-i8q40GTxP3Uw]
[2025-12-02T09:21:19,545][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index target_index from [true] to [true]
[2025-12-02T09:21:19,890][INFO ][o.o.c.r.a.AllocationService] [integTest-0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[target_index][0]]]).
[2025-12-02T09:21:49,380][WARN ][o.o.c.InternalClusterInfoService] [integTest-0] No resource usage stats available for node: integTest-0
[2025-12-02T09:32:32,783][INFO ][o.o.c.s.ClusterManagerTaskThrottler] [integTest-0] Starting cluster manager throttling as all nodes are higher than or equal to 2.5.0
[2025-12-02T09:32:32,787][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index vector-index from [false] to [true]
[2025-12-02T09:32:32,787][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating maxThreadCount from [0] to [4] and maxMergeCount from [0] to [9] for index vector-index.
[2025-12-02T09:32:32,787][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Initialized index vector-index with maxMergeCount=9, maxThreadCount=4, autoThrottleEnabled=true
[2025-12-02T09:32:32,788][INFO ][o.o.p.PluginsService     ] [integTest-0] PluginService:onIndexModule index:[vector-index/lUK9AnPHTcO5IXEv9BWqsQ]
[2025-12-02T09:32:32,791][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index vector-index from [true] to [true]
[2025-12-02T09:32:32,794][INFO ][o.o.c.m.MetadataCreateIndexService] [integTest-0] [vector-index] creating index, cause [api], templates [], shards [1]/[1]
[2025-12-02T09:32:32,830][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index vector-index from [false] to [true]
[2025-12-02T09:32:32,831][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating maxThreadCount from [0] to [4] and maxMergeCount from [0] to [9] for index vector-index.
[2025-12-02T09:32:32,831][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Initialized index vector-index with maxMergeCount=9, maxThreadCount=4, autoThrottleEnabled=true
[2025-12-02T09:32:32,831][INFO ][o.o.p.PluginsService     ] [integTest-0] PluginService:onIndexModule index:[vector-index/lUK9AnPHTcO5IXEv9BWqsQ]
[2025-12-02T09:32:32,833][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index vector-index from [true] to [true]
[2025-12-02T09:33:38,706][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating autoThrottle for index vector-index from [false] to [true]
[2025-12-02T09:33:38,707][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Updating maxThreadCount from [0] to [4] and maxMergeCount from [0] to [9] for index vector-index.
[2025-12-02T09:33:38,707][INFO ][o.o.i.MergeSchedulerConfig] [integTest-0] Initialized index vector-index with maxMergeCount=9, maxThreadCount=4, autoThrottleEnabled=true
[2025-12-02T09:33:38,708][INFO ][o.o.p.PluginsService     ] [integTest-0] PluginService:onIndexModule index:[vector-index/lUK9AnPHTcO5IXEv9BWqsQ]
[2025-12-02T09:33:38,714][INFO ][o.o.c.m.MetadataMappingService] [integTest-0] [vector-index/lUK9AnPHTcO5IXEv9BWqsQ] update_mapping [_doc]
<============-> 94% EXECUTING [16m 50s]
> :run
```

```
(base) finnrobl@80a997329e07 ~ % curl -X GET "localhost:9200/_cat/segments?v"
index        shard prirep ip        segment generation docs.count docs.deleted   size size.memory committed searchable version compound
target_index 0     p      127.0.0.1 _2               2         27            0 11.1kb           0 true      true       10.3.2  false
target_index 0     p      127.0.0.1 _3               3         12            0  8.1kb           0 true      true       10.3.2  true
target_index 1     p      127.0.0.1 _2               2         23            0 10.4kb           0 true      true       10.3.2  false
target_index 1     p      127.0.0.1 _3               3         13            0  8.3kb           0 true      true       10.3.2  true
vector-index 0     p      127.0.0.1 _0               0          3            0  3.5kb           0 false     true       10.3.2  true
vector-index 0     p      127.0.0.1 _1               1         20            0  8.8kb           0 false     true       10.3.2  true
```

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java [hunk 1]
```diff
@@ -66,65 +66,52 @@ public static String toCsv(QuantizationConfig quantizationConfig) {
      * @param csv Csv format of quantization config
      * @return Quantization config
      */
-    public static QuantizationConfig fromCsv(String csv, org.apache.lucene.util.Version luceneVersion) {
+    public static QuantizationConfig fromCsv(String csv) {
```
Comment (finnroblin) [inline src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java:69]: Previous PR has discussion about these checks: https://github.com/opensearch-project/k-NN/pull/2986#discussion_r2563177053

**Review by Vikasht34 — APPROVED** [review]
I am good with this PR .. Thanks for Addressing the comments on Other PR

File: src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java:58]: why we need this check now? Is it really needed? I am trying to think of a case when we need this version check in the write path?

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java:58]: This is not a blocker for this PR. But I am bit skeptical of this check.

Comment (finnroblin) [reply src/main/java/org/opensearch/knn/index/engine/qframe/QuantizationConfigParser.java:58]: I will take as a fast follow once this is merged to remove the check. The original thinking was to be cautious/explicit in the write path. I see the point that it's overcautious — any old code < 3.2 will only write two values. Any new code should write all 4 values, since by definition it's after 3.2 when the code was originally written. So there is no case where the new code is present, but version is before 3.2.

**Review by Vikasht34 — APPROVED** [review]
