### PR TITLE
Derived source dynamic template fix

### LINKED ISSUE #3012: [BUG] KNN 512-dimensional vector has broken value with derived_source: true and dynamic template
**What is the bug?**

KNN vector field has value `1`

**How can one reproduce the bug?**

**Edit**: I have minimally recreated the bug here: https://github.com/devk-scayle/os-knn-derived-source-bug

We upgraded to OS3.3 (from 2.19) and did reindexing. At some point we ended up with large number of KNN vectors with value `1`. These documents had expected 512 dimensional vector in the old index.

The mapping is done using dynamic template:
```
{
    "knn_vector_template": {
        "path_match": "similar_products_vector.*.clip_vit_base_patch32",
        "mapping": {
            "dimension": 512,
            "method": {
                "engine": "faiss",
                "space_type": "cosinesimil",
                "name": "hnsw",
                "parameters": {
                    "ef_search": 128,
                    "ef_construction": 128,
                    "m": 16
                }
            },
            "type": "knn_vector"
        }
    }
}
```

Further reindexing also failed with expected reason:
```
{
    "type": "illegal_argument_exception",
    "reason": "Vector dimension mismatch. Expected: 512, Given: 1"
}
```

**What is the expected behavior?**

Reindexing should not break existing vectors. Fields with knn_vector type should not accept broken values

_note_: manually updating the document kkn value to `1` fails, as expected.

**What is your host/environment?**

AWS managed OpenSearch 3.3 with KNN plugin.

**Do you have any screenshots?**

Proof of correct mappings, but broken value. See `similar_products_vector.2088.clip_vit_base_patch32`:

Image

**Do you have any additional context?**

I have also tried manually setting the new `derived_source` to `false` and could no longer reproduce the issue. We had this set to default (`false` pre-GA on 2.19, `true` since upgrade to 3.3).
I cannot 100% confirm this is the cause, but so far I could not reproduce it with it set to `false`, while it happened regularly with it set to `true`

**Edit:**

Upon further research, it looks like it this happens when _target_ index has `derived_source: true`. The source index is not the issue.

Image

It also looks like the issue might be the dynamic template. We have multiple knn graps (`similar_products_vector.1856`, `similar_products_vector.2167`, etc) and to the best of my findings: either all values under a graph are broken (1856 in the above screenshot) or all are correct (2167 in the above screenshot). Though, mapping for both shows knn_field as I would expect

### PR DESCRIPTION
**Pull request by buddharajusahil**
### Description
Fixes a bug where bulk indexing with dynamic templates and knn.derived_source.enabled=true caused vectors to be incorrectly returned as 1 instead of the actual vector array.

The Problem:
When bulk indexing documents that create new dynamic field mappings (e.g., similar_products_vector.*.clip_vit_base_patch32), only the first document's vector was correctly reconstructed. All subsequent documents returned the mask value 1 instead of the actual vector.

Root Cause:
Segment attributes (which track which fields need derived source reconstruction) were written in fieldsWriter() at segment creation time. At that point, only the first document's dynamic mapping existed in mapperService.fieldTypes(). Subsequent documents' dynamic mappings were created as they were parsed, after the segment attributes had already been written with an incomplete field list.

The Fix:
Move segment attribute writing from fieldsWriter() to finish(), which is called after all documents have been written to the segment and all dynamic mappings exist.
Add explicit segment attribute handling in merge() for merge operations, since finish() is not called during merge (the delegate's finish is called instead).

Changes:
KNN10010DerivedSourceStoredFieldsFormat: Removed early attribute writing from fieldsWriter(), now passes segmentInfo and mapperService to writer.
KNN10010DerivedSourceStoredFieldsWriter: Added attribute writing in finish() for normal indexing and in merge() for merge operations.
KNN10010DerivedSourceStoredFieldsReader: Added getDerivedVectorFields() getter to support field collection during merge.
Added regression test testDerivedSource_withDynamicTemplates_andBulkIndexing to prevent future regressions.

### Related Issues
Resolves #3012 

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 1]
```diff
@@ -88,21 +111,63 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
-        // In case of backwards compatibility, with old segments, we need to perform a non-optimal merge. Basically, it
-        // will repopulate each source and then inject the vector and then remove it. This allows us to migrate
-        // segments from filter approach to mask approach
         if (KNN9120DerivedSourceStoredFieldsReader.doesMergeContainLegacySegments(mergeState)) {
             return super.merge(mergeState);
         }
 
-        // We wrap the segments to avoid injecting back vectors and then removing. If this is not done, then we will
-        // inject and then just write to disk potentially.
+        Set<String> vectorFields = new HashSet<>();
```
Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java:176]: Nit:- We are using **HashSet**  in Merge and **mapperService.fieldTypes()** in finish , both can make non-deterministic order which might be difficult in debugging , Can we sort the field lists before writing segment attributes.

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java:176]: This makes sense, will add.

**Review by navneet1v — APPROVED** [review]

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 2]
```diff
@@ -43,12 +57,22 @@ public class KNN10010DerivedSourceStoredFieldsWriter extends StoredFieldsWriter
...
+        this.mapperService = mapperService;
+
+        List<String> vectorFieldTypes = new ArrayList<>();
+        for (MappedFieldType fieldType : mapperService.fieldTypes()) {
+            if (fieldType instanceof KNNVectorFieldType knnVectorFieldType) {
+                if (IndexUtil.isDerivedEnabledForField(knnVectorFieldType, mapperService)) {
+                    vectorFieldTypes.add(fieldType.name().toLowerCase());
+                }
+            }
+        }
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: this will not fix the issue, as writer is created only on first document so mapper service has knowledge about first document field only. For rest of the document adding new fields won't be present in mapper service yet and it will not create transformers for those fields. We will need to do it at per document level unfortunately and add transformers there for dynamic template case. 

Basically in our test, can we somehow validate that indeed mask is written to the `_source` for the vector fields because from search query it will always return the vector field irrespective of it is masked in source or not. Or another work around if we cannot validate this easily is use integer values for each dimension in vector and I think if it is masked it will return floats back. So we can assert if returned vectors have integer values that means it is not masked and stored as is ?

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: So actually original masking is done in derived source pre-index operation listener. So in all our IT's we have, the behavior will be correct, in that all fields will get masked. The masking done in the fields writer, as far as I know, is redundant, but just used a safety net as jack pointed out in his original PR: https://github.com/opensearch-project/k-NN/pull/2704

Which makes sense because otherwise the original customer queries would not have contained the mask as stated in the bug, it would include the full vector (since the vector would never have gotten masked in the first place). The case here that would fail would be that if writeField is called before preIndex, on documents that are not already masked, where all fields that are "to be" added don't yet exist in the mapperService, which I am not sure is a possible case.

Comment (sohami) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Right, so we are changing that behavior here by relying only on the masking in the Listener. Original linked PR had a caveat where author was not sure if listener based approach is handling all the cases correctly or not. So either we completely remove the masking logic from codec and rely only on the listener side of the things or we keep both in correct way which is not true in current state of the PR.

>The case here that would fail would be that if writeField is called before preIndex, on documents that are not already masked, where all fields that are "to be" added don't yet exist in the mapperService, which I am not sure is a possible case.

I think meta question is if there are cases when `writeField` is called without `preIndex` getting invoked. Both of these get exercised as part of indexing operation which can happen either as part of bulk request or as part of recovery (translog replay or sequence number based recovery in peer recovery). In all these ingestion path, `writeField` and `preIndex` both will be invoked. `preIndex` gets invoked as part of the [IndexShard private method index](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L1281) which takes care of indexing documents into the Lucene layer. With this we can remove the transformation from codec layer but there is another big caveat. If we keep transformation only in listener layer, and lets say there is any failure in the listener and it [throws exception, that will be caught and swallowed](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/shard/IndexingOperationListener.java#L113) and request path will flow to the codec layer. So if we remove the transformation logic from codec layer we will not mask vector fields for those operations. With this I don't see that we can escape the code layer transformation here.

Comment (Vikasht34) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Nice , In Depth Explanation @sohami , learned from your comment !! But Still I have question , Are u suggesting document level or What is your suggestion?

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Got it. Yea I think the codec layer mask's original intention was for merge cases, as this will go through the writeField flow without masking from preIndex, but even then it might be redundant. My thought was if any merge case existed where we needed codec masking, then we would anyways have all the fields in mapperservice anyways.

However the preindex failure case probably makes the codec dynamic masking unavoidable.

Comment (sohami) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: >But Still I have question , Are u suggesting document level or What is your suggestion?

Immediate fix is document level, don't see any other way out of it. If there is a way to differentiate dynamic template vs static mapping probably we can limit the overhead (if any) to dynamic template case itself.

As a follow-up we should work on https://github.com/opensearch-project/k-NN/issues/3058 which **may** remove the need of doing in codec or listener layer completely.

Comment (Vikasht34) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Thanks Make Sense

Comment (sohami) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: >Got it. Yea I think the codec layer mask's original intention was for merge cases, as this will go through the writeField flow without masking from preIndex

@buddharajusahil  But for merge cases, `_source` is already having mask for vector values. So we should not require to mask it again or apply transformers again right ? But yes segmentInfo needs to be updated with the list of fields for the newly created segment

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: @sohami I think for standard merge, documents will already have the mask from indexing so codec masking is not necessary. But I think the original PR was cautious about some edge cases. For example if a legacy KNN9120 segment is being merged with a 10010 segment, as far as I can tell, codec masking might be necessary, as KNN9120 codec filtered vectors completely out of its source in derived source path. On merge, the old segment source is read, which will include the entire vector.

Comment (sohami) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: @buddharajusahil [Setting is static](https://docs.opensearch.org/latest/vector-search/settings/#index-settings) so ideally it is not intended to change on existing index. So the case of old segments without mask should not exist. But I guess transformation during `merge` time can be separate discussion, please create a issue if transformation is happening today during merges. We can discuss and see if we need to optimize that as well.

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: @sohami Right the derived source setting isn't changing, I am talking about legacy KNN9120 format using derived source. In 9120 format, in derived source path, we just remove the vector entirely, and on read we put it back, there is no concept of masking, only vector field filtering. If we merge this with a 10010 format segment, we will need to apply the mask to the legacy segment in codec level. This is more about bwc.

Comment (sohami) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: So is 10010 format handling the case where a mask is not present for a document to still fetch the vector value from reader which may or may not be present (e.g. a doc without vector field) ? I think it is best to discuss the merge part separately as we need to consider all the different possibilities here. For the scope of this PR we can keep the merge behavior same as today.

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: @sohami Agreed, for this PR I will add the dynamic masking. 

Not sure I fully understand the question in the comment. The 10010 format reader finds the fields to inject from the segment info. If a documents source does not have any of the vector fields to inject, then it is treated as a no-op.

Comment (sohami) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Ignore my previous case, that was assuming a scenario when an older segment in an index on latest codec is not merged so it will not have masks for vector fields. How is that handled with new codec derived readers, however in that case for older segments, reader will still be from older codec so should be fine. 

Performing transformation during merge for bwc is fine. Thanks for sharing that use case. Wondering if we should have logic to ignore transformations when segments from 10010 codecs are merged so all the new indices atleast does not have to again do transformation in merge phase. It will be worth it if there is any performance gain with it.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 3]
```diff
@@ -88,62 +112,219 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
+     */
+    private boolean containsUnmaskedVectors(Map<String, Object> source) {
+        for (Map.Entry<String, Object> entry : source.entrySet()) {
+            Object value = entry.getValue();
+
+            // Check if this is an unmasked vector (List of Numbers with more than 1 element)
+            if (value instanceof List<?> list && !list.isEmpty()) {
+                Object first = list.get(0);
+                if (first instanceof Number && list.size() > 1) {
+                    return true;
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: I would recommend not to have utility method like this where we are assuming based on the field value type if it is a vector field or not. For reference, users can pass list of integers for an integer field type as well which will be treated as a multi-valued field.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 4]
```diff
@@ -88,62 +112,219 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
+                "Encountered NotXContent while deserializing _source field. Instead found String: [{}]",
+                new String(bytesRef.bytes, 0, Math.min(bytesRef.bytes.length, 512)),
+                e
+            );
+            return;
+        }
+
+        // Check if source is already masked from preindex masking path.
+        // If it is, we do not need to remask the source here
+        if (!containsUnmaskedVectors(mapTuple.v2())) {
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: We can remove this to preserve the older behavior of always masking in codec for now

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 5]
```diff
@@ -20,41 +22,63 @@
...
+            if (fieldType instanceof KNNVectorFieldType knnVectorFieldType) {
+                if (IndexUtil.isDerivedEnabledForField(knnVectorFieldType, mapperService)) {
+                    knownVectorFields.add(fieldType.name().toLowerCase());
+                }
+            }
+        }
+
+        if (!knownVectorFields.isEmpty()) {
+            vectorMask = buildMask(knownVectorFields);
         }
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: we can move the check for empty collections inside `buildMask` which can return `null` or  valid transformation function.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 6]
```diff
@@ -88,62 +112,219 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
+        }
+
+        // This path is only if source is not masked from preindex path
+        // Eg: preindex failed, merging legacy segment with modern segment - need to mask
+        // Find KNN fields in this document
+        if (vectorMask != null) {
+            Map<String, Object> filteredSource = vectorMask.apply(mapTuple.v2());
+
+            // Check if existing masking worked (no unmasked vectors remain)
+            if (!containsUnmaskedVectors(filteredSource)) {
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: 1. I think instead of handling like this where we iterate on `_source` to check if mask is applied on some field or not, can we use `mapperService` here to iterate and find all the fields with derived source enabled. Update `vectorMask` to initialize the masking lambda function for all the discovered fields and then just apply the mask on the current document ? Basically move the logic from constructor [here](https://github.com/opensearch-project/k-NN/pull/3035/files#diff-28fdc09fa0ef5c86ccc4f8a2ef9712c745485a41c0ff423ecafee3481ab32416R72) to this function. That will be much stronger and safer check based on fieldType and will be contained to this `writeField` method as well.
2. We should definitely do some perf benchmark to see if there is any performance impact on the ingestion and merges with this change.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 7]
```diff
@@ -157,8 +338,55 @@ public void finishDocument() throws IOException {
...
+                }
+
+                boolean isNested = mapperService.documentMapper().mappers().getNestedScope(fieldType.name()) != null;
+                if (isNested) {
+                    nestedVectorFieldTypes.add(fieldType.name());
+                } else {
+                    vectorFieldTypes.add(fieldType.name());
+                }
+            }
+        }
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: I think we can maintain both nested and non-nested derived field types as part of evaluating in `writeField` itself which can be later used here to update the segment info. Can we double confirm if writers will be recreated for each segment or reused such we will need to reset these states related to derivedFields or vectorMask

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 8]
```diff
@@ -88,62 +112,219 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
         for (int i = 0; i < mergeState.storedFieldsReaders.length; i++) {
             mergeState.storedFieldsReaders[i] = KNN10010DerivedSourceStoredFieldsReader.wrapForMerge(mergeState.storedFieldsReaders[i]);
         }
-        return delegate.merge(mergeState);
+
+        int result = delegate.merge(mergeState);
+
+        if (!vectorFields.isEmpty()) {
+            List<String> sortedVectorFields = new ArrayList<>(vectorFields);
+            Collections.sort(sortedVectorFields);
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: any reason to sort the fields here and in other places ?

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 9]
```diff
@@ -88,62 +112,219 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
+            DerivedSourceSegmentAttributeParser.addDerivedVectorFieldsSegmentInfoAttribute(
+                segmentInfo,
+                new ArrayList<>(vectorFields),
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: can we just pass set into `addDerivedVectorFieldsSegmentInfoAttribute` utility instead of converting it to list ? `Set` seems to provide better control to avoid duplicate fields from being written to segment info

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 5 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Sure, makes sense.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 8 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: I think this was to address @Vikasht34 comment that it would make debugging easier, but on second thought, I don't think it is applicable in this case.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 9 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Makes sense.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 7 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Writers are created when segment is created and are not reused across multiple segments. Sounds good.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 6 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Makes sense, sure.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 4 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Got it.

**Comment by navneet1v** [comment]
@buddharajusahil anything else left on this PR any reason why this PR is not getting merged?

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 10]
```diff
@@ -88,62 +99,150 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
+                    } else {
+                        knownVectorFields.add(fieldName.toLowerCase());
+                    }
+                }
+            }
+        }
+        // Build mask from both sets combined
+        Set<String> allFields = new HashSet<>();
+        allFields.addAll(knownVectorFields);
+        allFields.addAll(knownNestedVectorFields);
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: nit: this can be populated in above loop itself.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 11]
```diff
@@ -88,62 +99,150 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
             MediaType actualContentType = mapTuple.v1();
             XContentBuilder builder = MediaTypeRegistry.contentBuilder(actualContentType, bStream).map(filteredSource);
             builder.close();
-            BytesReference bytesReference = bStream.bytes();
-            delegate.writeField(fieldInfo, bytesReference.toBytesRef());
+            delegate.writeField(fieldInfo, bStream.bytes().toBytesRef());
             return;
         }
+
         delegate.writeField(fieldInfo, bytesRef);
```
Comment (sohami) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]:
```suggestion
        if (!Objects.equals(fieldInfo.name, SourceFieldMapper.NAME)) {
            delegate.writeField(fieldInfo, bytesRef);
            return;
        }
        
        // Check if mapperService has new fields (cheap integer comparison)
        int currentFieldCount = getFieldCount();
        if (currentFieldCount != lastKnownFieldCount) {
            refreshKnownVectorFields();
            lastKnownFieldCount = currentFieldCount;
        }
    
         // if we don't have any vector fields just pass it to delegate writer
         if (vectorMask == null) {
             delegate.writeField(fieldInfo, bytesRef);
             return;
         }

         // Reference: https://github.com/opensearch-project/OpenSearch/blob/2.18.0/server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java#L322
            
         // In the Index operation listener, preindex, we apply the mask operation. We apply it again for safety
         // here because writeField may not always follow the preindex step, so it might have the vector (think
         // merge). This may be overly cautious and we can remove/optimize it in the future. For now, its a safety net.
        Tuple<? extends MediaType, Map<String, Object>> mapTuple;
        try {
            mapTuple = XContentHelper.convertToMap(
                BytesReference.fromByteBuffer(ByteBuffer.wrap(bytesRef.bytes, bytesRef.offset, bytesRef.length)),
                true,
                MediaTypeRegistry.JSON
            );
        } catch (NotXContentException e) {
            // If the content is not XContent, skip writing altogether. See:
            // https://github.com/opensearch-project/k-NN/issues/2880
            log.warn(
                "Encountered NotXContent while deserializing _source field. Instead found String: [{}]",
                new String(bytesRef.bytes, 0, Math.min(bytesRef.bytes.length, 512)),
                e
            );
            return;
        }

        // Apply mask on vector fields in parsed source (idempotent - safe to apply even if already masked)
        Map<String, Object> filteredSource = vectorMask.apply(mapTuple.v2());
        BytesStreamOutput bStream = new BytesStreamOutput();
        MediaType actualContentType = mapTuple.v1();
        XContentBuilder builder = MediaTypeRegistry.contentBuilder(actualContentType, bStream).map(filteredSource);
        builder.close();
        delegate.writeField(fieldInfo, bStream.bytes().toBytesRef());
```

**Review by sohami — COMMENTED** [review]
@buddharajusahil Did you get chance to run perf benchmark with this change ? Curious to see if we are observing any latency impact here.

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java (hunk 10 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java]: Sure

**Comment by buddharajusahil** [comment]
@navneet1v @sohami Need review / approval again after merge conflict resolution.

**Review by Vikasht34 — DISMISSED** [review]

File: src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java [hunk 12]
```diff
@@ -90,66 +106,158 @@ public void writeField(FieldInfo info, StoredFieldDataInput value) throws IOExce
...
 
+    /**
+     * Builds a mask transform function for the given fields.
+     */
+    private Function<Map<String, Object>, Map<String, Object>> buildMask(Set<String> fields) {
+        if (fields == null || fields.isEmpty()) {
+            return null;
+        }
+        return XContentMapValues.transform(
+            fields.stream().collect(Collectors.toMap(k -> k, k -> (Object o) -> o == null ? o : MASK)),
```
Comment (shatejas) [inline src/main/java/org/opensearch/knn/index/codec/KNN10010Codec/KNN10010DerivedSourceStoredFieldsWriter.java:117]: nit: I know its just copied but everytime I look at it its confusing so just a suggestion

```suggestion
            fields.stream().collect(Collectors.toMap(field -> , field -> (Object vector) -> vector == null ? vector : MASK)),
```

**Review by Vikasht34 — APPROVED** [review]
