### PR TITLE
[Backport 2.x] Add support for search using the "fields" parameter with knn_vector field

### LINKED ISSUE #1633: [BUG] Indices that include knn_vector field fail when search includes "fields" parameter
## Description

Right now, for indices that contain a `knn_vector`, we are not able to support the `fields` option in queries. This is because in KNNVectorFieldType, we do not implement [ValuesFetcher](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java#L460). We should implement it similar to the [geo types](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/AbstractGeometryFieldMapper.java#L323-L343) that handle arrays directly.

```
curl -X GET "localhost:9200/target_index/_search?pretty" -H 'Content-Type: application/json' -d'
> {
>   "fields": ["*"],
>   "query": {
>     "match_all": {}
>   }
> }
> '

{
  "error" : {
    "root_cause" : [
      {
        "type" : "unsupported_operation_exception",
        "reason" : "KNN Vector do not support fields search"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "target_index",
        "node" : "grr7rDoPSwKXqQcpNrcbJQ",
        "reason" : {
          "type" : "unsupported_operation_exception",
          "reason" : "KNN Vector do not support fields search"
        }
      }
    ],
    "caused_by" : {
      "type" : "unsupported_operation_exception",
      "reason" : "KNN Vector do not support fields search",
      "caused_by" : {
        "type" : "unsupported_operation_exception",
        "reason" : "KNN Vector do not support fields search"
      }
    }
  },
  "status" : 500
}
```

## Repro steps
```
curl -X PUT "localhost:9200/target_index" -H 'Content-Type: application/json' -d'
{
  "settings" : {
    "number_of_shards" : 1,
    "number_of_replicas" : 0,
    "index.knn": true
  },
  "mappings": {
       "properties": {
       "target_field": {
           "type": "knn_vector",
           "dimension": 2,
           "method": {
               "name":"hnsw",
               "engine":"nmslib",
               "space_type": "l2",
               "parameters":{
                 "m":20,
                 "ef_construction": 23
               }
           }
      }
   }
  }
}
'

curl -X PUT "localhost:9200/_bulk" -H 'Content-Type: application/json' -d'
{ "index": { "_index": "target_index" } }
{ "target_field": [1.5, 5.5]}
{ "index": { "_index": "target_index" } }
{ "target_field": [2.5, 3.5]}
{ "index": { "_index": "target_index" } }
{ "target_field": [4.5, 5.5]}
{ "index": { "_index": "target_index" } }
{ "target_field": [1.5, 5.5]}
{ "index": { "_index": "target_index" } }
{ "target_field": [1.5, 5.5]}
{ "index": { "_index": "target_index" } }
{ "target_field": [2.5, 3.5]}
'


curl localhost:9200/target_index/_refresh?pretty
curl -X GET "localhost:9200/target_index/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "fields": ["*"],
  "query": {
    "match_all": {}
  }
}
'
```

### PR DESCRIPTION
**Pull request by e-emoto**
### Description
Backport of #2314 
Fix Sign-Off Issues/Test Failures in #2394 

This change implements valueFetcher in KNNVectorFieldType so search can support using the "fields" parameter when used with the knn_vector field type.  ITs for this change were added to OpenSearchIT after the change was tested manually.  

### Related Issues
Resolves #1633

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by jmazanec15 — APPROVED** [review]

File: qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java [hunk 1]
```diff
@@ -46,6 +46,7 @@ public void testKNNWarmupDefaultLegacyFieldMapping() throws Exception {
 
     // Custom Legacy Field Mapping
     // space_type : "innerproduct", engine : "nmslib", m : 2, ef_construction : 2
+    @AwaitsFix(bugUrl = "https://github.com/opensearch-project/k-NN/issues/2415")
     public void testKNNWarmupCustomLegacyFieldMapping() throws Exception {
```
Comment (kotwanikunal) [inline qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java:50]: I think you would have a conflict with this. This change is already merged in.

**Review by navneet1v — APPROVED** [review]

File: qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java (hunk 1 above)
Comment (navneet1v) [reply qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java:50]: somehow git is not thinking this as conflict.
