### PR TITLE
Fix bug when clearing models

### LINKED ISSUE #93: [faiss] bug in delete/update logic
In the delete/update logic, the model is removed from the cache on the node that is handling the delete/update. However, the model will not be removed from the other nodes' caches.

To fix this, we need to create a broadcast evict from model cache transport action to totally wipe the model from all caches.

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
This PR adds an action that tells nodes in the cluster to clears the model identified by model_id from their cache. If the model isnt present, nothing happens. 

The modelDao uses this action to clear the model from the caches during delete and update. Previously, the model was only removed from the cache on the node that was executing the delete request.
 
### Issues Resolved
#93 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/indices/ModelDao.java [hunk 1]
```diff
@@ -264,16 +267,38 @@ private void putInternal(@Nullable String modelId, Model model, ActionListener<I
...
-                    ModelCache.getInstance().remove(modelId);
-                    listener.onResponse(response);
-                }, listener::onFailure);
+                onMetaListener = ActionListener.wrap(indexResponse -> client.execute(
+                        RemoveModelFromCacheAction.INSTANCE,
+                        new RemoveModelFromCacheRequest(modelId),
+                        ActionListener.wrap(
+                                removeModelFromCacheResponse -> {
+
+                                    if (removeModelFromCacheResponse.hasFailures()) {
```
Comment (VijayanB) [inline src/main/java/org/opensearch/knn/indices/ModelDao.java:280]: Shall we flip if condition and return if no failure to improve readability?

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:280]: Make sense.

File: src/main/java/org/opensearch/knn/indices/ModelDao.java [hunk 2]
```diff
@@ -264,16 +267,38 @@ private void putInternal(@Nullable String modelId, Model model, ActionListener<I
...
+                                            stringBuilder
+                                                    .append("Node \"")
+                                                    .append(nodeException.nodeId())
+                                                    .append("\" ")
+                                                    .append(nodeException.getMessage())
+                                                    .append("; ");
+                                        }
+
+                                        listener.onFailure(new RuntimeException(stringBuilder.toString()));
+                                        return;
```
[the remark this answers is not in the document]
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:295]: I thought about this. I think some can be refactored. The major issue is that the response type of the listener are different. Ill pull out the error message construction.

**Review by VijayanB — APPROVED** [review]
