### PR TITLE
Fix setting rescore as false in on_disk knn_vector query

### LINKED ISSUE #2360: Setting rescore to false as search parameter is noop
## Description

For re-scoring, when the query parameter is set to false but the knn_vector field is configured to use on disk, re-scoring will still take place:
```
# Re-scoring will still happen for below query
GET my-knn-index-1/_search
{
  "query": {
    "knn": {
      "my_vector": {
        "vector": [ ],
        "k": 3,
        "rescore": false
      }
    }
  }
}
``` 

This is incorrect. When set to false, no re-scoring should happen. 

## Workaround

As a workaround, users can set the index setting `index.knn.disk.vector.shard_level_rescoring_disabled` to true. However, we should fix this so that the behavior properly works.

## Mitigation

The solution was added in the development branch for the disk based feature, but it appears to have gotten lost in shuffle of merging disk based from dev branch to 2.17. The main change will be in [KNNQueryBuilderParser](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java#L87-L92) and will look something like this:
```
-        internalParser.declareObjectOrDefault(
-            KNNQueryBuilder.Builder::rescoreContext,
-            (p, v) -> RescoreParser.fromXContent(p),
-            RescoreContext::getDefault,
-            RESCORE_FIELD
-        );
+        internalParser.declareField((p, v, c) -> {
+            BiConsumer<KNNQueryBuilder.Builder, RescoreContext> consumer = KNNQueryBuilder.Builder::rescoreContext;
+            BiFunction<XContentParser, Void, RescoreContext> objectParser = (_p, _v) -> RescoreParser.fromXContent(_p);
+            Supplier<RescoreContext> defaultValue = RescoreContext::getDefault;
+            if (p.currentToken() == XContentParser.Token.VALUE_BOOLEAN) {
+                if (p.booleanValue()) {
+                    consumer.accept(v, defaultValue.get());
+                } else {
+                    // If the user specifies false, I want to explicitly set to empty disabled so we dont
+                    // accidentally resolve.
+                    consumer.accept(v, EXPLICITLY_DISABLED_RESCORE_CONTEXT);
+                }
+            } else {
+                consumer.accept(v, objectParser.apply(p, c));
+            }
+        }, RESCORE_FIELD, ObjectParser.ValueType.OBJECT_OR_BOOLEAN);
```

This was similar to what we had done in development. See https://github.com/jmazanec15/k-NN-1/blob/6df6b0618db5124d5067eddcb0903aa50eb8194c/src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java#L89-L104 (And this thrown away PR: https://github.com/jmazanec15/k-NN-1/pull/1).

### PR DESCRIPTION
**Pull request by e-emoto**
### Description
This change adds a flag to RescoreContext for tracking if rescore has been disabled by the KNN query parameters.  This flag is set to not skip rescore by default, and is only set to skip rescore if `"rescore": false` is in the KNN query.  UTs were added for the KNNQueryBuilderParser that covers the different cases for rescore.  The below steps were also run with a debugging cluster to verify that the rescore was being run/skipped correctly based on the query parameters.  

#### Manual Testing Steps
```
curl -X PUT "localhost:9200/test_index" -H 'Content-Type: application/json' -d'
{
  "settings" : {
    "index": {
      "knn": true
    }
  },
  "mappings": {
    "properties": {
      "test_field1": {
        "type": "knn_vector",
        "dimension": 8,
        "space_type": "innerproduct",
        "data_type": "float",
        "mode": "on_disk",
        "compression_level": "16x"
      },"test_field2": {
        "type": "knn_vector",
        "dimension": 4,
        "space_type": "innerproduct",
        "data_type": "float",
        "mode": "on_disk",
        "compression_level": "16x"
      }
    }
  }
}
'

curl -X PUT "localhost:9200/_bulk" -H 'Content-Type: application/json' -d'
{ "index": { "_index": "test_index" } }
{ "test_field1": [1.5, 5.5, 3.5, 2.5, 5.5, 4.5, 7.5, 1.5], "test_field2": [1.5, 5.5, 3.5, 2.5]}
{ "index": { "_index": "test_index" } }
{ "test_field1": [2.5, 3.5, 7.5, 4.5, 1.5, 3.5, 5.5, 6.5], "test_field2": [2.5, 3.5, 7.5, 4.5]}
{ "index": { "_index": "test_index" } }
{ "test_field1": [4.5, 5.5, 1.5, 6.5, 3.5, 4.5, 2.5, 1.5], "test_field2": [4.5, 5.5, 1.5, 6.5]}
{ "index": { "_index": "test_index" } }
{ "test_field1": [1.5, 5.5, 2.5, 1.5, 3.5, 7.5, 5.5, 1.5], "test_field2": [1.5, 5.5, 2.5, 1.5]}
{ "index": { "_index": "test_index" } }
{ "test_field1": [1.5, 5.5, 4.5, 2.5, 3.5, 2.5, 6.5, 7.5], "test_field2": [1.5, 5.5, 4.5, 2.5]}
{ "index": { "_index": "test_index" } }
{ "test_field1": [2.5, 3.5, 5.5, 7.5, 1.5, 4.5, 3.5, 6.5], "test_field2": [2.5, 3.5, 5.5, 7.5]}
'
```
rescore skipped:
```
curl -X GET "localhost:9200/test_index/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "knn": {
      "test_field1": {
        "vector": [ 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0 ],
        "k": 3,
        "rescore": false
      }
    }
  }
}
'
```
rescore does happen:
```
curl -X GET "localhost:9200/test_index/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "knn": {
      "test_field2": {
        "vector": [ 4.0, 3.0, 2.0, 1.0 ],
        "k": 3
      }
    }
  }
}
'
```
rescore does happen:
```
curl -X GET "localhost:9200/test_index/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "query": {
    "knn": {
      "test_field1": {
        "vector": [ 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0 ],
        "k": 3,
        "rescore": {
            "oversample_factor": 2.5
        }
      }
    }
  }
}
'
```

### Related Issues
Resolves #2360 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java [hunk 1]
```diff
@@ -84,12 +88,22 @@ private static ObjectParser<KNNQueryBuilder.Builder, Void> createInternalObjectP
...
-        internalParser.declareObjectOrDefault(
-            KNNQueryBuilder.Builder::rescoreContext,
-            (p, v) -> RescoreParser.fromXContent(p),
-            RescoreContext::getDefault,
-            RESCORE_FIELD
-        );
+        internalParser.declareField((p, v, c) -> {
+            BiConsumer<KNNQueryBuilder.Builder, RescoreContext> consumer = KNNQueryBuilder.Builder::rescoreContext;
+            BiFunction<XContentParser, Void, RescoreContext> objectParser = (_p, _v) -> RescoreParser.fromXContent(_p);
+            Supplier<RescoreContext> defaultValue = RescoreContext::getDefault;
```
Comment (kotwanikunal) [inline src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java:94]: I do not see any version checks here for the new flag. `RescoreParser` has version based checks for streams - https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/parser/RescoreParser.java#L87-L109

Would this change break that assumption? Should we add in BwC tests?

Comment (e-emoto) [reply src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java:94]: Are you saying we need to check the version for the flag `rescoreDisabled` in `RescoreContext`?  I didn't see any version checks for the `userProvided` flag which is setup similarly, so I didn't think it needed it.

Comment (e-emoto) [reply src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java:94]: @jmazanec15 Do we need to run version based checks for flags that get added to `RescoreContext`?

File: src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java [hunk 2]
```diff
@@ -47,6 +47,18 @@ public final class RescoreContext {
     @Builder.Default
     private boolean userProvided = true;
 
+    /**
+     * Flag to track whether rescoring has been disabled by the query parameters.
+     */
+    @Builder.Default
+    private boolean rescoreDisabled = false;
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java:54]: nit: Lets switch to rescoreEnabled for readability?

File: src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java [hunk 3]
```diff
@@ -47,6 +47,18 @@ public final class RescoreContext {
...
+
+    // Rescore context to be used when rescoring should be explicitly disabled
+    public static final RescoreContext EXPLICITLY_DISABLED_RESCORE_CONTEXT = RescoreContext.builder()
+        .oversampleFactor(DEFAULT_OVERSAMPLE_FACTOR)
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/query/rescore/RescoreContext.java:58]: nit: Do we need to specify this?

File: src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java (hunk 1 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java:94]: For this, we are not changing the content that is being serialized and deserialized. Its more so how we are interpreting it. So I dont think we need to add BWC.

**Review by jmazanec15 — COMMENTED** [review]
Thanks @e-emoto. Lets add a test somewhere in https://github.com/opensearch-project/k-NN/tree/main/src/test/java/org/opensearch/knn/integ that confirms that it actually does end up disabling re-scoring. Confirm that it fails before and works after. 

These tests would provide a good template: https://github.com/opensearch-project/k-NN/blob/main/src/test/java/org/opensearch/knn/integ/ModeAndCompressionIT.java

**Review by kotwanikunal — APPROVED** [review]

**Review by jmazanec15 — APPROVED** [review]

**Review by jmazanec15 — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]
