### PR TITLE
[BUG FIX] Add space type default and ef search parameter in warmup

### LINKED ISSUE #255: [BUG] Upgrade from ES 7.x to OS 1.x leads to query failure
## Overview

In OpenSearch 1.0 release, we introduced KNNEngine, which contains metadata about the underlying library used for the particular field: https://github.com/opensearch-project/k-NN/pull/20. 

For a given field, we store the name of the engine in [Lucene's fieldType](https://github.com/opensearch-project/k-NN/blob/1.0/src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java#L358) as an attribute. This gets stored on a per segment basis. 

The problem is that when a customer upgrades from ES 7.x to OS 1.x, the fieldAttribute is not set in the segments created in ES 7.x. When a node running OpenSearch attempts to run a query on such a segment, the [engine name is null](https://github.com/opensearch-project/k-NN/blob/1.0/src/main/java/org/opensearch/knn/index/KNNWeight.java#L107) leading [to an exception](https://github.com/opensearch-project/k-NN/blob/1.0/src/main/java/org/opensearch/knn/index/util/KNNEngine.java#L54).

## Impact

Indices created in ES 7.x clusters may not be searchable in OS 1.x. 

[Upgrade tests were run](https://github.com/opensearch-project/k-NN/issues/17#issuecomment-863598982) for ES 7.x to OS 1.0, but it is unclear at the moment why this issue was not caught then. One potential reason is that forcemerging created new segments.

## Mitigation(s)

Reindex data from the indices created  in ES 7.x to new indices created in OpenSearch 1.x. This will build the segments with nmslib as the default engine. The same settings/mapping from the old index can be used for the new index:

```
PUT /new_index
{
  "settings": {
same as old_index
  },
  "mappings": {
same as old_index
    }
}
'

POST /_reindex
{
  "source": {
    "index": "old_index"
  },
  "dest": {
    "index": "new_index"
  }
}
```

## Patch

The fix is simple. If the fieldAttribute isnt found in [KNNWeight](https://github.com/opensearch-project/k-NN/blob/1.0/src/main/java/org/opensearch/knn/index/KNNWeight.java#L107), we should default to nmslib as the engine. We actually already do this in [KNN80DocValuesConsumer](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java#L112-L113). We will need to backport to 1.2, 1.1 and 1.0.

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Warmup is used to load native library files into memory so that there are no initial latency penalties during search. The load process for search and warmup are very similar. 

Currently, warmup api has a similar bug to #267. It does not default to a space type. For customers upgrading to 1.2 from ES 7.1 or 7.4 this will cause warmup failure. This only applies to 1.2. 1.1 and 1.0 do not have this bug in warmup.

Additionally, for nmslib, we allow the ef_search parameter to be set after indexing. To do this, we pass the parameter in during loading. In 1.2, we did not pass this parameter in. This will cause default ef_search to be used during warmup. To clean this up a bit, I abstracted generating load parameters into a utility function and used the same one for both search as well as warmup.
 
### Issues Resolved
#255 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/IndexUtil.java [hunk 1]
```diff
@@ -156,4 +161,26 @@ public static ValidationException validateKnnField(IndexMetadata indexMetadata,
...
+
+    /**
+     * Gets the load time parameters for a given engine.
+     *
+     * @param spaceType Space for this particular segment
+     * @param knnEngine Engine used for the native library indices being loaded in
+     * @param indexName Name of OpenSearch index that the segment files belong to
+     * @return load parameters that will be passed to the JNI.
+     */
+    public static Map<String, Object> getLoadParameters(SpaceType spaceType, KNNEngine knnEngine, String indexName) {
```
Comment (VijayanB) [inline src/main/java/org/opensearch/knn/index/IndexUtil.java:173]: may be: getParametersAtLoading ?

File: src/main/java/org/opensearch/knn/index/KNNIndexShard.java [hunk 2]
```diff
@@ -122,7 +122,8 @@ public void warmup() throws IOException {
 
             for (FieldInfo fieldInfo : reader.getFieldInfos()) {
                 if (fieldInfo.attributes().containsKey(KNNVectorFieldMapper.KNN_FIELD)) {
-                    SpaceType spaceType = SpaceType.getSpace(fieldInfo.attributes().get(SPACE_TYPE));
+                    String spaceTypeName = fieldInfo.attributes().getOrDefault(SPACE_TYPE, SpaceType.L2.getValue());
```
Comment (junqiu-lei) [inline src/main/java/org/opensearch/knn/index/KNNIndexShard.java:125]: How about to add a default value here to make more readable?
```suggestion
                    String spaceTypeDefaultVaule = SpaceType.L2.getValue();
                    String spaceTypeName = fieldInfo.attributes().getOrDefault(SPACE_TYPE, spaceTypeDefaultVaule);
```

File: src/main/java/org/opensearch/knn/index/IndexUtil.java [hunk 3]
```diff
@@ -156,4 +161,26 @@ public static ValidationException validateKnnField(IndexMetadata indexMetadata,
...
+        Map<String, Object> loadParameters = Maps.newHashMap(ImmutableMap.of(
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/knn/index/IndexUtil.java:174]: Are we going to mutate this map later? Seems that at the end we return mutable object from this method. 
```suggestion
        final Map<String, Object> loadParameters;
        if (KNNEngine.NMSLIB.equals(knnEngine)) {
              loadParameters = ImmutableMap.of(
                            SPACE_TYPE, spaceType.getValue(),
                            HNSW_ALGO_EF_SEARCH, KNNSettings.getEfSearchParam(indexName)
              );
        } else {
              loadParameters = ImmutableMap.of(SPACE_TYPE, spaceType.getValue());
        }
        return loadParameters;
```

File: src/main/java/org/opensearch/knn/index/IndexUtil.java (hunk 1 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/IndexUtil.java:173]: Makes sense. Will update.

File: src/main/java/org/opensearch/knn/index/KNNIndexShard.java (hunk 2 above)
Comment (martin-gaievski) [reply src/main/java/org/opensearch/knn/index/KNNIndexShard.java:125]: I would make default value a constant

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/KNNIndexShard.java:125]: That makes sense, I will update.

Comment (VijayanB) [reply src/main/java/org/opensearch/knn/index/KNNIndexShard.java:125]: Either way is fine, but i am leaning towards what you have :) since method itself gives the hint that it is get or Default :)

File: src/main/java/org/opensearch/knn/index/IndexUtil.java (hunk 3 above)
Comment (VijayanB) [reply src/main/java/org/opensearch/knn/index/IndexUtil.java:174]: or we can just return UnModifiableMap.

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/IndexUtil.java:174]: Prefer the unmodifiable map approach. Will go with that.

File: src/main/java/org/opensearch/knn/index/KNNIndexShard.java (hunk 2 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/KNNIndexShard.java:125]: Right, I think I will just keep what I have. So, we do have SpaceType.DEFAULT, but in this case I do not want to use that because I know for sure that this should be L2. I will update with a comment.

**Review by VijayanB — APPROVED** [review]
LGTM. Thanks!

**Review by martin-gaievski — APPROVED** [review]
