### PR TITLE
Change VectorReaderListener to expect number array

### LINKED ISSUE #415: [BUG] Unable to read integer arrays during training
**What is the bug?**
When a user ingests vectors that are composed of integers [1, 2, 3] (as opposed to floats [1.0, 2.0, 3.0]), the plugin internally will [convert them to floats](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNVectorFieldMapper.java#L414). However, when the vectors are returned in a search, the vector will be returned in the original way that it was ingested: [1, 2, 3]. This is because the value of the vector is fetched from the documents source (not docvalues that actually have the float arrays). This is not the problem.

The problem is that during [training when we get vectors from an index](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/training/VectorReader.java#L187) using the _search API and try to convert them to float arrays. In the logs, you will see something along the lines of:
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
        ...
	at org.opensearch.knn.training.VectorReader$VectorReaderListener.onResponse(VectorReader.java:170)
	at org.opensearch.knn.training.VectorReader$VectorReaderListener.onResponse(VectorReader.java:125)
```

The result will be that training will fail.

To fix this issue, we need to improve this code in the VectorReader to handle integer type arrays:
```
            for (int i = 0; i < vectorsToAdd; i++) {
                trainingData.add(
                    ((List<Double>) hits[i].getSourceAsMap().get(fieldName)).stream().map(Double::floatValue).toArray(Float[]::new)
                );
            }
```

**Proposed solutions**
@martin-gaievski suggested the following snippet:
```
trainingData.add(((List<Number>) m.get("fieldName")).stream()
        .map(Number::floatValue)
        .toArray(Float[]::new));
```

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Refactors VectorReaderListener onResponse to expect arrays of Number type from search result instead of Double type. This will allow the training to handle cases where the vectors source is stored as an integer array. Adds test case to confirm that it can handle Integer type. Cleans up tests in VectorReaderTest class. 

Credit to @martin-gaievski for the suggested fix.
 
### Issues Resolved
#415 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java [hunk 1]
```diff
@@ -66,59 +64,100 @@ public void testRead_valid_completeIndex() throws InterruptedException, Executio
...
+
+        // Create list of random vectors and ingest
+        Random random = new Random();
+        List<Integer[]> vectors = new ArrayList<>();
+        for (int i = 0; i < DEFAULT_NUM_VECTORS; i++) {
+            Integer[] vector = new Integer[DEFAULT_DIMENSION];
+
+            for (int j = 0; j < DEFAULT_DIMENSION; j++) {
+                vector[j] = random.nextInt();
+            }
```
Comment (martin-gaievski) [inline src/test/java/org/opensearch/knn/training/VectorReaderTests.java:100]: nit: you can do the same but with less code via streams:

`
Integer[] array = random.ints(size, lowBound, highBound).boxed().toArray(Integer[]::new);
`

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java [hunk 2]
```diff
@@ -66,59 +64,100 @@ public void testRead_valid_completeIndex() throws InterruptedException, Executio
...
         assertEquals(new HashSet<>(flatVectors), new HashSet<>(flatConsumedVectors));
     }
 
+    public void testRead_valid_trainVectorsIngestedAsIntegers() throws IOException, ExecutionException, InterruptedException {
+        createIndex(DEFAULT_INDEX_NAME);
+        createKnnIndexMapping(DEFAULT_INDEX_NAME, DEFAULT_FIELD_NAME, DEFAULT_DIMENSION);
+
+        // Create list of random vectors and ingest
+        Random random = new Random();
+        List<Integer[]> vectors = new ArrayList<>();
```
Comment (martin-gaievski) [inline src/test/java/org/opensearch/knn/training/VectorReaderTests.java:94]: Is it possible to have mix of lists of different types? If yes I think we need to have such test case with mixed docs.

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java [hunk 3]
```diff
@@ -32,32 +31,31 @@
...
 public class VectorReaderTests extends KNNSingleNodeTestCase {
 
-    public static Logger logger = LogManager.getLogger(VectorReaderTests.class);
+    private final int DEFAULT_LATCH_TIMEOUT = 100;
+    private final String DEFAULT_INDEX_NAME = "test-index";
+    private final String DEFAULT_FIELD_NAME = "test-field";
+    private final int DEFAULT_DIMENSION = 16;
+    private final int DEFAULT_NUM_VECTORS = 100;
+    private final int DEFAULT_MAX_VECTOR_COUNT = 10000;
+    private final int DEFAULT_SEARCH_SIZE = 10;
```
Comment (navneet1v) [inline src/test/java/org/opensearch/knn/training/VectorReaderTests.java:40]: any reason for not making them static?

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java (hunk 2 above)
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:94]: Oh interesting. Hadn't thought of that. I can add this case.

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java (hunk 1 above)
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:100]: Thanks will update

File: src/main/java/org/opensearch/knn/training/VectorReader.java [hunk 4]
```diff
@@ -184,7 +184,7 @@ public void onResponse(SearchResponse searchResponse) {
 
             for (int i = 0; i < vectorsToAdd; i++) {
                 trainingData.add(
-                    ((List<Double>) hits[i].getSourceAsMap().get(fieldName)).stream().map(Double::floatValue).toArray(Float[]::new)
+                    ((List<Number>) hits[i].getSourceAsMap().get(fieldName)).stream().map(Number::floatValue).toArray(Float[]::new)
```
[the remark this answers is not in the document]
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/training/VectorReader.java:187]: Sorry, what do you mean by this?

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java (hunk 3 above)
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:40]: Oh good question. Would it be better practice to do that?

Comment (navneet1v) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:40]: Yes its a better practice.

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java (hunk 2 above)
Comment (navneet1v) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:94]: Before adding the test case can you please validate do we even allow such kind of vectors as input?

Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:94]: Itd be like if someone indexed 2 docs, 1 with [1, 2, 3] and the other with [1.0, 2.0, 3.0]

File: src/main/java/org/opensearch/knn/training/VectorReader.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/training/VectorReader.java:187]: Hmm `hits[i].getSourceAsMap().get(fieldName)` will be a List of something that extends Number, but not necessarily Double. If we cast it as a List<Double> when it is a List<Integer> wont this cause an issue?

File: src/test/java/org/opensearch/knn/training/VectorReaderTests.java (hunk 2 above)
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/training/VectorReaderTests.java:94]: On second thought, I dont think this would need to be added. Given that we process each hit's vector separately, I dont see the need to add a case for when the hits have different representations.

File: src/main/java/org/opensearch/knn/training/VectorReader.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (martin-gaievski) [reply src/main/java/org/opensearch/knn/training/VectorReader.java:187]: Agree with Jack, this cast going to throw runtime classcast exception for list of Integer objects.
`(List<Double>) hits[i].getSourceAsMap().get(fieldName)`

**Review by martin-gaievski — APPROVED** [review]

File: src/main/java/org/opensearch/knn/training/VectorReader.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (navneet1v) [reply src/main/java/org/opensearch/knn/training/VectorReader.java:187]: ahh.. My mistake I read it like we are typecasting the final result to List of double. 

[nitpick]We could have done a better job in breaking this code to multiple lines for better understanding.

[the remark this answers is not in the document]
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/training/VectorReader.java:187]: Interesting, thats what I did originally, but `./gradlew spotlessApply` changed it back to a single line.

**Review by navneet1v — APPROVED** [review]
