### PR TITLE
[Backport 2.x] Fix setting rescore as false in on_disk knn_vector query

### LINKED ISSUE #2360: Setting rescore to false as search parameter is noop
## Description

For re-scoring, when the query parameter is set to false but the knn_vector field is configured to use on disk, re-scoring will still take place:
```
# Re-scoring will still happen for below query
GET my-knn-index-1/_search
{
  "query": {
    "knn": {
      "my_vector": {
        "vector": [ ],
        "k": 3,
        "rescore": false
      }
    }
  }
}
``` 

This is incorrect. When set to false, no re-scoring should happen. 

## Workaround

As a workaround, users can set the index setting `index.knn.disk.vector.shard_level_rescoring_disabled` to true. However, we should fix this so that the behavior properly works.

## Mitigation

The solution was added in the development branch for the disk based feature, but it appears to have gotten lost in shuffle of merging disk based from dev branch to 2.17. The main change will be in [KNNQueryBuilderParser](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java#L87-L92) and will look something like this:
```
-        internalParser.declareObjectOrDefault(
-            KNNQueryBuilder.Builder::rescoreContext,
-            (p, v) -> RescoreParser.fromXContent(p),
-            RescoreContext::getDefault,
-            RESCORE_FIELD
-        );
+        internalParser.declareField((p, v, c) -> {
+            BiConsumer<KNNQueryBuilder.Builder, RescoreContext> consumer = KNNQueryBuilder.Builder::rescoreContext;
+            BiFunction<XContentParser, Void, RescoreContext> objectParser = (_p, _v) -> RescoreParser.fromXContent(_p);
+            Supplier<RescoreContext> defaultValue = RescoreContext::getDefault;
+            if (p.currentToken() == XContentParser.Token.VALUE_BOOLEAN) {
+                if (p.booleanValue()) {
+                    consumer.accept(v, defaultValue.get());
+                } else {
+                    // If the user specifies false, I want to explicitly set to empty disabled so we dont
+                    // accidentally resolve.
+                    consumer.accept(v, EXPLICITLY_DISABLED_RESCORE_CONTEXT);
+                }
+            } else {
+                consumer.accept(v, objectParser.apply(p, c));
+            }
+        }, RESCORE_FIELD, ObjectParser.ValueType.OBJECT_OR_BOOLEAN);
```

This was similar to what we had done in development. See https://github.com/jmazanec15/k-NN-1/blob/6df6b0618db5124d5067eddcb0903aa50eb8194c/src/main/java/org/opensearch/knn/index/query/parser/KNNQueryBuilderParser.java#L89-L104 (And this thrown away PR: https://github.com/jmazanec15/k-NN-1/pull/1).

### PR DESCRIPTION
**Pull request by e-emoto**
### Description
Backport of #2399 
Skip Flaky BWC in #2417 

This change adds a flag to RescoreContext for tracking if rescore has been disabled by the KNN query parameters. This flag is set to not skip rescore by default, and is only set to skip rescore if `"rescore": false` is in the KNN query. UTs were added for the KNNQueryBuilderParser that covers the different cases for rescore. The below steps were also run with a debugging cluster to verify that the rescore was being run/skipped correctly based on the query parameters.

### Related Issues
Resolves #2360 

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java [hunk 1]
```diff
@@ -46,6 +46,7 @@ public void testKNNWarmupDefaultLegacyFieldMapping() throws Exception {
 
     // Custom Legacy Field Mapping
     // space_type : "innerproduct", engine : "nmslib", m : 2, ef_construction : 2
+    @AwaitsFix(bugUrl = "https://github.com/opensearch-project/k-NN/issues/2415")
```
Comment (kotwanikunal) [inline qa/restart-upgrade/src/test/java/org/opensearch/knn/bwc/WarmupIT.java:49]: I think you would have a conflict with this. This change is already merged in to `2.x`

**Review by navneet1v — APPROVED** [review]

**Review by kotwanikunal — APPROVED** [review]
