### PR TITLE
Fix score conversion logic for filtered radial exact search

### LINKED ISSUE #3099: [BUG] min_score Threshold Ignored with FAISS Efficient Filtering
**What is the bug?**
When using FAISS engine with radial search (`min_score`) and efficient filtering (filter inside knn query), OpenSearch returns results with scores **below** the specified `min_score` threshold. The threshold is correctly enforced when no filter is applied or when using post-filtering.

**How can one reproduce the bug?**
Step 1: Create index with FAISS engine

```bash
PUT /test-faiss-bug
{
  "settings": {
    "index": {
      "knn": true
    }
  },
  "mappings": {
    "properties": {
      "embedding": {
        "type": "knn_vector",
        "dimension": 768,
        "method": {
          "name": "hnsw",
          "engine": "faiss",
          "space_type": "cosinesimil",
          "parameters": {
            "ef_construction": 100,
            "m": 16
          }
        }
      },
      "category": {
        "type": "keyword"
      }
    }
  }
}
```

Step 2: Index sample documents

```bash
# Index 20 documents with similar vectors in category "electronics"
POST /test-faiss-bug/_doc/1
{
  "embedding": [0.1, 0.2, ..., 0.5],  # 768-dimensional vector
  "category": "electronics"
}

# Repeat for documents 2-20 with slightly varied vectors
```

Step 3: Query with min_score and efficient filtering

```bash
POST /test-faiss-bug/_search
{
  "size": 100,
  "query": {
    "knn": {
      "embedding": {
        "vector": [0.1, 0.2, ..., 0.5],
        "min_score": 0.935,
        "filter": {
          "term": {
            "category": "electronics"
          }
        }
      }
    }
  }
}
```

Step 4: Observe incorrect results

Response contains documents with `_score` values **below 0.935** (e.g., 0.934, 0.918, 0.900).

**What is the expected behavior?**
**Expected**: All returned documents should have `_score >= 0.935`

**Actual**: Documents with scores below 0.935 are returned when efficient filtering is used

**What is your host/environment?**
- **OS**: AL2023
- **OpenSearch Version**: 3.1.0
- **Engine**: FAISS

**Do you have any additional context?**
Current workaround: Use post-filtering
```json
{
  "query": {
    "bool": {
      "must": [
        {
          "knn": {
            "embedding": {
              "vector": [...],
              "min_score": 0.935
            }
          }
        }
      ],
      "filter": [
        { "term": { "category": "electronics" } }
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by kotwanikunal**
### Description
- Fixes score translation logic for exact radial search with cosine space type

### Related Issues
Resolves #3099 

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/query/exactsearch/ExactSearcher.java [hunk 1]
```diff
@@ -104,9 +104,9 @@ private TopDocs doRadialSearch(LeafReaderContext leafReaderContext, ExactSearche
         // We need to use the given radius when memory optimized search is enabled. Since it relies on Lucene's scoring framework, the given
         // max distance is already converted min score then saved in `radius`. Thus, we don't need a score translation which does not make
         // sense as it is treating min score as a max distance otherwise.
-        final float minScore = context.isMemoryOptimizedSearchEnabled
-            ? context.getRadius()
-            : spaceType.scoreTranslation(context.getRadius());
+        // For FAISS exact search, radius is in FAISS distance space (e.g., inner product for cosine).
+        // We need to convert it to OpenSearch score space using the reverse translation.
+        final float minScore = context.isMemoryOptimizedSearchEnabled ? context.getRadius() : engine.score(context.getRadius(), spaceType);
```
Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/query/exactsearch/ExactSearcher.java:109]: Curious : Same Problem could also happen with MemoryOptimized Search as well , or it's like score calaulation is differnt?

**Review by Vikasht34 — COMMENTED** [review]
Overall Looks Good , Some. Clarification Question

File: src/main/java/org/opensearch/knn/index/query/exactsearch/ExactSearcher.java (hunk 1 above)
Comment (VijayanB) [reply src/main/java/org/opensearch/knn/index/query/exactsearch/ExactSearcher.java:109]: Can we also make sure we have IT for MOS if it is not already there?

File: src/test/java/org/opensearch/knn/index/FaissIT.java [hunk 2]
```diff
@@ -236,6 +236,83 @@ public void testEndToEnd_whenDoRadiusSearch_whenScoreThreshold_whenMethodIsHNSWF
...
+            new float[][] { queryVector },
+            null,
+            minScore,
+            spaceType,
+            filterQuery,
+            null
+        );
+
+        for (KNNResult result : results.get(0)) {
+            assertTrue(String.format("Score %.4f below threshold %.3f", result.getScore(), minScore), result.getScore() >= minScore);
```
Comment (shatejas) [inline src/test/java/org/opensearch/knn/index/FaissIT.java:310]: Ideally we want to be at a place where we match the exact scores with an error factor

File: src/main/java/org/opensearch/knn/index/query/exactsearch/ExactSearcher.java (hunk 1 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/query/exactsearch/ExactSearcher.java:109]: MOS does not need this fix as it has a separate score calculation flow. 

References:
- https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/query/KNNQueryBuilder.java#L516-L521
- MOS then uses - https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/engine/KNNEngine.java#L199-L201
but Native uses https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/engine/faiss/Faiss.java#L111-L117
- MOS stays in the score space vs Native needs to be converted from radial distance to score - leading to the bug

I'll add in a test for MOS as a followup

File: src/test/java/org/opensearch/knn/index/FaissIT.java (hunk 2 above)
Comment (kotwanikunal) [reply src/test/java/org/opensearch/knn/index/FaissIT.java:310]: I'll update the test with the MOS follow up.
