### PR TITLE
Fix KNNCodecUtil FieldInfo construction

### LINKED ISSUE #570: KNNCodecTestUtil broken due to fieldInfo constructor
https://github.com/opensearch-project/k-NN/actions/runs/3192735420/jobs/5210547276

```
> Task :compileTestJava
/home/runner/work/k-NN/k-NN/src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java:167: error: constructor FieldInfo in class FieldInfo cannot be applied to given types;
            return new FieldInfo(
                   ^
  required: String,int,boolean,boolean,boolean,IndexOptions,DocValuesType,long,Map<String,String>,int,int,int,int,VectorEncoding,VectorSimilarityFunction,boolean
  found: String,int,boolean,boolean,boolean,IndexOptions,DocValuesType,long,Map<String,String>,int,int,int,int,VectorSimilarityFunction,boolean
  reason: actual and formal argument lists differ in length
```

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Fixes constructor for FieldInfo, which changed with Lucene upgrade.

### Issues Resolved
#570 
 
### Check List
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java [hunk 1]
```diff
@@ -178,6 +179,7 @@ public FieldInfo build() {
                 pointIndexDimensionCount,
                 pointNumBytes,
                 vectorDimension,
+                VectorEncoding.FLOAT32,
```
Comment (martin-gaievski) [inline src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java:182]: Why we choose FLOAT32 over other value (I think it's BYTE)?

Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/index/codec/KNNCodecTestUtil.java:182]: Right now, we only support FLOAT32 - so I figured there was no sense in making it BYTE.

**Review by VijayanB — APPROVED** [review]
