### PR TITLE
Fix AVX2 detection on other platforms

### LINKED ISSUE #2788: [BUG] Non-Windows, non-Mac OS, non-Linux case is not considered in PlatformUtils leading to uncaught exception
**What is the bug?**
`org.opensearch.knn.jni.PlatformUtils.isAVX2Supported()` returns `null` when it is expected to be `boolean`. This may result in performance degradation or unavailability of the plug-in — I did not have time to investigate.

**How can one reproduce the bug?**
1. Install OpenSearch on FreeBSD from either binary packages or ports
2. Start OpenSearch
3. See uncaught exception in the console output.

**What is the expected behavior?**
OpenSearch should start silently.

**What is your host/environment?**
 - OS: FreeBSD
 - Version: 14.0-RELEASE
 - Plugins: N/A

**Do you have any screenshots?**
No screenshots; console output:
```
uncaught exception in thread [ForkJoinPool.commonPool-worker-1]
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "org.opensearch.knn.jni.Platfor
mUtils.isAVX2Supported" is null
        at org.opensearch.knn.jni.PlatformUtils.isAVX2SupportedBySystem(PlatformUtils.java:98)
        at org.opensearch.knn.plugin.KNNPlugin.lambda$static$0(KNNPlugin.java:183)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Do you have any additional context?**
isAVX2Supported() ignores Platforms other than Windows, Mac OS, and Linux, resulting in a null in the return value.

### PR DESCRIPTION
**Pull request by naveentatikonda**
### Description
Fix NPE while detecting AVX2 on other platforms(other than Linux, Mac and Windows)
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "org.opensearch.knn.jni.Platfor
mUtils.isAVX2Supported" is null
        at org.opensearch.knn.jni.PlatformUtils.isAVX2SupportedBySystem(PlatformUtils.java:98)
        at org.opensearch.knn.plugin.KNNPlugin.lambda$static$0(KNNPlugin.java:183)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

### Related Issues
Resolves #2788 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by 0ctopus13prime — APPROVED** [review]

File: src/main/java/org/opensearch/knn/jni/PlatformUtils.java [hunk 1]
```diff
@@ -50,14 +50,14 @@ static void reset() {
...
-        if (!Platform.isIntel() || Platform.isWindows()) {
-            isAVX2Supported = false;
-        }
-
         if (isAVX2Supported != null) {
             return isAVX2Supported;
         }
 
+        if (!Platform.isIntel() || Platform.isWindows()) {
+            return isAVX2Supported = false;
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/jni/PlatformUtils.java:58]: how does this solves the NPE? is it like on windows even when user has disabled the AVX2 we were still checking `isIntel || isWindows()` ?

Comment (naveentatikonda) [reply src/main/java/org/opensearch/knn/jni/PlatformUtils.java:58]: This is just to terminate and return early. This is the detection logic which will check if user has enabled or disabled AVX2 based on OS.

NPE is happening when it is ran on some other platform like FreeBSD other than linux, windows and mac because the default value of `isAVX2Supported` is `null`. So, we are fixing it here by returning false if it is still null

**Review by Vikasht34 — APPROVED** [review]
