### PR TITLE
Regex for derived source support

### LINKED ISSUE #3029: [BUG] Derived Source Regex Bug
**What is the bug?**
Currently, when passing includes and excludes in queries, derived source only recognizes full names, and doesn't resolve regex. Additionally, if a vector fields are partially excluded, and some are included, then it will go through the derived path for all vector fields, and will only get excluded from the source at the core level, which is inefficient. 

It will make no difference for the end output in either case, but this is not correct behavior, and can be optimized here.

**How can one reproduce the bug?**
This bug has no effect on output, but it leads to unnecessary work being done. 
To reproduce:
1. Create an index with 2 knn fields. 
2. Index one document.
3. Fire a query with excluded wildcard that should exclude both, set breakpoint inside ShouldInject function in DerivedSourceVectorTransformaer.java. It will not properly exclude. 

**What is the expected behavior?**
The regex should be evaluated and exclude properly, and excluded fields, even when partially excluded, should not trigger the derived flow for that field.

### PR DESCRIPTION
**Pull request by buddharajusahil**
### Description
Add regex support to derived source transformer exclusion. Also avoid applying derived source path on excluded or non included fields:

https://github.com/opensearch-project/k-NN/issues/3029

### Related Issues
Resolves #3029 

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java [hunk 1]
```diff
@@ -55,12 +57,75 @@ public DerivedSourceVectorTransformer(
...
     }
 
+    /**
+     * Initialize the transformer with the fields that should be injected based on includes/excludes.
+     * This filters perFieldDerivedVectorTransformers and builds the derivedSourceVectorTransformer.
+     * Should be called once before the first call to injectVectors().
+     *
+     * @param excludes List of field patterns that should not be injected
+     */
+    public void initialize(String[] includes, String[] excludes) {
```
Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:70]: Earlier change was not using regex pattern and was using excat , Since we started using Regex , and If customer is let's say happeing patern like _source: { excludes: ["test_vector_*"] } , regex can be costly  since this would be running per doc,  we should improve this to run pattern matching only once per filepath.

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:70]: This won't happen on a per document basis, the includes excludes should be resolved in the DerivedSourceVectorTransformer at the first time document is called. Any document call after this will not go down this initialize path.

Comment (Vikasht34) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:70]: You are right , I saw the code in Reader. Make Sense.

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java [hunk 2]
```diff
@@ -55,12 +57,75 @@ public DerivedSourceVectorTransformer(
...
+        derivedSourceVectorTransformer = XContentMapValues.transform(transformerFunctions, true);
+
+    }
+
+    private Set<String> getFieldsToExclude(String[] includes, String[] excludes) {
+        Set<String> fieldsToRemove = new HashSet<>();
+        Set<String> allFields = perFieldDerivedVectorTransformers.keySet();
+
+        // If includes are specified, start by excluding everything that doesn't match
+        if (includes != null && includes != Strings.EMPTY_ARRAY) {
```
Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java]: This check is not correct , **includes != Strings.EMPTY_ARRAY** checks object identity, not whether the array is empty. 

try this 
```
String[] a = new String[0];
String[] b = new String[0];

a == b                 
a == Strings.EMPTY_ARRAY 

it comes as false, 
```

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java [hunk 3]
```diff
@@ -55,12 +57,75 @@ public DerivedSourceVectorTransformer(
...
+            for (String fieldName : allFields) {
```
Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: Below two loops are duplicating the work , We don't need two pass for all the fields , 

Right now for everyfeild we do this 

First loop:
- Run simpleMatch() against every include pattern

Second loop:
- Run simpleMatch() against every exclude pattern.

if Field is already included why we need to run the Second Loop against all exclue pattern again for the same feild.

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java (hunk 2 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java]: Makes sense, will update in next revision

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java (hunk 3 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: So the behavior for source includes and excludes from my understanding is this:

First pass through the includes to figure out what fields to include in source. If any fields are explicitly included, then fields that are not explicitly included are practically excluded. This is what the first loop does.

Then it passes through the excluded fields to exclude from the remaining fields that were initially included from the included field.

For example a query like this:
```
{
  "query": { "match_all": {} },
  "_source": {
    "includes": ["t*"],
    "excludes": ["test"]
  }
}'
```
will include all fields that match the t* regex, but then exclude the test field, so the output source won't have the "test" field.

Comment (Vikasht34) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: My understanding was if field was not in Include that means it's already excluded then why we need to run second loop again on that field.  Includes act as a whitelist. Excludes only apply to fields that survive the include gate

so I have test, temp, and user as feilds.
Since we are lopping for all fields , why I need to do Regex Matching for user field on second loop , Since I know it's not in include and already excluded. 

Example 

```
"_source": {
  "includes": ["t*"],
  "excludes": ["test"]
}
``` 

@navneet1v What do u think?

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java (hunk 2 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java]: This makes sense, will change in next revision.

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java (hunk 3 above)
Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: Oh, I think I misunderstood your first comment. Yea, I think this makes sense, if a field is already not in includes and includes is explicitly defined, then we do not need to go through the excludes logic for that field.

**Review by Vikasht34 — APPROVED** [review]
Thanks for Addressing the Comments , Looks Good to Me !!

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java (hunk 3 above)
Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: @buddharajusahil or @Vikasht34 did any one of you checked the code of the SourceFieldMapper in the OpenSeach core to confirm the behavior?

Comment (Vikasht34) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: I looked at this https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java , 

```
final boolean filtered = CollectionUtils.isEmpty(includes) == false || CollectionUtils.isEmpty(excludes) == false;
this.filter = enabled && filtered ? XContentMapValues.filter(includes, excludes, true) : null;

```

So:

- if includes or excludes is set and _source is enabled → filter becomes a function that will filter a JSON map.

- otherwise filter == null


They behave like:

- includes is a whitelist gate: if includes is present, fields not matching it are effectively dropped.

- excludes is applied after that: it removes fields from whatever survived the include step.

Let me know if this is what I am geting

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: Here is the filtering logic used in XContentMapValues.java:
```
    private static Function<Map<String, ?>, Map<String, Object>> createSetBasedFilter(
        String[] includes,
        String[] excludes,
        boolean caseSensitive
    ) {
        Set<String> includeSet = (includes == null || includes.length == 0) ? null : toSet(includes, caseSensitive);
        Set<String> excludeSet = (excludes == null || excludes.length == 0) ? Collections.emptySet() : toSet(excludes, caseSensitive);

        return (map) -> {
            Map<String, Object> filtered = new HashMap<>();
            for (Map.Entry<String, ?> entry : map.entrySet()) {
                String key = entry.getKey();
                int dotPos = key.indexOf('.');
                if (dotPos > 0) {
                    key = key.substring(0, dotPos);
                }
                String k = caseSensitive ? key : key.toLowerCase(Locale.ROOT);
                if ((includeSet == null || includeSet.contains(k)) && !excludeSet.contains(k)) {
                    filtered.put(entry.getKey(), entry.getValue());
                }
            }
            return filtered;
        };
    }
```
    
In particular  :  if ((includeSet == null || includeSet.contains(k)) && !excludeSet.contains(k)) {

Based on this logic it first checks if a field is included, whether excplicitly or because includes is null, then it checks if excludes contains this field. So the behavior should match here. 

Have also manually tested these cases with text fields to confirm this behavior.

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: > Have also manually tested these cases with text fields to confirm this behavior.

Would it be good to have UTs and ITs for this change? WDYT?

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: > They behave like:
> 
> * includes is a whitelist gate: if includes is present, fields not matching it are effectively dropped.
> * excludes is applied after that: it removes fields from whatever survived the include step.
> 
> Let me know if this is what I am geting

Based on the code read and attached links I also feel this is what is happening.

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:89]: I have added IT's covering all combinations of includes excludes scenarios, but will also add UT's for the specific includes / excludes function.

File: src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java [hunk 4]
```diff
@@ -55,12 +56,78 @@ public DerivedSourceVectorTransformer(
...
     }
 
+    /**
+     * Initialize the transformer with the fields that should be injected based on includes/excludes.
+     * This filters perFieldDerivedVectorTransformers and builds the derivedSourceVectorTransformer.
+     * Should be called once before the first call to injectVectors().
+     *
+     * @param excludes List of field patterns that should not be injected
+     */
+    public void initialize(String[] includes, String[] excludes) {
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:70]: @buddharajusahil this can be basic question but want to make sure that we have covered it. Will this initialize function will look at the fields? or we are just going to include/exclude the vector fields? Because in this PR I am not able to find how we are making sure that we are apply this transformer for vector fields only. Is that logic present somewhere else?

Comment (buddharajusahil) [reply src/main/java/org/opensearch/knn/index/codec/derivedsource/DerivedSourceVectorTransformer.java:70]: So this initialize function's includes and excludes parameter will contain all included and excluded fields, regardless of field type. However, initialize then calls getFieldsToExclude:

```
private Set<String> getFieldsToExclude(String[] includes, String[] excludes) {
        Set<String> fieldsToRemove = new HashSet<>();
        Set<String> allFields = perFieldDerivedVectorTransformers.keySet();
```

which sets allFields to perFieldDerivedVectorTransformers.keySet();. This keyset will only contain the vector fields that we need to apply derived source transformation for, this vector field filtering logic was in KNN9120DerivedSourceStoredFieldsFormat.fieldsReader function. So it will go through the fields from this keyset and apply the includes and excludes filter. 

Short answer: No this filtering will only be applied to vector fields, which we filtered out in KNN9120DerivedSourceStoredFieldsFormat.fieldsReader.

**Review by navneet1v — APPROVED** [review]
