### PR TITLE
Fix derived source IT to handle field in both include and exclude

### LINKED ISSUE #3279: [Derived Source IT fix] Fix the Derived Source IT so that it works with latest changes in core
### Description

[DerivedSourceIT](https://github.com/opensearch-project/k-NN/blame/9332fbc5911335814b53de846fd279886cd7ed17/src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java#L417) currently checks if a field is included and excluded from source, the excluded field takes precedence: 

https://github.com/opensearch-project/k-NN/blame/9332fbc5911335814b53de846fd279886cd7ed17/src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java#L493

However, there was a recent change in OpenSearch core that changed this logic: https://github.com/opensearch-project/OpenSearch/pull/21203. Now, an `IllegalArgumentException` is thrown when specifying a field in both includes and excludes. A recent CI run on a PR tried to run the Derived Source IT, but failed: https://github.com/opensearch-project/k-NN/actions/runs/24468616146/job/71502586037?pr=3270. Here are the relevant error logs:

```
Suite: Test class org.opensearch.knn.integ.DerivedSourceIT
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests 'org.opensearch.knn.integ.DerivedSourceIT.testSourceFiltering_withVariousIncludeExcludeCombinations' -Dtests.seed=7AD9A17682DA4E0E -Dtests.security.manager=false -Dtests.locale=ar-001 -Dtests.timezone=America/Bahia_Banderas -Druntime.java=25
  2> org.opensearch.client.ResponseException: method [POST], host [http://127.0.0.1:34293/], URI [/source-filtering-combinationstestsourcefiltering_withvariousincludeexcludecombinations/_search], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The same entry [temp_vector] cannot be both included and excluded in _source."}],"type":"illegal_argument_exception","reason":"The same entry [temp_vector] cannot be both included and excluded in _source."},"status":400}
        at __randomizedtesting.SeedInfo.seed([7AD9A17682DA4E0E:D6A2B6D9BE7CF14E]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:494)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:383)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:358)
        at app//org.opensearch.knn.DerivedSourceTestCase.assertSourceFiltering(DerivedSourceTestCase.java:1213)
        at app//org.opensearch.knn.integ.DerivedSourceIT.testSourceFiltering_withVariousIncludeExcludeCombinations(DerivedSourceIT.java:493)
  2> NOTE: leaving temporary files on disk at: /__w/k-NN/k-NN/build/testrun/integTest/temp/org.opensearch.knn.integ.DerivedSourceIT_7AD9A17682DA4E0E-001
  2> NOTE: test params are: codec=Asserting(Lucene104): {}, docValues:{}, maxPointsInLeafNode=1511, maxMBSortInHeap=7.187965574445185, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=ar-001, timezone=America/Bahia_Banderas
  2> NOTE: Linux 6.17.0-1010-azure amd64/Eclipse Adoptium 25.0.2 (64-bit)/cpus=4,threads=1,free=269675680,total=536870912
  2> NOTE: All tests run in this JVM: [ADCIT, AdvancedFilteringUseCasesIT, DefaultKNNIndexSettingsIT, ExplainIT, FaissHNSWFlatE2EIT, FaissIT, KNNCircuitBreakerIT, KNNESSettingsTestIT, KNNMapperSearcherIT, LuceneEngineIT, LuceneSQFlatIT, MinScoreIT, OpenSearchIT, RandomRotationIT, RestoreSnapshotIT, SegmentReplicationIT, VectorDataTypeIT, InvalidSearchQueryIT, BinaryIndexIT, BinaryIndexInvalidMappingIT, DerivedSourceIT]
```

The integration test needs to be fixed to align with this change in core.

### PR DESCRIPTION
**Pull request by rchitale7**
### Description
With the recent change in OpenSearch Core: https://github.com/opensearch-project/OpenSearch/pull/21203, when a field is in both `includes` and `excludes`, then an exception is thrown. `DerivedSourceIT` assumed that `excludes` would take precedence over `includes`, so it needed to be fixed to align with core. 

Tested locally with `./gradlew --refresh-dependencies integTest --tests "org.opensearch.knn.integ.DerivedSourceIT"`, verified it worked. 

### Related Issues
Resolves #3279 

### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented. N/A
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md). N/A
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java [hunk 1]
```diff
@@ -489,14 +490,18 @@ public void testSourceFiltering_withVariousIncludeExcludeCombinations() {
...
-        assertSourceFiltering(
-            indexName,
-            new String[] { VECTOR_FIELD_1, VECTOR_FIELD_2, TEXT_FIELD },
-            new String[] { VECTOR_FIELD_2 },
-            new String[] { VECTOR_FIELD_1, TEXT_FIELD },
-            new String[] { VECTOR_FIELD_2, VECTOR_FIELD_3 }
+        // Test 4: Both includes and excludes - throws IllegalArgumentException because vector field cannot be in both includes and excludes
+        ResponseException ex = expectThrows(
+            ResponseException.class,
+            () -> assertSourceFiltering(
```
Comment (reta) [inline src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java]: @rchitale7 I would suggest to consider minor refactoring to introduce non-asserting `sourceFiltering` method, something along these lines:

```suggestion
            () -> sourceFiltering(
                indexName,
                new String[] { VECTOR_FIELD_1, VECTOR_FIELD_2, TEXT_FIELD },
                new String[] { VECTOR_FIELD_2 }
            )
```

We have also run into this issue in `opensearch-jvector` plugin: https://github.com/opensearch-project/opensearch-jvector/pull/409

File: src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java [hunk 2]
```diff
@@ -489,14 +490,18 @@ public void testSourceFiltering_withVariousIncludeExcludeCombinations() {
...
+                indexName,
+                new String[] { VECTOR_FIELD_1, VECTOR_FIELD_2, TEXT_FIELD },
+                new String[] { VECTOR_FIELD_2 },
+                new String[] { VECTOR_FIELD_1, TEXT_FIELD },
+                new String[] { VECTOR_FIELD_2, VECTOR_FIELD_3 }
+            )
         );
+        assertTrue(EntityUtils.toString(ex.getResponse().getEntity()).contains("cannot be both included and excluded in _source"));
```
Comment (reta) [inline src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java]: The `ResponseException` already contains entity as a string:
 
```
 assertThat(ex.getMessage(), containsString("The same entry [" + VECTOR_FIELD_2 + "] cannot be both included and excluded in _source."));
```

File: src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java (hunk 1 above)
Comment (rchitale7) [reply src/test/java/org/opensearch/knn/integ/DerivedSourceIT.java]: sure, will make this change

**Review by reta — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]

**Review by kotwanikunal — APPROVED** [review]

File: src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java [hunk 3]
```diff
@@ -1190,13 +1190,7 @@ protected void validateDerivedSetting(String indexName, boolean expectedValue) t
...
 
     @SneakyThrows
-    protected void assertSourceFiltering(
-        String indexName,
-        String[] includes,
-        String[] excludes,
-        String[] expectedPresent,
-        String[] expectedAbsent
-    ) {
+    protected Response sourceFiltering(String indexName, String[] includes, String[] excludes) {
```
Comment (0ctopus13prime) [inline src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java:1193]: NIT : Could you give a better name on the method? 😅 
It looks like doing search with include and exclude, but it took me quite a while to understand what it has a thing to do with sourceFiltering haha

Comment (rchitale7) [reply src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java:1193]: ya i can change to `searchWithSourceIncludesExcludes`. I'll do this in another PR i have open: https://github.com/opensearch-project/k-NN/pull/3270.

**Review by VijayanB — APPROVED** [review]

File: src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java (hunk 3 above)
Comment (0ctopus13prime) [reply src/testFixtures/java/org/opensearch/knn/DerivedSourceTestCase.java:1193]: thank you
