### PR TITLE
Include Model Index status as part of Stats API

### LINKED ISSUE #151: Add stats for faiss feature
For the faiss feature, we need to add stats to the stats API. This addition should not break any backwards compatibility. The proposed additional stats will be:

**Node Stats**
1. training.requests: number of training requests
2. training.errors: number of training request errors
3. training.memory_usage: memory usage used by training in kb
4. training.memory_usage_percentage: memory usage used by training as percentage
5. training.jobs: job level training stats
6. model.indexing_degraded: whether indexing from models is degraded. This is true when the model cache is experiencing capacity misses
7. engine.faiss_in_use: Whether faiss is in use on the node in the last 12 hours
8. engine.nmslib_in_use: Whether nmslib is in use on the node in the last 12 hours

**Cluster Stats**
1. model.index_status: k-NN model index status

The API response will look like:
```
{
    "_nodes" : {
        "total" : 1,
        "successful" : 1,
        "failed" : 0
    },
    "cluster_name" : "_run",
    "circuit_breaker_triggered" : false,
    
    "model": {
       "index_status": "green|yellow|red|non-existant",
    },
    
    "nodes" : {
        "HYMrXXsBSamUkcAjhjeN0w" : {
            "cache_capacity_reached" : false,
            "eviction_count" : 0,
            "hit_count" : 0,
            "miss_count" : 1,
            "knn_query_requests" : 4,
            "graph_memory_usage" : 1,
            "graph_memory_usage_percentage" : 3.68,
            "graph_index_requests" : 7,
            "graph_index_errors" : 1,
            "graph_query_requests" : 30,
            "graph_query_errors" : 15,
            "indices_in_cache" : {
                "myindex" : {
                    "graph_memory_usage" : 2,
                    "graph_memory_usage_percentage" : 3.68,
                    "graph_count" : 2
                }
            },
            
            "training": {
                "requests": X,
                "errors": X,
                "memory_usage" : 2,
                "memory_usage_percentage" : 3.68
                "jobs": {
                    "my_model_id" : {
                        "memory_usage" : 2,
                        "memory_usage_percentage" : 3.68
                    }
                },
             },
            "model": {
                "indexing_degraded": true,
            },
            "engine": {
                "nmslib_in_use": false,
                "faiss_in_use": true,
            },

            "load_exception_count" : 0,
            "load_success_count" : 1,
            "total_load_time" : 2878745,
            "script_compilations" : 1,
            "script_compilation_errors" : 0,
            "script_query_requests" : 534,
            "script_query_errors" : 0
        }
    }
}
```

### PR DESCRIPTION
**Pull request by VijayanB**
### Description
Add Model Index Status to Stats API.
1. if model index is not created, value will be null,
2. if model index exists, return index health status as model index status.
 
### Issues Resolved
#151 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/indices/ModelDao.java [hunk 1]
```diff
@@ -82,6 +87,13 @@
      */
     boolean isCreated();
 
+    /**
+     * gets model index's health status
+     *
+     * @return ClusterHealthStatus of model index
+     */
+    ClusterHealthStatus getHealthStatus();
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/indices/ModelDao.java:95]: Why is this cluster health status when we are interested in index status?

File: src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexStatusSupplier.java [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+     */
+    public ModelIndexStatusSupplier(Function<ModelDao, T> getter) {
+        this.getter = getter;
+    }
+
+    @Override
+    public T get() {
+        try{
+            return getter.apply(ModelDao.OpenSearchKNNModelDao.getInstance());
+        } catch (Exception e) { //catch to prevent exception to be raised.
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexStatusSupplier.java:42]: Cant we catch the IndexNotFoundException as opposed to general Exception?

File: src/main/java/org/opensearch/knn/indices/ModelDao.java (hunk 1 above)
Comment (VijayanB) [reply src/main/java/org/opensearch/knn/indices/ModelDao.java:95]: Unfortunately, this Enum is only being used to represent IndexHealth status as well since value is common among both index and cluster.

File: src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexStatusSupplier.java (hunk 2 above)
Comment (VijayanB) [reply src/main/java/org/opensearch/knn/plugin/stats/suppliers/ModelIndexStatusSupplier.java]: Ack.

**Review by jmazanec15 — APPROVED** [review]

**Review by vamshin — APPROVED** [review]
LGTM! Thanks
