### PR TITLE
Fixing bug to prevent NullPointerException while doing PUT mappings

### LINKED ISSUE #2556: [BUG] NPE while doing put mappings
**What is the bug?**
Getting NPE while doing PUT mappings.

**How can one reproduce the bug?**
1. Create index with below mappings
```
curl --request PUT \
  --url http://localhost:9200/my-knn-index-1/ \
  --header 'Content-Type: application/json' \
  --data '{
	"settings": {
		"index": {
			"number_of_shards": 1,
			"number_of_replicas": 0,
			"refresh_interval": "1s",
			"knn": true
		}
	},
	"mappings": {
		"properties": {
			"my_vector2": {
				"type": "knn_vector",
				"dimension": 4,
				"method": {
					"engine": "faiss",
					"name": "hnsw"
				}
			}
		}
	}
}'
```
2. Try doing put mappings like this
```
curl --request PUT \
  --url http://localhost:9200/my-knn-index-1/_mappings \
  --header 'Content-Type: application/json' \
  --data '{
	"properties": {
		"my_vector2": {
			"type": "knn_vector",
			"dimension": 4
		}
	}
}'
```

**Output**

```
{
	"error": {
		"root_cause": [
			{
				"type": "null_pointer_exception",
				"reason": "Cannot invoke \"org.opensearch.knn.index.engine.KNNMethodContext.getMethodComponentContext()\" because \"m\" is null"
			}
		],
		"type": "null_pointer_exception",
		"reason": "Cannot invoke \"org.opensearch.knn.index.engine.KNNMethodContext.getMethodComponentContext()\" because \"m\" is null"
	},
	"status": 500
}
```

**Stacktrace:**
```
[2025-02-25T00:07:03,874][WARN ][r.suppressed             ] [integTest-0] path: /my-knn-index-1/_mappings, params: {index=my-knn-index-1}
java.lang.NullPointerException: Cannot invoke "org.opensearch.knn.index.engine.KNNMethodContext.getMethodComponentContext()" because "m" is null
        at org.opensearch.knn.index.mapper.KNNVectorFieldMapper$Builder.lambda$new$13(KNNVectorFieldMapper.java:165) ~[?:?]
        at org.opensearch.index.mapper.ParametrizedFieldMapper$Parameter.merge(ParametrizedFieldMapper.java:347) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.ParametrizedFieldMapper$Builder.merge(ParametrizedFieldMapper.java:619) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:128) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.ParametrizedFieldMapper.merge(ParametrizedFieldMapper.java:77) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:821) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:363) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:780) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:358) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.Mapping.merge(Mapping.java:130) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:313) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.applyRequest(MetadataMappingService.java:284) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.execute(MetadataMappingService.java:245) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.service.ClusterManagerService.executeTasks(ClusterManagerService.java:889) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.service.ClusterManagerService.calculateTaskOutputs(ClusterManagerService.java:441) ~[opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.service.ClusterManagerService.runTasks(ClusterManagerService.java:301) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.service.ClusterManagerService$Batcher.run(ClusterManagerService.java:214) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:206) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:264) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:935) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246) [opensearch-3.0.0-alpha1-SNAPSHOT.jar:3.0.0-alpha1-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

```

**What is the expected behavior?**
The expected behavior is we should either block these kind of update telling user that we cannot update the mapping, or it should be similar to old behavior.

**What is your host/environment?**
ALL

**Do you have any screenshots?**
NA

**Do you have any additional context?**
NA

### PR DESCRIPTION
**Pull request by oaganesh**
### Description
Following code prevents the state of a NullPointerException from occurring while doing PUT mappings. The expected behavior is to block the update by telling the user that we cannot update the mapping.

### Related Issues
Resolves #2556

### Check List
- [ ✔️ ] New functionality includes testing.
- [ ✔️ ] New functionality has been documented.
- [ ✔️ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ✔️ ] Commits are signed per the DCO using `--signoff`.
- [ ✔️ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### Input:

Create index with below mappings:
```
curl --request PUT \
  --url http://localhost:9200/my-knn-index-1/ \
  --header 'Content-Type: application/json' \
  --data '{
	"settings": {
		"index": {
			"number_of_shards": 1,
			"number_of_replicas": 0,
			"refresh_interval": "1s",
			"knn": true
		}
	},
	"mappings": {
		"properties": {
			"my_vector2": {
				"type": "knn_vector",
				"dimension": 4,
				"method": {
					"engine": "faiss",
					"name": "hnsw"
				}
			}
		}
	}
}'
```

Try doing put mappings like this:
```
curl --request PUT \
  --url http://localhost:9200/my-knn-index-1/_mappings \
  --header 'Content-Type: application/json' \
  --data '{
	"properties": {
		"my_vector2": {
			"type": "knn_vector",
			"dimension": 4
		}
	}
}'
```
### Changes

Previous Error Output:
```
{
	"error": {
		"root_cause": [
			{
				"type": "null_pointer_exception",
				"reason": "Cannot invoke \"org.opensearch.knn.index.engine.KNNMethodContext.getMethodComponentContext()\" because \"m\" is null"
			}
		],
		"type": "null_pointer_exception",
		"reason": "Cannot invoke \"org.opensearch.knn.index.engine.KNNMethodContext.getMethodComponentContext()\" because \"m\" is null"
	},
	"status": 500
}
```
New Error Output:
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Mapping update for knn_vector fields is not supported. Cannot update mapping without the original method configuration."
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Mapping update for knn_vector fields is not supported. Cannot update mapping without the original method configuration."
    },
    "status": 400
}
```

### CODE REVIEW

**Comment by navneet1v** [comment]
The error message could be better. So the way to think about error message should be, when a user sees it he/she should able to understand what caused this error. With this error message I am not seeing that. adding @jmazanec15 , @shatejas to see how we can improve this message

File: src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java [hunk 1]
```diff
@@ -161,7 +161,15 @@ public static class Builder extends ParametrizedFieldMapper.Builder {
...
-        }), m -> m.getMethodComponentContext().getName());
+        }), m -> {
+            if (m == null) {
+                throw new IllegalArgumentException(
+                    "Mapping update for knn_vector fields is not supported. "
+                        + "Cannot update mapping without the original method configuration."
+                );
+            }
+            return m.getMethodComponentContext().getName();
+        });
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:172]: lets also have a UT and IT for this change.

**Comment by markwu-sde** [comment]
> The error message could be better. So the way to think about error message should be, when a user sees it he/she should able to understand what caused this error. With this error message I am not seeing that. adding @jmazanec15 , @shatejas to see how we can improve this message

It seems as though when [merging](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java#L347) the mappings together the expectation is that for knn the method is included when I think when defining the index it can default to FAISS without specifying an engine while the underlying document content remains without a method context. 

The scenario listed above would be a failure case where the current value has a method context but the new value doesn't. Interestingly enough the same can happen if a index was inserted without a method context but the mapping was updated with a method context.

With that in mind I think it would beneficial to tell the user that they need to maintain behavior of including/excluding the method when updating. Something like `Cannot add or remove method key for existing KNN field [%s]
` could work better here?

File: src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java (hunk 1 above)
Comment (markwu-sde) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:172]: +1

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:172]: I think we want to follow something like this instead of throwing: https://github.com/opensearch-project/OpenSearch/blob/73882054afcdb74244c07c5be1f54a629ffd0bc2/server/src/main/java/org/opensearch/index/mapper/TextParams.java#L143C13-L143C45. This is the conflictSerializer which is used to build the exception method, so no need to throw.

If I were to redo this field mapper completely, I wouldve added the toString method to KnnMethodContext so we could just follow the default: https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java#L199. But, thats out of scope for this change.

**Comment by jmazanec15** [comment]
@markwu-sde The failure happens in the parameters conflict serializer. This is used to actually build the error message. So we are getting an NPE when building the error message. So I dont think we are allowing users to update any of these parameters, its more so how we are failing.

File: src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java [hunk 2]
```diff
@@ -157,11 +156,18 @@ public static class Builder extends ParametrizedFieldMapper.Builder {
...
             m -> toType(m).originalMappingParameters.getKnnMethodContext()
-        ).setSerializer(((b, n, v) -> {
-            b.startObject(n);
-            v.toXContent(b, ToXContent.EMPTY_PARAMS);
-            b.endObject();
-        }), m -> m.getMethodComponentContext().getName());
+        ).setSerializer(
+            // Main serializer - handles null values properly
+            (b, f, v) -> {
+                if (v != null) {
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:162]: Good catch. Is there a way for this to just serialize the null value as opposed to skipping? Like, b.field(f, null) ort something

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:162]: Also I dont think we'll hit this because https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java#L195, acceptsNull is false by default, but not sure. Were you able to repro a failure case for this?

Comment (oaganesh) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:162]: Hi Jack, 
Do you mean something like this?
`(b, f, v) -> {
    b.startObject(f);
    if (v == null) {
        b.nullField("value");
    } else {
        v.toXContent(b, ToXContent.EMPTY_PARAMS);
    }
    b.endObject();
}`

Also I have not reproduced a failure case for this.

Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java:162]: I think itd be:
```
if v == null
 b.nullField(f)
else:
 b.startObject(f)
...
 b.endObject()

```

Comment (oaganesh) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java]: Modified change in latest commit

**Review by jmazanec15 — APPROVED** [review]
LGTM thanks @oaganesh !!!

**Review by markwu-sde — APPROVED** [review]
LGTM

File: src/test/java/org/opensearch/knn/index/OpenSearchIT.java [hunk 3]
```diff
@@ -1208,6 +1208,43 @@ public void testKNNIndexSearchFieldsParameterDocsWithOnlyOtherFields() throws Ex
         assertEquals(0, parseSearchResponseFieldsCount(EntityUtils.toString(response4.getEntity()), "text1"));
     }
 
+    public void testKNNVectorMappingUpdate_whenMethodRemoved_thenThrowsException() throws Exception {
```
[the remark this answers is not in the document]
Comment (oaganesh) [reply src/test/java/org/opensearch/knn/index/OpenSearchIT.java:1211]: Modified change in latest commit

File: src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java [hunk 4]
```diff
@@ -157,11 +156,20 @@ public static class Builder extends ParametrizedFieldMapper.Builder {
...
+                    b.nullField(f);
+                } else {
+                    b.startObject(f);
+                    v.toXContent(b, ToXContent.EMPTY_PARAMS);
+                    b.endObject();
+                }
+            },
+            // Conflict serializer - simple string representation for error messages
+            v -> v == null ? null : v.getMethodComponentContext().getName()
+        ).acceptsNull();
```
[the remark this answers is not in the document]
Comment (oaganesh) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java]: Updated change in latest commit

**Review by jmazanec15 — APPROVED** [review]

File: src/test/java/org/opensearch/knn/index/OpenSearchIT.java [hunk 5]
```diff
@@ -1208,6 +1208,104 @@ public void testKNNIndexSearchFieldsParameterDocsWithOnlyOtherFields() throws Ex
...
+
+        ResponseException exception = expectThrows(ResponseException.class, () -> putMappingRequest(indexName, updatedMapping.toString()));
+
+        assertThat(
+            EntityUtils.toString(exception.getResponse().getEntity()),
+            containsString("Cannot update parameter [method] from [hnsw] to [null]")
+        );
+    }
+
+    public void testKNNVectorMappingUpdate_whenDimensionChanged_thenSucceeds() throws Exception {
```
[the remark this answers is not in the document]
Comment (oaganesh) [reply src/test/java/org/opensearch/knn/index/OpenSearchIT.java:1248]: The test is not exactly updating an existing index's mapping as it is creating a new index with the specified mapping as shown below:

```
createKnnIndex(indexName, getKNNDefaultIndexSettings(), updatedMapping.toString());
```

If necessary, I can change the above test to fail when updating the mapping.

[the remark this answers is not in the document]
Comment (navneet1v) [reply src/test/java/org/opensearch/knn/index/OpenSearchIT.java:1248]: I think the name of the test is wrong. Because it gave an impression that we are updating the mappings and changing the dimension value. But that is not the case. Please fix the name or correct the test

[the remark this answers is not in the document]
Comment (oaganesh) [reply src/test/java/org/opensearch/knn/index/OpenSearchIT.java]: Understood. Changed name of test function to be more accurate.

**Review by navneet1v — APPROVED** [review]

**Review by jmazanec15 — APPROVED** [review]
