### PR TITLE
[BUG FIX] Fix knn index shard to get bwc engine paths

### LINKED ISSUE #308: Warmup API does not work for files created with older version of libs
## Description
The warmup API decides what segments to load based on the file name it would build for the segments: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNIndexShard.java#L129-L130. The problem with this is that for segment files built with older versions of a library, the lib version is included in the file name. This leads to these files getting skipped during warmup

## Proposed solution
Update warmup API logic to get files in a backwards compatible manner.

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Fixes getEnginePaths in KNNIndexShard to retrieve all engine paths, regardless of what version the index was created. Prevents silent failure when warmup completes but doesnt load any segments.

Instead of checking if the engine file that the current version of the plugin would create is in the segment, it just checks the prefix and suffix of the file that would be created. To prevent this failure in the future, a new test was added. Intentionally, the structure is hardcoded. This will ensure that this will be caught in the future if segment file naming conventions change.
 
### Issues Resolved
#308 
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — DISMISSED** [review]
LGTM! Thanks.

Some checks seem to be failing. You may want to fix it.

File: src/main/java/org/opensearch/knn/index/KNNIndexShard.java [hunk 1]
```diff
@@ -126,17 +127,21 @@ public void warmup() throws IOException {
...
                 }
             }
         }
         return engineFiles;
     }
+
+    protected Map<String, SpaceType> getEnginePaths(Collection<String> files, String segmentName, String fieldName,
+                                                   String fileExtension, Path shardPath, SpaceType spaceType) {
+        return files.stream()
+                .filter(fileName -> fileName.startsWith(buildEngineFilePrefix(segmentName)))
```
Comment (VijayanB) [inline src/main/java/org/opensearch/knn/index/KNNIndexShard.java:142]: We don't have to compute buildEngineFilePrefix for every file. This can be called once outside streams and used inside filer.

**Comment by jmazanec15** [comment]
> LGTM! Thanks.
> 
> Some checks seem to be failing. You may want to fix it.

Right. Its checkstyle. I was going to get review first before fixing it, as to not clutter the diff.

File: src/main/java/org/opensearch/knn/index/KNNIndexShard.java (hunk 1 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/KNNIndexShard.java]: Makes sense. Updated.

**Review by vamshin — DISMISSED** [review]
LGTM! Thanks

**Review by martin-gaievski — APPROVED** [review]

**Review by naveentatikonda — APPROVED** [review]

**Review by naveentatikonda — APPROVED** [review]

**Review by junqiu-lei — APPROVED** [review]

**Review by martin-gaievski — APPROVED** [review]

**Review by vamshin — APPROVED** [review]
