### PR TITLE
Fix memory overflow caused by cache behavior

### LINKED ISSUE #1582: Investigate rearchitecture of the native memory circuit breaker
## Description

Wanted to put out an issue to track potentially rearch our current circuit breaker/native memory management system. Currently, our circuit breaking logic has a couple flaws and can be confusing to users. I think that we should consider re-architecting it to be more in line with the JVM heap based circuit breaker that OpenSearch uses (https://github.com/opensearch-project/OpenSearch/blob/main/libs/core/src/main/java/org/opensearch/core/common/breaker/CircuitBreaker.java)

A couple issues I have with our circuit breaker:
1. Caching allocations and limiting memory is tied together in a guava cache. This makes it difficult to impose custom limits per-allocation type
2. All allocation types sit in a single allocation manager. This can make it tricky for complex management like we had in #1507. Also, it makes it very difficult if another plugin perhaps wanted to introduce their own native memory allocation type
3. Guava cache does not free memory allocations immediately when they are evicted. This can lead to going over circuit breaker limit in native memory consumption
4. We do not track large allocations during indexing time
5. We require consumers of native memory allocations to acquire locks. This can make the code very hard to manage and requires delicate handling of exceptions etc.

## Proposed Solution
I think we should investigate migrating towards the approach OpenSearch has taken for the jvm circuit breaker limits. This would allow:
1. Through the a hierarchical mem management system, we could separate management of diff memory allocations while still imposing a global limit. This would make the system more extendable
2. Per allocation type memory management would allow us to take more control over memory free life cycle. This would allow us to migrate away from problems associated with guava cache freeing.
3. Provide a more consistent OpenSearch user experience by following conventions set for existing circuit breaker

### PR DESCRIPTION
**Pull request by kotwanikunal**
### Description
- Adds in a force evict mechanism before entry to prevent memory overflow for native memory usage within the cache
- This solution works in tandem with `jemalloc` enabled. In case of default `malloc`, there are potential delays with memory free up operations leading to similar scenarios
- The solution has been tested and benchmarked - described in the Testing section below

### Problem
- The problem stems from the behavior of the cache where in entries of the cache might not be cleaned up as soon as they are evictable
- This delay between new entry and cleanup can, in our case, cause the memory to overflow - leading to a node failure

### Solution
- This solution aims at maintaining an additional recency list within the cache manager
- On every `get` call - 
  - in case of a cache hit - it just marks the key as recent, returns the value
  - in case of a cache miss - it adds the key to the recency list, loads the item into the cache and returns
  - in case of a cache miss & a potential overflow - eviction process kicks off before the item is loaded into the cache 

### Testing

1. **Case: Enough memory available**
  - Scenario description: Indexed 1M 768d vectors on a 3 node cluster with 16GB memory - 8GB heap, 8GB for graph files, ran an OSB query load with and without the fix
  - TLDR; Not a ton of deviation from current code in terms of raw numbers. Results below

| Index Type    | Dimension | Number Of Vectors | Min Throughput | Mean Throughput | Median Throughput | Max Throughput | 50th percentile latency | 90th percentile latency | 99th percentile latency | 100th percentile latency | 50th percentile service time | 90th percentile service time | 99th percentile service time | 100th percentile service time | Mean recall@k | Mean recall@1 |
| ------------- | --------- | ----------------- | -------------- | --------------- | ----------------- | -------------- | ----------------------- | ----------------------- | ----------------------- | ------------------------ | ---------------------------- | ---------------------------- | ---------------------------- | ----------------------------- | ------------- | ------------- |
| Current Code  | 768       | 1,000,000         | 2.46           | 2.68            | 2.69              | 2.74           | 358.268                 | 382.036                 | 414.636                 | 482.332                  | 358.268                      | 382.036                      | 414.636                      | 482.332                       | 0.98          | 1             |
| Code with Fix | 768       | 1,000,000         | 2.55           | 2.71            | 2.7               | 2.75           | 363.62                  | 398.338                 | 432.811                 | 447.278                  | 363.62                       | 398.338                      | 432.811                      | 447.278                       | 0.98          | 1             |

2. **Case: Heavy query load scenario**
  - Scenario: Created 3 indexes (2 FAISS, 1 NMSLIB), Indexed 1M 768d vectors on a 3 node cluster with 16GB memory - 8GB heap, 8GB for graph files, ran 3 parallel query workloads for all the indexes at once. 
  - TLDR; **Without the fix** - noticed node crashes. **With the fix** - there was an uptick in error due to timeouts, latency increased but no node crash was observed

| Index Type      | Dimension | Number Of Vectors | Min Throughput | Mean Throughput | Median Throughput | Max Throughput | 50th percentile latency | 90th percentile latency | 99th percentile latency | 100th percentile latency | 50th percentile service time | 90th percentile service time | 99th percentile service time | 100th percentile service time | Error rate % | Mean recall@k | Mean recall@1 |
| --------------- | --------- | ----------------- | -------------- | --------------- | ----------------- | -------------- | ----------------------- | ----------------------- | ----------------------- | ------------------------ | ---------------------------- | ---------------------------- | ---------------------------- | ----------------------------- | ------------ | ------------- | ------------- |
| Index1 with fix | 768       | 1,000,000         | 0.05           | 0.06            | 0.06              | 0.09           | 13228.9                 | 19363.3                 | 24602.8                 | 35710.1                  | 13228.9                      | 19363.3                      | 24602.8                      | 35710.1                       | 11           | 0.99          | 1             |
| Index2 with fix | 768       | 1,000,000         | 0.1            | 0.25            | 0.14              | 1.02           | 11728.5                 | 15634.2                 | 23228.2                 | 34283.1                  | 11728.5                      | 15634.2                      | 23228.2                      | 34283.1                       | 0            | 0.98          | 1             |
| Index3 with fix | 768       | 1,000,000         | 0.06           | 0.07            | 0.07              | 0.09           | 12575                   | 17641.8                 | 25928.4                 | 27722.8                  | 12575                        | 17641.8                      | 25928.4                      | 27722.8                       | 3            | 0.98          | 1             |

### Related Issues
Partially resolves #1582 (Case 3)

### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).~
- [x] Commits are signed per the DCO using `--signoff`.
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java [hunk 1]
```diff
@@ -163,11 +164,19 @@ class IndexAllocation implements NativeMemoryAllocation {
...
+            Runnable onClose = () -> {
                 writeLock();
                 cleanup();
                 writeUnlock();
-            });
+            };
+
+            // The close operation needs to be blocking to prevent overflow
+            // This blocks any entry until the close has completed, preventing creation before close scenarios
+            if (KNNFeatureFlags.isForceEvictCacheEnabled()) {
```
Comment (heemin32) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java:175]: Have you tested with only this change without a code which try to evict before adding value to cache to see if node crash or not?

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 2]
```diff
@@ -301,7 +306,47 @@ public NativeMemoryAllocation get(NativeMemoryEntryContext<?> nativeMemoryEntryC
...
+            // Utilizes a force eviction mechanism to free up memory before the entry can be added to the cache
+            // In case of a cache hit, the operation just updates the locally maintained recency list
+            // In case of a cache miss, least recently accessed entries are evicted in a blocking manner
+            // before the new entry can be added to the cache.
+            String key = nativeMemoryEntryContext.getKey();
+            NativeMemoryAllocation result = cache.getIfPresent(key);
+
+            // Cache Hit
+            if (result != null) {
+                accessRecencyQueue.remove(key);
```
Comment (heemin32) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: This is concerning part when there are many graphs in a single node. This remove is linear complexity and this code path will be hit for every query. I think the benchmark case might not have enough segment files to see the degradation.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 3]
```diff
@@ -301,7 +306,47 @@ public NativeMemoryAllocation get(NativeMemoryEntryContext<?> nativeMemoryEntryC
...
+                accessRecencyQueue.addLast(key);
```
Comment (heemin32) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:320]: There is a chance that same key can be added more than once in the queue.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 4]
```diff
@@ -301,7 +306,47 @@ public NativeMemoryAllocation get(NativeMemoryEntryContext<?> nativeMemoryEntryC
...
+                    Iterator<String> lruIterator = accessRecencyQueue.iterator();
+                    while (lruIterator.hasNext()
+                        && (getCacheSizeInKilobytes() + nativeMemoryEntryContext.calculateSizeInKB() >= maxWeight)) {
+
+                        String keyToRemove = lruIterator.next();
+                        NativeMemoryAllocation allocationToRemove = cache.getIfPresent(keyToRemove);
+                        if (allocationToRemove != null) {
+                            allocationToRemove.close();
+                            cache.invalidate(keyToRemove);
+                            lruIterator.remove();
```
Comment (heemin32) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:337]: If we remove key from dequeue only when it is available in cache, some key will stay in the dequeue forever.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java [hunk 5]
```diff
@@ -163,11 +164,19 @@ class IndexAllocation implements NativeMemoryAllocation {
 
         @Override
         public void close() {
-            executor.execute(() -> {
+            Runnable onClose = () -> {
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java:167]: Oh I like this - I was always wondering if we actually need to run this in an executor context. Anecdotally from you testing, how long would this method typically run?

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 6]
```diff
@@ -97,7 +102,7 @@ private void initialize(NativeMemoryCacheManagerDto nativeMemoryCacheDTO) {
         }
 
         cacheCapacityReached = new AtomicBoolean(false);
-
+        accessRecencyQueue = new ConcurrentLinkedDeque<>();
```
Comment (jmazanec15) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:105]: So - why cant we rely on guava cache to do this? I forget some of the details around how size based evictions take place.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java (hunk 1 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java:175]: Yes. As I pointed out in the testing section - the nodes did crash.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: I think most of your concerns are around queue efficiency/operations. 

Let me see if I can replace it to a ordered set and make it work good enough. We do not have an out of the box concurrent ordered set solution.
We can always use `Collections.synchronizedSet(new LinkedHashSet<>())` - but the efficiency of wrapped concurrent collections is not as efficient.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java (hunk 5 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java:167]: I did not run numbers specifically for this block. Do you want me to get those numbers?

Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java:167]: The other general problem with this today is that when the cache calls the `onRemoval` method for an entry - based on the Guava's documentation - it is supposed to be blocking. 
So when the cache is trying to clean up - forking the operation on this thread enables the cache to have a different usage metric compared to what is held by native memory indexes, further exacerbating the overflow problem.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 7]
```diff
@@ -301,7 +306,47 @@ public NativeMemoryAllocation get(NativeMemoryEntryContext<?> nativeMemoryEntryC
...
+                if (getCacheSizeInKilobytes() + nativeMemoryEntryContext.calculateSizeInKB() >= maxWeight) {
+                    Iterator<String> lruIterator = accessRecencyQueue.iterator();
+                    while (lruIterator.hasNext()
+                        && (getCacheSizeInKilobytes() + nativeMemoryEntryContext.calculateSizeInKB() >= maxWeight)) {
+
+                        String keyToRemove = lruIterator.next();
+                        NativeMemoryAllocation allocationToRemove = cache.getIfPresent(keyToRemove);
+                        if (allocationToRemove != null) {
+                            allocationToRemove.close();
+                            cache.invalidate(keyToRemove);
```
Comment (heemin32) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:336]: Will this call `close()` one more time by Guava?

Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:336]: Yes. Which should be fine since `close()` is idempotent. 

https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java#L173-L177

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (heemin32) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: Can we consider utilizing removal listener?

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: +1 on @heemin32 comment. Is there a way we can avoid having our own queue/set and use removal listener from Guava cache? Does Guava cache provides a sync way to remove the items from cache?

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 3 above)
Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:320]: There should not be the case where 1 key is added more than once in the queue.

But looking at the current code I think 319 and 320 should be in a sync block so that only 1 thread is updating the key Even when the queue is `ConcurrentLinkedDeque`, as this is a transaction on the key

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 4 above)
Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:337]: +1. Even if there is not allocation present on the key the key should be removed from the queue.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: That is the root of our problems - there are currently two async operations that happen for cache entry removal - 

1. The notification from Guava is not guaranteed to be before entry i.e the object cleanup can happen after an entry is added
2. The `close` on `NativeMemoryAllocation` objects is forked off into a separate thread (`onRemoval` from the cache is supposed to be sync with the removal flow)

This PR solves both of these problems. If we could utilize the listener directly - we would not be in this problem in the first place :) 

Details: https://github.com/google/guava/wiki/CachesExplained#when-does-cleanup-happen)

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 4 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:337]: Ack. This will be updated with the next rev.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (heemin32) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: I think removal listener should be called earlier enough unlike cleanup? Can we test it?
```
If your cache should not grow beyond a certain size, just use [CacheBuilder.maximumSize(long)](https://guava.dev/releases/snapshot/api/docs/com/google/common/cache/CacheBuilder.html#maximumSize-long-). The cache will try to evict entries that haven't been used recently or very often. Warning: the cache may evict entries before this limit is exceeded -- typically when the cache size is approaching the limit.
```

```
You may specify a removal listener for your cache to perform some operation when an entry is removed, via [CacheBuilder.removalListener(RemovalListener)](https://guava.dev/releases/snapshot/api/docs/com/google/common/cache/CacheBuilder.html#removalListener-com.google.common.cache.RemovalListener-). The [RemovalListener](https://guava.dev/releases/snapshot/api/docs/com/google/common/cache/RemovalListener.html) gets passed a [RemovalNotification](https://guava.dev/releases/snapshot/api/docs/com/google/common/cache/RemovalNotification.html), which specifies the [RemovalCause](https://guava.dev/releases/snapshot/api/docs/com/google/common/cache/RemovalCause.html), key, and value.
```

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 6 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:105]: https://github.com/opensearch-project/k-NN/pull/2015#discussion_r1742382795

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java (hunk 5 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryAllocation.java:167]: Ran some numbers - I could only get averages.

With default code (current code) - 4.26076555024 ms averaged across nodes 
With modified code - 1.63179895861 ms averaged across nodes  (Possibly because the block is sync already)

**Comment by kotwanikunal** [comment]
Ran some tests for LinkedHashSet vs the current queue implementation. Results:

| Index Type              | Dimension | Number Of Vectors | Min Throughput | Mean Throughput | Median Throughput | Max Throughput | 50th percentile latency | 90th percentile latency | 99th percentile latency | 100th percentile latency | Error rate % | Mean recall@k | Mean recall@1 |
| ----------------------- | --------- | ----------------- | -------------- | --------------- | ----------------- | -------------- | ----------------------- | ----------------------- | ----------------------- | ------------------------ | ------------ | ------------- | ------------- |
| Single Query Queue      | 768       | 1,000,000         | 1.28           | 2.37            | 2.46              | 2.58           | 368.768                 | 417.358                 | 483.694                 | 761.651                  | 0            | 0.98          | 0.97          |
| Single Query Sync Set   | 768       | 1,000,000         | 1.1            | 1.97            | 2.07              | 2.3            | 407.133                 | 516.032                 | 658.99                  | 889.347                  | 0            | 0.98          | 0.97          |
|                         |           |                   |                |                 |                   |                |                         |                         |                         |                          |              |               |               |
| Parallel Query Queue    | 768       | 1,000,000         | 0.07           | 0.07            | 0.07              | 0.09           | 13465.6                 | 18455.7                 | 31858                   | 33136.6                  | 0            | 0.99          | 1             |
| Parallel Query Sync Set | 768       | 1,000,000         | 0.06           | 0.07            | 0.06              | 0.08           | 13937                   | 18936.5                 | 28190.5                 | 28804.4                  | 8            | 0.99          | 1             |

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:319]: Ran some more tests for the comparison between the two approaches (set vs optimized concurrent queue) - https://github.com/opensearch-project/k-NN/pull/2015#issuecomment-2327064680

It does look like the concurrent optimized version of the queue helps with perf.

Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: @heemin32 We do have an `onRemoval` listener attached: [Ref code](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java#L383-L394)

The problem is that this is called after an entry is made into the cache - so there is still a potential for memory overflow - leading to node drops.

To validate this - I tested a theory using minimal changes from this solution
- Made no changes to the `get` method from `NativeMemoryCacheManager` 
- Made the `close()` method from `NativeMemoryAllocation` to be sync with the `onRemoval` method

This still led to memory overflows and node drop scenarios.
We need both the things to work in tandem.
The solutions are using an additional DS (like this solution) or design a cache that has strict enforcement.

**Review by navneet1v — APPROVED** [review]
Approving the PR. I do understand that by adding updating element in the queue is not fully optimized but as the solution provides more stability(in memory constraint situation)I am good with the approach.

I would suggest turning on the feature flag so that we can see the impact of this in the nightlies. But I will leave this upto the author.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (heemin32) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: I would like to explore other cache option like caffeine or ehcache but I guess it can be discussed in a separate thread.

The main concern here is removing and adding entry in dequeue. 
Because this code path is called for every query, it could impact to query latency with high number of segments compared to current implementation.
One other approach would be having last access time in the cache item itself and updating it for every get operation. When eviction is needed, we scan the entire entry and evict least accessed item.

Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: The general idea here was to add in correctness.
A minor increase in latency is a lot better than node drops in my opinion. And this can be looked at as an incremental solution. 

With the feature flag turned off - you get the same performance as you do today. But for use cases where node drops are a bigger problem, we can turn on force eviction.

And your concerns are valid - this is not the most optimized solution currently. But it is a step in that direction.
We can work on improving it before enabling the feature by default.

File: src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+@UtilityClass
+public class KNNFeatureFlags {
+
+    // Feature flags
+    private static final String KNN_FORCE_EVICT_CACHE_ENABLED = "knn.feature.cache.force_evict.enabled";
+
+    @VisibleForTesting
+    public static final Setting<Boolean> KNN_FORCE_EVICT_CACHE_ENABLED_SETTING = Setting.boolSetting(
+        KNN_FORCE_EVICT_CACHE_ENABLED,
+        false,
```
[the remark this answers is not in the document]
Comment (kotwanikunal) [reply src/main/java/org/opensearch/knn/common/featureflags/KNNFeatureFlags.java:33]: Given @heemin32's callouts and concerns, I think we can let it default to `false` for now. I can turn it on by default once I have some more optimizations in.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (heemin32) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: - Is there any urgency on this feature? Otherwise, implementing it without feature flag is the best.

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: > Is there any urgency on this feature? Otherwise, implementing it without feature flag is the best.

Feature flag is there to be more of a defensive mechanism, since all tests cannot be covered and this code touches the hot code path. What I am not able to understand is why this question is coming up? Because this is a good feature that adds stability to cluster.

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: > I would like to explore other cache option like caffeine or ehcache but I guess it can be discussed in a separate thread.

@heemin32 
Do you know that the limitations of Guava cache is not present in these caches?

Comment (heemin32) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: >Feature flag is there to be more of a defensive mechanism, since all tests cannot be covered and this code touches the hot code path. What I am not able to understand is why this question is coming up? Because this is a good feature that adds stability to cluster.

The question is more about the urgency not the need of this feature. I feel feature flag is mostly for user to configure the behavior. As a method of defensive mechanism, we should invest more on testing.
I think we can avoid using dequeue which puts latency for every query. Instead we can have last accessed time en cache entry and evict them when the cache is full where some latency won't have a big impact.

I haven't checked if they don't have the limitation of Guava cache.

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:324]: I see this as a bug in k-NN plugin, and with more. 


> As a method of defensive mechanism, we should invest more on testing.

There has been testing around it but not all cases can be covered. Hence having this helps.

> I think we can avoid using dequeue which puts latency for every query. Instead we can have last accessed time en cache entry and evict them when the cache is full where some latency won't have a big impact.

What you mean by this?


> I haven't checked if they don't have the limitation of Guava cache.

Then this is the best solution we have for now.

**Review by heemin32 — APPROVED** [review]
Approving it as this is behind feature flag and it is false by default. We might need a test with higher number of segments.

**Comment by kotwanikunal** [comment]
Backport: https://github.com/opensearch-project/k-NN/pull/2032
