### PR TITLE
Block index creation for byte-cosinesimilarity-faiss indices

### LINKED ISSUE #2955: [BUG] Block index creation for byte-cosinesimilarity-faiss combination
**What is the bug?**
Currently when data_type is byte, spaceType is consinesimilarity and engine is faiss, an error is thrown during ingestion of document
```
"caused_by": { "type": "unsupported_operation_exception", "reason": "Byte array normalization is not supported" }
```

Ask is to block index creation instead of throwing at ingestion

### PR DESCRIPTION
**Pull request by kasundra07**
### Description
Block index creation for Faiss engine with cosine similarity and byte vectors due to normalization incompatibility.

### Testing
```
% curl -X PUT "http://localhost:9200/test-byte-cosine" -H "Content-Type: application/json" -d'        
{
  "settings": {
    "index.knn": true
  },
  "mappings": {
    "properties": {
      "my_vector": {
        "type": "knn_vector",
        "dimension": 3,
        "data_type": "byte",
        "space_type": "cosinesimil",
        "method": {
          "name": "hnsw",
          "engine": "faiss"
        }
      }
    }
  }
}'
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Faiss engine does not support cosine similarity with byte vectors. Cosine similarity requires vector normalization which is only supported for float vectors. Please use float data type or choose a different space type like l2 or inner_product."}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Faiss engine does not support cosine similarity with byte vectors. Cosine similarity requires vector normalization which is only supported for float vectors. Please use float data type or choose a different space type like l2 or inner_product.","caused_by":{"type":"illegal_argument_exception","reason":"Faiss engine does not support cosine similarity with byte vectors. Cosine similarity requires vector normalization which is only supported for float vectors. Please use float data type or choose a different space type like l2 or inner_product."}},"status":400}
```

### Related Issues
Resolves #2955 

### Check List
- [X] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java [hunk 1]
```diff
@@ -526,6 +526,9 @@ private void validateFromKNNMethod(KNNVectorFieldMapper.Builder builder) {
                 throw validationException;
             }
 
+            // Validate Faiss engine specific constraints
+            validateFaissEngineConstraints(builder);
```
Comment (Vikasht34) [inline src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java]: Though This solution will work but it will be harder to scale if we keep dumping validations on validateFromKNNMethod. I think there would be two Places we can do this validation better 

1. Engine Level Validation :- we already have Faiss.java class and KnnEngine Enum , if we can restrict the validation with help of these two classes , we can all the validation regarding specific engine at places where it's functionality is there. 
2. Data Type Level Validation :- In this Class we are reading data type like this 

```
protected final Parameter<VectorDataType> vectorDataType = new Parameter<>(
            VECTOR_DATA_TYPE_FIELD,
            false,
            () -> DEFAULT_VECTOR_DATA_TYPE_FIELD,
            (n, c, o) -> VectorDataType.get((String) o),
            m -> toType(m).originalMappingParameters.getVectorDataType()
        )
```

and Parent class for this is ParametrizedFieldMapper , where we already have functinality to do setValidation , If we can write a validator function difrectly attached to vectorDataType that will also be scalable solution. 

```
public Parameter<T> setValidator(Consumer<T> validator) {
            this.validator = validator;
            return this;
        }
```

But I will prefer approach 1.

Comment (navneet1v) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java]: +1 on the comment. Dumping validation in the mapper is not a scalable idea. One way to think where to put this validation is from where this validation is coming from? Like is this a data type validation or an Engine Validation. If we see space type constraint on valid datatype(byte being a valid datatype) comes from Engine(since a engine might not support a certain datatype like Faiss may not support L1, or in this case cosine with Byte vector) we should move this validation inside FaissEngine class via KNNEngine being base class.

Comment (kasundra07) [reply src/main/java/org/opensearch/knn/index/mapper/KNNVectorFieldMapper.java]: Thanks for the feedback. I agree that having engine-level validations makes it more scalable. I've moved the validation to `Faiss.java` class.

**Comment by MrFlap** [comment]
CIs are failing due to the issue here: https://github.com/opensearch-project/k-NN/issues/3005

**Review by VijayanB — APPROVED** [review]
LGTM
