### PR TITLE
Remove latestSettings cache from KNNSettings

### LINKED ISSUE #585: [BUG] KNN memory circuit breaker limit in opensearch.yaml
**Describe the bug**
The setting `knn.memory.circuit_breaker.limit` doesn't seem to be respected when set in the `opensearch.yaml`. Even setting it in `/_cluster/settings` does not work unless I remove the setting from `opensearch.yaml`

**To Reproduce**
1. Set `knn.memory.circuit_breaker.limit: 56200000KB` in `opensearch.yaml`
2. Warm up an index
3. Check `/_plugins/_knn/*/stats` and calculate `graph_memory_usage*100/graph_memory_usage_percentage`. This will be 50% of the native memory.
4. Set `knn.memory.circuit_breaker.limit: 56200000KB` in the persistent settings (`/_cluster/settings`) and repeat 2-3.
5. Now remove `knn.memory.circuit_breaker.limit: 56200000KB` from `opensearch.yaml` and repeat 2-3. This time the result should be 56200000.

**Expected behavior**
The `opensearch.yaml` setting should be picked up correctly.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by jmazanec15**
### Description
Removes the latestSettings cache from the KNNSettings class. latestSettings cache gets updated in a consumer when the particular settings are updated.

[KNNSettings.getSettingValue](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNSettings.java#L305) would pull from this cache and then fallback to the default if it is not present. However, in the case when the settings are set via opensearch.yml config file, the settings get set before any functions can be registered. So the config values never get put in the cache. This leads to getSettingValue to always return the default instead of the value specified in the config file.

To fix this, this change refactors getSettingValue to pull from the cluster settings and removes the latestSetting cache. However, because the dynamicCacheSettings have [consumers](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNSettings.java#L269) that rebuild the NativeMemoryCacheManager cache when they are changed, the logic for passing the parameters to rebuild this cache had to change as well. Initially, the NativeMemoryCacheManager gets its [parameters](https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java#L77) from the settings. However, because we are switching "getSettingValue" to get the values from the ClusterSettings, the new cluster settings will not yet be committed to the cluster state when the settings update consumer is called (it gets called in this chain starting [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/admin/cluster/settings/SettingsUpdater.java#L158)). To workaround this, this change refactors the cache to accept parameters as args.

In addition to this, I added a couple tests units tests and did some refactoring to get tests to pass.

### Issues Resolved
#585 
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [X] Commits are signed as per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/index/KNNSettings.java [hunk 1]
```diff
@@ -262,35 +265,33 @@ public static synchronized KNNSettings state() {
...
+            boolean isCircuitBreakerEnabled = updatedSettings.getAsBoolean(
+                KNN_MEMORY_CIRCUIT_BREAKER_ENABLED,
+                getSettingValue(KNN_MEMORY_CIRCUIT_BREAKER_ENABLED)
+            );
 
-                // Rebuild the cache with updated limit
-                NativeMemoryCacheManager.getInstance().rebuildCache();
-            });
-        }
+            ByteSizeValue maxCacheWeight = getSettingValue(KNN_MEMORY_CIRCUIT_BREAKER_LIMIT);
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/knn/index/KNNSettings.java:277]: nit: can we change maxCacheWeight type to long, this way it's gonna be consistent with expiryTimeInMinutes setting. now we do have both primitive object and getter of complex. seems maxCacheWeight it's not used anywhere else in this method so ByteSizeValue type is not required

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 2]
```diff
@@ -93,13 +100,33 @@ private void initialize() {
...
+    public synchronized void rebuildCache(boolean isWeightLimited, long maxWeight, boolean isExpirationLimited, long expiryTimeInMin) {
         logger.info("KNN Cache rebuilding.");
 
-        // TODO: Does this really need to be executed with an executor? Also, does invalidateAll really need to be
-        // called?
+        // TODO: Does this really need to be executed with an executor?
         executor.execute(() -> {
-            cache.invalidateAll();
-            initialize();
+            if (cache != null) {
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:124]: curious did we have an NPE with `cache` var or it's more of being on a safe side?

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java [hunk 3]
```diff
@@ -68,20 +68,27 @@ public static synchronized NativeMemoryCacheManager getInstance() {
...
     private void initialize() {
+        initialize(
+            KNNSettings.state().getSettingValue(KNNSettings.KNN_MEMORY_CIRCUIT_BREAKER_ENABLED),
+            KNNSettings.getCircuitBreakerLimit().getKb(),
+            KNNSettings.state().getSettingValue(KNNSettings.KNN_CACHE_ITEM_EXPIRY_ENABLED),
+            ((TimeValue) KNNSettings.state().getSettingValue(KNNSettings.KNN_CACHE_ITEM_EXPIRY_TIME_MINUTES)).getMinutes()
+        );
+    }
+
+    private void initialize(boolean isWeightLimited, long maxWeight, boolean isExpirationLimited, long expiryTimeInMin) {
```
Comment (martin-gaievski) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:79]: nit: I suggest we use DTO instead of 4 arguments. It's will increase maintainability for future changes if we need to add/remove settings, especially as we can re-use DTO in multiple places, e.g. rebuildCache, tests etc.

File: src/test/java/org/opensearch/knn/index/KNNSettingsTests.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+import java.util.Collections;
+import java.util.List;
+import java.util.Map;
+
+import static org.opensearch.test.NodeRoles.dataNode;
+
+public class KNNSettingsTests extends KNNTestCase {
+
+    @SneakyThrows
+    public void testGetSettingValueFromConfig() {
```
Comment (martin-gaievski) [inline src/test/java/org/opensearch/knn/index/KNNSettingsTests.java:43]: I assume that would fail without changes in rebuild cache? do we need to include other settings as well?

**Comment by navneet1v** [comment]
> However, in the case when the settings are set via opensearch.yml config file, the settings update consumers never get called, so the config values never get put in the cache.

The better explanation for this as per the deep-dive done was config(from .yml) gets set at the start, before any functions can be registered. Hence the .yml file config will not trigger the settings update, as these are updates.

File: src/main/java/org/opensearch/knn/index/KNNSettings.java (hunk 1 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/KNNSettings.java:277]: Sure, will update.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 2 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:124]: I dont think this can be reached. The only time the cache will be null will be if rebuildCache is called before the constructor, but I dont think this can happen. I think Ill remove this.

File: src/test/java/org/opensearch/knn/index/KNNSettingsTests.java (hunk 4 above)
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/index/KNNSettingsTests.java:43]: Not sure I understand what you mean by "that would fail without changes in rebuild cache". Could you elaborate?

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java (hunk 3 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManager.java:79]: Sure, will update

File: src/test/java/org/opensearch/knn/index/KNNSettingsTests.java (hunk 4 above)
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/index/KNNSettingsTests.java:37]: > I mean is this test, if it exists before your PR, fail without you code change?

Yes, this was the failure before the fix:
```
  2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.knn.index.KNNSettingsTests.testGetSettingValueFromConfig" -Dtests.seed=2B1E0A6CFDBD324B -Dtests.security.manager=false -Dtests.locale=fr -Dtests.timezone=America/Paramaribo -Druntime.java=11
  2> java.lang.AssertionError: expected:<8126464> but was:<13>
        at __randomizedtesting.SeedInfo.seed([2B1E0A6CFDBD324B:4423BA039518D35]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
```

I think my actual and expected are mixed up, but Ill go ahead and fix this.

> And second question is about settings, we're checking here only for KNNSettings.KNN_MEMORY_CIRCUIT_BREAKER_LIMIT, but we have other settings like KNNSettings.KNN_CACHE_ITEM_EXPIRY_ENABLED and KNNSettings.KNN_CACHE_ITEM_EXPIRY_TIME_MINUTES, do we need to have similar test for them as well?

I think it is probably okay to test just one. We group all of the dynamic cache settings here: https://github.com/opensearch-project/k-NN/blob/main/src/main/java/org/opensearch/knn/index/KNNSettings.java#L223 and then dont handle them uniquely from there, so I think we are okay.

**Comment by jmazanec15** [comment]
@navneet1v true, I updated the PR description to reflect this.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerDto.java [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+package org.opensearch.knn.index.memory;
+
+import lombok.Builder;
+import lombok.Getter;
+
+@Getter
+@Builder
```
Comment (navneet1v) [inline src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerDto.java:12]: [Minor]
if you use @Value and @Builder then you don't need add @Getter and you can remove final from every variable as @Value will make class variables final.

**Comment by navneet1v** [comment]
Minor comments overall code looks good to me.

File: src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerDto.java (hunk 5 above)
Comment (jmazanec15) [reply src/main/java/org/opensearch/knn/index/memory/NativeMemoryCacheManagerDto.java:12]: Makes sense. Will add.

File: src/test/java/org/opensearch/knn/KNNTestCase.java [hunk 6]
```diff
@@ -30,6 +41,18 @@ public static void resetState() {
             knnCounter.set(0L);
         }
 
+        ClusterService clusterService = mock(ClusterService.class);
```
[the remark this answers is not in the document]
Comment (jmazanec15) [reply src/test/java/org/opensearch/knn/KNNTestCase.java]: Sure, will update.

**Review by navneet1v — APPROVED** [review]
